import type { ResidentCapability, ResidentCapabilityAction, ResidentCapabilityId } from '../models/ResidentCapability';
import type { ResidentCapabilityAudience } from '../models/ResidentRoleCapability';
import { residentRequiredScenarioMatrix } from '../models/ResidentScenario';

const allResidentRoles: readonly ResidentCapabilityAudience[] = [
  'owner',
  'coOwner',
  'tenant',
  'familyMember',
  'authorizedOccupant',
];

const ownerRoles: readonly ResidentCapabilityAudience[] = ['owner', 'coOwner'];
const ownerTenantRoles: readonly ResidentCapabilityAudience[] = ['owner', 'coOwner', 'tenant'];
const activeStatuses = ['active', 'moveOutPending'] as const;
const commonStates = [
  'loaded',
  'empty',
  'partialData',
  'paginationLoading',
  'paginationExhausted',
  'recoverableError',
  'nonRecoverableError',
  'offlineCached',
  'permissionDenied',
  'featureDisabled',
  'membershipSuspended',
  'residenceUnavailable',
] as const;

const readActions: readonly ResidentCapabilityAction[] = ['view', 'retry'];
const manageActions: readonly ResidentCapabilityAction[] = ['view', 'create', 'edit', 'submit', 'cancel', 'retry'];

export const residentCapabilityRegistry: readonly ResidentCapability[] = [
  { id: 'resident.authentication', featureArea: 'access', allowedRoles: allResidentRoles, allowedMembershipStatuses: ['active', 'pendingApproval', 'accessRestricted', 'moveOutPending', 'inactive'], ownerConfiguredFamilyPermissionRequired: false, guardianManagedAccessAllowed: true, requiredFeatureFlag: 'residentAuthentication', route: 'ResidentAuth', repository: 'residentAuthRepository', supportedActions: ['view', 'submit', 'retry'], supportedStates: commonStates, requiredTests: residentRequiredScenarioMatrix },
  { id: 'resident.membership', featureArea: 'access', allowedRoles: allResidentRoles, allowedMembershipStatuses: ['active', 'pendingApproval', 'accessRestricted', 'moveOutPending', 'inactive'], ownerConfiguredFamilyPermissionRequired: false, guardianManagedAccessAllowed: true, requiredFeatureFlag: 'residentMemberships', route: 'ResidentMembership', repository: 'residentMembershipRepository', supportedActions: ['view', 'submit', 'approve', 'reject', 'retry'], supportedStates: commonStates, requiredTests: residentRequiredScenarioMatrix },
  { id: 'resident.homeContext', featureArea: 'homes', allowedRoles: allResidentRoles, allowedMembershipStatuses: ['active', 'pendingApproval', 'accessRestricted', 'moveOutPending'], ownerConfiguredFamilyPermissionRequired: false, guardianManagedAccessAllowed: true, requiredFeatureFlag: 'multiHome', route: 'ResidentHome', repository: 'residentHomeContextRepository', supportedActions: ['view', 'switchResidence', 'retry'], supportedStates: commonStates, requiredTests: residentRequiredScenarioMatrix },
  { id: 'resident.household', featureArea: 'household', allowedRoles: ownerRoles, allowedMembershipStatuses: activeStatuses, ownerConfiguredFamilyPermissionRequired: false, guardianManagedAccessAllowed: false, requiredFeatureFlag: 'familyMemberManagement', route: 'HouseholdOverview', repository: 'residentHouseholdRepository', permission: 'OWNER_TENANT_VIEW_CURRENT', supportedActions: [...manageActions, 'managePermissions'], supportedStates: commonStates, requiredTests: residentRequiredScenarioMatrix },
  { id: 'resident.familyPortability', featureArea: 'household', allowedRoles: ownerRoles, allowedMembershipStatuses: activeStatuses, ownerConfiguredFamilyPermissionRequired: false, guardianManagedAccessAllowed: false, requiredFeatureFlag: 'familyPortability', route: 'FamilyPortability', repository: 'residentLifecycleRepository', permission: 'OWNER_TENANT_VIEW_CURRENT', supportedActions: ['view', 'linkPerson', 'submit', 'cancel', 'retry'], supportedStates: commonStates, requiredTests: residentRequiredScenarioMatrix },
  { id: 'resident.tenantLifecycle', featureArea: 'occupancy', allowedRoles: ownerTenantRoles, allowedMembershipStatuses: activeStatuses, ownerConfiguredFamilyPermissionRequired: false, guardianManagedAccessAllowed: false, requiredFeatureFlag: 'tenantOnboarding', route: 'TenantManagement', repository: 'ownerTenantRepository', permission: 'OWNER_TENANT_VIEW_CURRENT', supportedActions: manageActions, supportedStates: commonStates, requiredTests: residentRequiredScenarioMatrix },
  { id: 'resident.rentalDeclaration', featureArea: 'occupancy', allowedRoles: ownerRoles, allowedMembershipStatuses: activeStatuses, ownerConfiguredFamilyPermissionRequired: false, guardianManagedAccessAllowed: false, requiredFeatureFlag: 'rentalDeclaration', route: 'RentalDeclaration', repository: 'residentLifecycleRepository', permission: 'OWNER_TENANT_VIEW_CURRENT', supportedActions: manageActions, supportedStates: commonStates, requiredTests: residentRequiredScenarioMatrix },
  { id: 'resident.shortStay', featureArea: 'occupancy', allowedRoles: ownerRoles, allowedMembershipStatuses: activeStatuses, ownerConfiguredFamilyPermissionRequired: false, guardianManagedAccessAllowed: false, requiredFeatureFlag: 'shortStayManagement', route: 'ShortStayManagement', repository: 'residentLifecycleRepository', permission: 'OWNER_TENANT_VIEW_CURRENT', supportedActions: [...manageActions, 'checkIn', 'checkOut'], supportedStates: commonStates, requiredTests: residentRequiredScenarioMatrix },
  { id: 'resident.visitors', featureArea: 'security', allowedRoles: allResidentRoles, allowedMembershipStatuses: activeStatuses, ownerConfiguredFamilyPermissionRequired: true, guardianManagedAccessAllowed: false, requiredFeatureFlag: 'visitorManagement', route: 'VisitorTab', repository: 'visitorsRepository', permission: 'VISITOR_VIEW', supportedActions: manageActions, supportedStates: commonStates, requiredTests: residentRequiredScenarioMatrix },
  { id: 'resident.billing', featureArea: 'finance', allowedRoles: ownerTenantRoles, allowedMembershipStatuses: activeStatuses, ownerConfiguredFamilyPermissionRequired: false, guardianManagedAccessAllowed: false, requiredFeatureFlag: 'maintenanceBilling', route: 'BillTab', repository: 'residentBillingRepository', permission: 'BILL_VIEW', supportedActions: ['view', 'pay', 'download', 'share', 'retry'], supportedStates: commonStates, requiredTests: residentRequiredScenarioMatrix },
  { id: 'resident.complaints', featureArea: 'support', allowedRoles: allResidentRoles, allowedMembershipStatuses: activeStatuses, ownerConfiguredFamilyPermissionRequired: true, guardianManagedAccessAllowed: false, requiredFeatureFlag: 'complaints', route: 'ComplaintTab', repository: 'residentComplaintsRepository', permission: 'COMPLAINT_VIEW', supportedActions: manageActions, supportedStates: commonStates, requiredTests: residentRequiredScenarioMatrix },
  { id: 'resident.interFlatIssues', featureArea: 'support', allowedRoles: allResidentRoles, allowedMembershipStatuses: activeStatuses, ownerConfiguredFamilyPermissionRequired: true, guardianManagedAccessAllowed: false, requiredFeatureFlag: 'interFlatIssues', route: 'InterFlatStack', repository: 'interFlatRepository', permission: 'INTER_FLAT_VIEW_OWN', supportedActions: manageActions, supportedStates: commonStates, requiredTests: residentRequiredScenarioMatrix },
  { id: 'resident.notices', featureArea: 'governance', allowedRoles: allResidentRoles, allowedMembershipStatuses: activeStatuses, ownerConfiguredFamilyPermissionRequired: true, guardianManagedAccessAllowed: true, requiredFeatureFlag: 'notices', route: 'NoticeListFromHome', repository: 'noticesRepository', permission: 'NOTICE_VIEW', supportedActions: [...readActions, 'acknowledge'], supportedStates: commonStates, requiredTests: residentRequiredScenarioMatrix },
  { id: 'resident.governance', featureArea: 'governance', allowedRoles: ownerTenantRoles, allowedMembershipStatuses: activeStatuses, ownerConfiguredFamilyPermissionRequired: false, guardianManagedAccessAllowed: false, requiredFeatureFlag: 'governance', route: 'GovernanceStack', repository: 'governanceRepository', permission: 'GOVERNANCE_VIEW', supportedActions: ['view', 'submit', 'acknowledge', 'retry'], supportedStates: commonStates, requiredTests: residentRequiredScenarioMatrix },
  { id: 'resident.documents', featureArea: 'records', allowedRoles: allResidentRoles, allowedMembershipStatuses: activeStatuses, ownerConfiguredFamilyPermissionRequired: true, guardianManagedAccessAllowed: false, requiredFeatureFlag: 'documentVault', route: 'DocumentVaultHome', repository: 'documentRepository', permission: 'DOCUMENT_VIEW_OWN', supportedActions: ['view', 'create', 'download', 'share', 'retry'], supportedStates: commonStates, requiredTests: residentRequiredScenarioMatrix },
  { id: 'resident.nocAndMoveOut', featureArea: 'records', allowedRoles: ownerTenantRoles, allowedMembershipStatuses: activeStatuses, ownerConfiguredFamilyPermissionRequired: false, guardianManagedAccessAllowed: false, requiredFeatureFlag: 'digitalNocRequests', route: 'NocRequestList', repository: 'nocRepository', permission: 'NOC_VIEW', supportedActions: manageActions, supportedStates: commonStates, requiredTests: residentRequiredScenarioMatrix },
  { id: 'resident.parking', featureArea: 'mobility', allowedRoles: ownerTenantRoles, allowedMembershipStatuses: activeStatuses, ownerConfiguredFamilyPermissionRequired: false, guardianManagedAccessAllowed: false, requiredFeatureFlag: 'parkingVehicles', route: 'ParkingStack', repository: 'parkingRepository', permission: 'PARKING_VIEW', supportedActions: manageActions, supportedStates: commonStates, requiredTests: residentRequiredScenarioMatrix },
  { id: 'resident.facilities', featureArea: 'amenities', allowedRoles: allResidentRoles, allowedMembershipStatuses: activeStatuses, ownerConfiguredFamilyPermissionRequired: true, guardianManagedAccessAllowed: false, requiredFeatureFlag: 'facilityBooking', route: 'FacilityStack', repository: 'facilityRepository', permission: 'FACILITY_BOOK', supportedActions: ['view', 'book', 'reschedule', 'cancel', 'retry'], supportedStates: commonStates, requiredTests: residentRequiredScenarioMatrix },
  { id: 'resident.chat', featureArea: 'communication', allowedRoles: allResidentRoles, allowedMembershipStatuses: activeStatuses, ownerConfiguredFamilyPermissionRequired: true, guardianManagedAccessAllowed: false, requiredFeatureFlag: 'controlledGroupChat', route: 'ChatTab', repository: 'residentChatRepository', permission: 'RESIDENT_CHAT', supportedActions: ['view', 'message', 'retry'], supportedStates: commonStates, requiredTests: residentRequiredScenarioMatrix },
  { id: 'resident.residentConnect', featureArea: 'communication', allowedRoles: allResidentRoles, allowedMembershipStatuses: activeStatuses, ownerConfiguredFamilyPermissionRequired: true, guardianManagedAccessAllowed: false, requiredFeatureFlag: 'residentMessenger', route: 'ResidentConnectStack', repository: 'residentConnectRepository', permission: 'RESIDENT_CONNECT_REQUEST', supportedActions: ['view', 'message', 'block', 'report', 'retry'], supportedStates: commonStates, requiredTests: residentRequiredScenarioMatrix },
  { id: 'resident.domesticHelp', featureArea: 'staff', allowedRoles: ownerTenantRoles, allowedMembershipStatuses: activeStatuses, ownerConfiguredFamilyPermissionRequired: false, guardianManagedAccessAllowed: false, requiredFeatureFlag: 'residentDomesticHelp', route: 'DomesticHelp', repository: 'domesticHelpRepository', permission: 'DOMESTIC_HELP_VIEW', supportedActions: manageActions, supportedStates: commonStates, requiredTests: residentRequiredScenarioMatrix },
  { id: 'resident.emergency', featureArea: 'safety', allowedRoles: allResidentRoles, allowedMembershipStatuses: activeStatuses, ownerConfiguredFamilyPermissionRequired: true, guardianManagedAccessAllowed: true, requiredFeatureFlag: 'residentEmergency', route: 'EmergencySafetyStack', repository: 'residentEmergencyRepository', supportedActions: ['view', 'triggerSos', 'configure', 'retry'], supportedStates: commonStates, requiredTests: residentRequiredScenarioMatrix },
  { id: 'resident.community', featureArea: 'community', allowedRoles: allResidentRoles, allowedMembershipStatuses: activeStatuses, ownerConfiguredFamilyPermissionRequired: true, guardianManagedAccessAllowed: false, requiredFeatureFlag: 'communityMarketplace', route: 'CommunityStack', repository: 'communityRepository', permission: 'COMMUNITY_VIEW', supportedActions: manageActions, supportedStates: commonStates, requiredTests: residentRequiredScenarioMatrix },
  { id: 'resident.settings', featureArea: 'preferences', allowedRoles: allResidentRoles, allowedMembershipStatuses: ['active', 'pendingApproval', 'accessRestricted', 'moveOutPending'], ownerConfiguredFamilyPermissionRequired: false, guardianManagedAccessAllowed: true, requiredFeatureFlag: 'profileSettings', route: 'ProfileTab', repository: 'residentSettingsRepository', supportedActions: ['view', 'edit', 'configure', 'retry'], supportedStates: commonStates, requiredTests: residentRequiredScenarioMatrix },
  { id: 'resident.notifications', featureArea: 'preferences', allowedRoles: allResidentRoles, allowedMembershipStatuses: ['active', 'pendingApproval', 'accessRestricted', 'moveOutPending'], ownerConfiguredFamilyPermissionRequired: false, guardianManagedAccessAllowed: true, requiredFeatureFlag: 'residentNotifications', route: 'NotificationSettings', repository: 'residentNotificationRepository', supportedActions: ['view', 'configure', 'retry'], supportedStates: commonStates, requiredTests: residentRequiredScenarioMatrix },
];

export function getResidentCapability(id: ResidentCapabilityId): ResidentCapability {
  const capability = residentCapabilityRegistry.find((entry) => entry.id === id);
  if (!capability) {
    throw new Error(`Resident capability is not registered: ${id}`);
  }
  return capability;
}
