import type { AuditEventType } from './audit.types';

export const auditEventTypes: AuditEventType[] = [
  'DOCUMENT_VIEW_ATTEMPT',
  'DOCUMENT_DOWNLOAD_ATTEMPT',
  'NOC_REQUEST_CREATED',
  'MOVE_OUT_REQUEST_CREATED',
  'VISITOR_PASS_CREATED',
  'GATE_ENTRY_RECORDED',
  'COMPLAINT_CREATED',
  'PAYMENT_ATTEMPT_STARTED',
  'RESIDENT_CONTACT_REQUEST_CREATED',
  'CHAT_MESSAGE_REPORTED',
  'PARKING_INCIDENT_CREATED',
  'FACILITY_BOOKING_CREATED',
  'WORK_ORDER_CREATED',
  'VENDOR_BLACKLIST_ATTEMPTED',
  'POLL_VOTE_SUBMITTED',
  'MEETING_RSVP_SUBMITTED',
  'PROXY_AUTHORIZATION_SUBMITTED',
  'PERMISSION_DENIED_VIEW',
];
