import { mockStore } from '../../../core/mockStore/mockStore';
import type {
  NocCertificate,
  NocRequest,
  NocStatus,
  NocType,
} from '../../../shared/types/noc.types';
import type { ClearanceSnapshot, ClearanceStatus } from '../../../shared/types/moveOut.types';
import type { Absent } from '../../../shared/types/absence.types';

const withMockDelay = <T>(data: T, ms = 400): Promise<T> =>
  new Promise((resolve) => setTimeout(() => resolve(data), ms));

function generateId(prefix: string): string {
  return `${prefix}-${Date.now()}-${Math.random().toString(36).substring(2, 9)}`;
}

function generateCertificateNumber(type: NocType): string {
  const prefixMap: Record<NocType, string> = {
    NO_DUES: 'NOC-ND',
    MOVE_OUT: 'NOC-MO',
    TENANT_NOC: 'NOC-TN',
    PARKING_NOC: 'NOC-PK',
    RENOVATION_NOC: 'NOC-RN',
    RESIDENCE_CERTIFICATE: 'NOC-RC',
    VEHICLE_NOC: 'NOC-VH',
  };
  const prefix = prefixMap[type] || 'NOC';
  const year = new Date().getFullYear();
  const seq = Math.floor(1000 + Math.random() * 9000);
  return `${prefix}-${year}-${seq}`;
}

function generateVerificationCode(): string {
  const chars = 'ABCDEFGHJKLMNPQRSTUVWXYZ23456789';
  let code = '';
  for (let i = 0; i < 8; i++) {
    code += chars.charAt(Math.floor(Math.random() * chars.length));
  }
  return `${code.slice(0, 4)}-${code.slice(4)}`;
}

export const nocService = {
  async generateMoveOutCertificate(
    moveOutRequestId: string,
    clearanceSnapshotId: string,
    generatedBy: string
  ): Promise<NocCertificate> {
    return new Promise((resolve, reject) => {
      setTimeout(() => {
        const requests = mockStore.getState().moveOutRequests || [];
        const request = requests.find((r) => r.id === moveOutRequestId);
        if (!request) {
          reject(new Error('Move-out request not found'));
          return;
        }

        const snapshots = mockStore.getState().clearanceSnapshots || [];
        const snapshot = snapshots.find((s) => s.id === clearanceSnapshotId);
        if (!snapshot) {
          reject(new Error('Clearance snapshot not found'));
          return;
        }

        const certificate: NocCertificate = {
          id: generateId('cert'),
          title: 'Move-Out Clearance Certificate',
          nocType: 'MOVE_OUT',
          certificateNumber: generateCertificateNumber('MOVE_OUT'),
          societyName: request.societyId || 'Society',
          flatNumber: request.unitId || 'N/A',
          residentName: request.residentId || 'Resident',
          issueDate: new Date().toISOString().split('T')[0] ?? '',
          issuedBy: generatedBy,
          clearanceSummary: `Clearance snapshot ${clearanceSnapshotId} verified. All mandatory clearances satisfied.`,
          verificationCode: generateVerificationCode(),
          disclaimer: 'This certificate is generated by Society OS. The digital signatures on file verify this copy is authentic.',
        };

        const certs = mockStore.getState().nocCertificates;
        if (certs) {
          certs.push(certificate);
        } else {
          mockStore.getState().nocCertificates = [certificate];
        }

        const nocRequest: NocRequest = {
          id: generateId('noc'),
          requestNumber: generateId('noc-req'),
          nocType: 'MOVE_OUT',
          flatNumber: request.unitId || 'N/A',
          residentName: request.residentId || 'Resident',
          submittedDate: new Date().toISOString().split('T')[0] ?? '',
          requiredByDate: new Date().toISOString().split('T')[0] ?? '',
          status: 'GENERATED' as NocStatus,
          reason: 'Move-out clearance certificate',
          timeline: [
            { title: 'NOC Generated', status: 'COMPLETED', updatedAt: new Date().toISOString(), actor: generatedBy },
          ],
          certificateId: certificate.id,
        };

        const nocs = mockStore.getState().nocs;
        if (nocs) {
          nocs.push(nocRequest);
        } else {
          mockStore.getState().nocs = [nocRequest];
        }
        mockStore.notify();

        resolve(certificate);
      }, 800);
    });
  },

  async getCertificate(certificateId: string): Promise<NocCertificate | null> {
    return withMockDelay(
      mockStore.getState().nocCertificates?.find((c) => c.id === certificateId) || null
    );
  },

  async getCertificateByVerificationCode(verificationCode: string): Promise<NocCertificate | null> {
    return withMockDelay(
      mockStore.getState().nocCertificates?.find((c) => c.verificationCode === verificationCode) || null
    );
  },

  async verifyNoc(verificationCode: string): Promise<{
    valid: boolean;
    certificate?: NocCertificate;
    status: 'VALID' | 'INVALID' | 'REVOKED' | 'EXPIRED';
    message?: string;
  }> {
    return new Promise((resolve) => {
      setTimeout(() => {
        const certificates = mockStore.getState().nocCertificates || [];
        const certificate = certificates.find((c) => c.verificationCode === verificationCode);

        if (!certificate) {
          resolve({
            valid: false,
            status: 'INVALID',
            message: 'No certificate found with this verification code',
          });
          return;
        }

        if (certificate.expiryDate && new Date(certificate.expiryDate) < new Date()) {
          resolve({
            valid: false,
            certificate,
            status: 'EXPIRED',
            message: 'Certificate has expired',
          });
          return;
        }

        resolve({
          valid: true,
          certificate,
          status: 'VALID',
        });
      }, 500);
    });
  },

  async revokeCertificate(certificateId: string, revokedBy: string, reason: string): Promise<NocCertificate> {
    return new Promise((resolve, reject) => {
      setTimeout(() => {
        const certificates = mockStore.getState().nocCertificates;
        if (!certificates) {
          reject(new Error('Certificate not found'));
          return;
        }
        const index = certificates.findIndex((c) => c.id === certificateId);
        if (index === -1) {
          reject(new Error('Certificate not found'));
          return;
        }
        const current = certificates[index];
        if (!current) {
          reject(new Error('Certificate not found'));
          return;
        }

        const updated: NocCertificate = {
          ...current,
          disclaimer: `${current.disclaimer}\n\nREVOKED by ${revokedBy} on ${new Date().toISOString()}: ${reason}`,
        };
        certificates[index] = updated;
        mockStore.notify();
        resolve(updated);
      }, 500);
    });
  },

  async getCertificatesByMoveOutRequest(moveOutRequestId: string): Promise<NocCertificate[]> {
    return withMockDelay(
      mockStore.getState().nocCertificates?.filter((c) => c.id.startsWith(moveOutRequestId)) || []
    );
  },

  async createClearanceSnapshot(
    moveOutRequestId: string,
    generatedBy: string,
    checklist: Array<{ id: string; title: string; category?: string; status: string; priority?: string }>
  ): Promise<ClearanceSnapshot> {
    return new Promise((resolve) => {
      setTimeout(() => {
        const now = new Date().toISOString();
        const snapshot: ClearanceSnapshot = {
          id: generateId('snapshot'),
          moveOutRequestId,
          generatedAt: now,
          generatedBy,
          clearanceItems: checklist.map((item) => ({
            id: item.id,
            title: item.title,
            description: item.title,
            responsibleTeam: 'Operations',
            status: item.status as ClearanceStatus,
            ...(item.priority ? { priority: item.priority as 'MANDATORY' | 'OPTIONAL' } : {}),
          })),
          overallStatus: checklist.every((i) => i.status === 'CLEARED' || i.status === 'OVERRIDDEN' || i.status === 'WAIVED' || i.status === 'NOT_APPLICABLE')
            ? 'READY'
            : 'EXCEPTION',
          blockingItems: checklist.filter((i) => i.priority === 'MANDATORY' && i.status === 'BLOCKED').map((item) => ({
            id: item.id,
            title: item.title,
            description: item.title,
            responsibleTeam: 'Operations',
            status: item.status as ClearanceStatus,
            ...(item.priority ? { priority: item.priority as 'MANDATORY' | 'OPTIONAL' } : {}),
          })),
          policyVersion: '1.0',
          checksum: `${Date.now()}`,
        };

        const snapshots = mockStore.getState().clearanceSnapshots;
        if (snapshots) {
          snapshots.push(snapshot);
        } else {
          mockStore.getState().clearanceSnapshots = [snapshot];
        }
        mockStore.notify();

        resolve(snapshot);
      }, 500);
    });
  },
};

export default nocService;