export const apiEndpoints = {
    bootstrap: {
        app: '/app/bootstrap',
        societyFeatures: (societyId: string) => `/societies/${societyId}/features`,
        society: (societyId: string) => `/societies/${societyId}`,
        societySettings: (societyId: string) => `/societies/${societyId}/settings`,
    },
    auth: {
        requestOtp: '/auth/otp/request',
        verifyOtp: '/auth/otp/verify',
        resendOtp: '/auth/otp/resend',
        registerResident: '/auth/residents/register',
        acceptResidentInvitation: '/auth/resident-invitations/accept',
        login: '/auth/login',
        refresh: '/auth/refresh-token',
        refreshToken: '/auth/refresh-token',
        logout: '/auth/logout',
        logoutAll: '/auth/logout-all-devices',
        logoutAllDevices: '/auth/logout-all-devices',
        me: '/auth/me',
    },
    resident: {
        me: '/residents/me',
        dashboard: '/residents/me/dashboard',
        units: '/residents/me/units',
        notificationsSummary: '/residents/me/notifications-summary',
        notifications: '/residents/me/notifications',
        preferences: '/residents/me/preferences',
        homeContexts: '/me/residences',
        activeHomeContext: '/me/active-residence',
        contextualInsights: '/residents/me/contextual-insights',
        dismissContextualInsight: (suggestionId: string) => `/residents/me/contextual-insights/${suggestionId}/dismiss`,
        memberships: '/resident/memberships',
        membershipDetail: (membershipId: string) => `/resident/memberships/${membershipId}`,
        requestAccess: '/resident/memberships/access-requests',
        sendReminder: (membershipId: string) => `/resident/memberships/${membershipId}/reminders`,
        withdrawRequest: (membershipId: string) => `/resident/memberships/${membershipId}/withdraw`,
        resubmitRequest: (membershipId: string) => `/resident/memberships/${membershipId}/resubmit`,
        timeline: (membershipId: string) => `/resident/memberships/${membershipId}/timeline`,
        onboarding: (membershipId: string) => `/resident/memberships/${membershipId}/onboarding`,
        saveOnboardingStep: (membershipId: string, stepId: string) => `/resident/memberships/${membershipId}/onboarding/steps/${stepId}`,
        completeOnboarding: (membershipId: string) => `/resident/memberships/${membershipId}/onboarding/complete`,
        registerPushToken: '/devices/push-token',
        deletePushToken: '/devices/push-token',
    },
    areas: {
        weatherSnapshot: (areaId: string) => `/areas/${areaId}/weather-snapshot`,
        localAdvisories: (areaId: string) => `/areas/${areaId}/local-advisories`,
    },
    chat: {
        societyChannels: (societyId: string) => `/api/societies/${societyId}/chat-channels`,
        staffMemberships: (societyId: string, userId: string) => `/api/societies/${societyId}/staff/${userId}/channel-memberships`,
        membership: (societyId: string, membershipId: string) => `/api/societies/${societyId}/channel-memberships/${membershipId}`,
        channelMembers: (societyId: string, channelId: string) => `/api/societies/${societyId}/chat-channels/${channelId}/members`,
    },
    society: {
        units: (societyId: string) => `/societies/${societyId}/units`,
        unit: (societyId: string, unitId: string) => `/societies/${societyId}/units/${unitId}`,
        occupancyHistory: (societyId: string, unitId: string) => `/societies/${societyId}/units/${unitId}/occupancy-history`,
    },
    visitors: {
        list: '/visitors',
        detail: (visitorPassId: string) => `/visitors/${visitorPassId}`,
        preapprove: '/visitors/preapprove',
        cancel: (visitorPassId: string) => `/visitors/${visitorPassId}/cancel`,
        approve: (visitorPassId: string) => `/visitors/${visitorPassId}/approve`,
        reject: (visitorPassId: string) => `/visitors/${visitorPassId}/reject`,
        exitAlerts: '/api/resident/visitor-exit-alerts',
        confirmExitLeft: (alertId: string) => `/api/resident/visitor-exit-alerts/${alertId}/confirm-left`,
        confirmExitStillInside: (alertId: string) => `/api/resident/visitor-exit-alerts/${alertId}/confirm-still-inside`,
        extendExit: (alertId: string) => `/api/resident/visitor-exit-alerts/${alertId}/extend`,
        contactSecurityForExit: (alertId: string) => `/api/resident/visitor-exit-alerts/${alertId}/contact-security`,
    },
    gate: {
        passesToday: '/gate/passes/today',
        passSearch: '/gate/passes/search',
        passDetail: (passId: string) => `/gate/passes/${passId}`,
        entries: '/gate/entries',
        manualEntries: '/gate/entries/manual',
        quickEntries: '/gate/entries/quick',
        activity: '/gate/activity',
        offlineQueue: '/gate/offline-queue',
        offlineQueueSync: '/gate/offline-queue/sync',
        emergencyAlerts: '/gate/emergency-alerts',
        shiftHandover: '/gate/shift-handover',
    },
    staff: {
        today: '/staff/today',
        detail: (staffId: string) => `/staff/${staffId}`,
        checkIn: (staffId: string) => `/staff/${staffId}/check-in`,
        checkOut: (staffId: string) => `/staff/${staffId}/check-out`,
        attendanceCorrections: (staffId: string) => `/staff/${staffId}/attendance-corrections`,
        monthlyAttendance: '/staff-attendance/monthly',
    },
    complaints: {
        list: '/complaints',
        create: '/complaints',
        detail: (complaintId: string) => `/complaints/${complaintId}`,
        update: (complaintId: string) => `/complaints/${complaintId}`,
        comments: (complaintId: string) => `/complaints/${complaintId}/comments`,
        reopen: (complaintId: string) => `/complaints/${complaintId}/reopen`,
        feedback: (complaintId: string) => `/complaints/${complaintId}/feedback`,
    },
    notices: {
        list: '/notices',
        detail: (noticeId: string) => `/notices/${noticeId}`,
        acknowledge: (noticeId: string) => `/notices/${noticeId}/acknowledge`,
        unreadCount: '/notices/unread-count',
    },
    billing: {
        bills: '/bills',
        billDetail: (billId: string) => `/bills/${billId}`,
        billReceipt: (billId: string) => `/bills/${billId}/receipt`,
        paymentOrders: '/payments/orders',
        paymentDetail: (paymentId: string) => `/payments/${paymentId}`,
        paymentReceipt: (receiptId: string) => `/payments/receipts/${receiptId}`,
        paymentCallback: '/payments/callback',
        residentSummary: '/api/resident/billing/summary',
        residentBills: '/api/resident/billing/bills',
        residentBillDetail: (billId: string) => `/api/resident/billing/bills/${billId}`,
        residentBillLineItems: (billId: string) => `/api/resident/billing/bills/${billId}/line-items`,
        residentLedger: '/api/resident/billing/ledger',
        residentMockPayment: '/api/resident/billing/payments/mock-confirm',
    },
    documents: {
        list: '/documents',
        create: '/documents',
        detail: (documentId: string) => `/documents/${documentId}`,
        update: (documentId: string) => `/documents/${documentId}`,
        delete: (documentId: string) => `/documents/${documentId}`,
        downloadUrl: (documentId: string) => `/documents/${documentId}/download-url`,
        accessLogs: (documentId: string) => `/documents/${documentId}/access-logs`,
        accessEvents: (documentId: string) => `/documents/${documentId}/access-events`,
        versions: (documentId: string) => `/documents/${documentId}/versions`,
        accessRequests: (documentId: string) => `/documents/${documentId}/access-requests`,
    },
    residentLifecycle: {
        familyPortabilityPlan: (residenceId: string) => `/residences/${residenceId}/family-portability`,
        copyFamilyMembers: '/family-members/copy',
        rentalDeclaration: (residenceId: string) => `/residences/${residenceId}/rental-declaration`,
        shortStays: (residenceId: string) => `/residences/${residenceId}/short-stays`,
        shortStay: (residenceId: string, stayId: string) => `/residences/${residenceId}/short-stays/${stayId}`,
        shortStayAction: (residenceId: string, stayId: string, action: string) => `/residences/${residenceId}/short-stays/${stayId}/${action}`,
    },
    noc: {
        requests: '/noc-requests',
        createRequest: '/noc-requests',
        requestDetail: (requestId: string) => `/noc-requests/${requestId}`,
        updateRequest: (requestId: string) => `/noc-requests/${requestId}`,
        submitRequest: (requestId: string) => `/noc-requests/${requestId}/submit`,
        cancelRequest: (requestId: string) => `/noc-requests/${requestId}/cancel`,
        certificate: (certificateId: string) => `/noc-certificates/${certificateId}`,
        verifyCertificate: (certificateId: string) => `/noc-certificates/${certificateId}/verify`,
    },
    move: {
        createMoveIn: '/move-in-requests',
        moveInDetail: (requestId: string) => `/move-in-requests/${requestId}`,
        createMoveOut: '/move-out-requests',
        moveOutDetail: (requestId: string) => `/move-out-requests/${requestId}`,
        moveOutClearanceChecklist: (requestId: string) => `/move-out-requests/${requestId}/clearance-checklist`,
        submitMoveOut: (requestId: string) => `/move-out-requests/${requestId}/submit`,
        cancelMoveOut: (requestId: string) => `/move-out-requests/${requestId}/cancel`,
    },
    occupancy: {
        currentOwner: (societyId: string, unitId: string) => `/societies/${societyId}/units/${unitId}/current-owner`,
        currentTenant: (societyId: string, unitId: string) => `/societies/${societyId}/units/${unitId}/current-tenant`,
        currentResidents: (societyId: string, unitId: string) => `/societies/${societyId}/units/${unitId}/current-residents`,
        familyMembers: (societyId: string, unitId: string) => `/societies/${societyId}/units/${unitId}/family-members`,
        familyMemberDetail: (societyId: string, unitId: string, memberId: string) => `/societies/${societyId}/units/${unitId}/family-members/${memberId}`,
        vehicles: (societyId: string, unitId: string) => `/societies/${societyId}/units/${unitId}/vehicles`,
        vehicleDetail: (societyId: string, unitId: string, vehicleId: string) => `/societies/${societyId}/units/${unitId}/vehicles/${vehicleId}`,
        ownerHistory: (societyId: string, unitId: string) => `/societies/${societyId}/units/${unitId}/owner-history`,
        ownerHistoryDetail: (societyId: string, unitId: string, ownerHistoryId: string) => `/societies/${societyId}/units/${unitId}/owner-history/${ownerHistoryId}`,
        tenantHistory: (societyId: string, unitId: string) => `/societies/${societyId}/units/${unitId}/tenant-history`,
        tenantHistoryDetail: (societyId: string, unitId: string, tenantHistoryId: string) => `/societies/${societyId}/units/${unitId}/tenant-history/${tenantHistoryId}`,
        occupancyTimeline: (societyId: string, unitId: string) => `/societies/${societyId}/units/${unitId}/occupancy-timeline`,
        occupancyOverview: (societyId: string, unitId: string) => `/societies/${societyId}/units/${unitId}/occupancy-overview`,
        occupancySummary: (societyId: string, unitId: string) => `/societies/${societyId}/units/${unitId}/occupancy-summary`,
        prevResidentDocs: (societyId: string, unitId: string, residentHistoryId: string) => `/societies/${societyId}/units/${unitId}/previous-residents/${residentHistoryId}/documents`,
        prevResidentDocAccessRequest: (societyId: string, unitId: string, residentHistoryId: string) => `/societies/${societyId}/units/${unitId}/previous-residents/${residentHistoryId}/document-access-requests`,
        moveInRequests: '/move-in-requests',
        createMoveInRequest: '/move-in-requests',
        moveInRequestDetail: (requestId: string) => `/move-in-requests/${requestId}`,
        submitMoveInRequest: (requestId: string) => `/move-in-requests/${requestId}/submit`,
        cancelMoveInRequest: (requestId: string) => `/move-in-requests/${requestId}/cancel`,
        accessStatus: (societyId: string, unitId: string) => `/societies/${societyId}/units/${unitId}/access-status`,
        accessActivate: (societyId: string, unitId: string) => `/societies/${societyId}/units/${unitId}/access/activate`,
        accessSuspend: (societyId: string, unitId: string) => `/societies/${societyId}/units/${unitId}/access/suspend`,
        accessRevoke: (societyId: string, unitId: string) => `/societies/${societyId}/units/${unitId}/access/revoke`,
    },
    residentConnect: {
        directory: '/resident-directory',
        directorySearch: '/resident-directory/search',
        directoryGroups: '/resident-connect/directory',
        directoryProfile: (residentProfileId: string) => `/resident-connect/directory/${residentProfileId}`,
        flatDetails: (unitId: string) => `/resident-directory/flats/${unitId}`,
        preview: (residentId: string) => `/resident-directory/residents/${residentId}/preview`,
        privacySettings: '/resident-directory/privacy-settings',
        updatePrivacySettings: '/resident-directory/privacy-settings',
        requests: '/resident-connect/requests',
        incomingRequests: '/resident-connect/requests/incoming',
        outgoingRequests: '/resident-connect/requests/outgoing',
        requestDetail: (requestId: string) => `/resident-connect/requests/${requestId}`,
        acceptRequest: (requestId: string) => `/resident-connect/requests/${requestId}/accept`,
        rejectRequest: (requestId: string) => `/resident-connect/requests/${requestId}/reject`,
        blockRequest: (requestId: string) => `/resident-connect/requests/${requestId}/block`,
        reportRequest: (requestId: string) => `/resident-connect/requests/${requestId}/report`,
        cancelRequest: (requestId: string) => `/resident-connect/requests/${requestId}/cancel`,
        contacts: '/resident-connect/contacts',
        blockedResidents: '/resident-connect/blocked-residents',
        blockResident: '/resident-connect/blocked-residents',
        unblockResident: (blockedResidentId: string) => `/resident-connect/blocked-residents/${blockedResidentId}`,
        threads: '/resident-connect/threads',
        directConversations: '/resident-connect/conversations',
        directConversationMessages: (conversationId: string) => `/resident-connect/conversations/${conversationId}/messages`,
        threadDetail: (threadId: string) => `/resident-connect/threads/${threadId}`,
        threadMessages: (threadId: string) => `/resident-connect/threads/${threadId}/messages`,
        createMessage: (threadId: string) => `/resident-connect/threads/${threadId}/messages`,
        markRead: (threadId: string) => `/resident-connect/threads/${threadId}/mark-read`,
        muteThread: (threadId: string) => `/resident-connect/threads/${threadId}/mute`,
        archiveThread: (threadId: string) => `/resident-connect/threads/${threadId}/archive`,
        reportMessage: (messageId: string) => `/resident-connect/messages/${messageId}/report`,
        reports: '/resident-connect/reports',
        reportDetail: (reportId: string) => `/resident-connect/reports/${reportId}`,
    },
    parking: {
        home: (societyId: string, unitId: string) => `/societies/${societyId}/units/${unitId}/parking/home`,
        vehicles: (societyId: string, unitId: string) => `/societies/${societyId}/units/${unitId}/vehicles`,
        createVehicle: (societyId: string, unitId: string) => `/societies/${societyId}/units/${unitId}/vehicles`,
        vehicleDetail: (societyId: string, unitId: string, vehicleId: string) => `/societies/${societyId}/units/${unitId}/vehicles/${vehicleId}`,
        vehicleGateHistory: (vehicleId: string) => `/vehicles/${vehicleId}/gate-history`,
        vehicleSearch: '/vehicles/search',
        slots: (societyId: string) => `/societies/${societyId}/parking/slots`,
        slotDetail: (societyId: string, slotId: string) => `/societies/${societyId}/parking/slots/${slotId}`,
        unitSlots: (societyId: string, unitId: string) => `/societies/${societyId}/units/${unitId}/parking-slots`,
        requestSlotChange: (societyId: string, slotId: string) => `/societies/${societyId}/parking/slots/${slotId}/request-change`,
        visitorPasses: '/parking/visitor-passes',
        visitorPassDetail: (visitorParkingPassId: string) => `/parking/visitor-passes/${visitorParkingPassId}`,
        cancelVisitorPass: (visitorParkingPassId: string) => `/parking/visitor-passes/${visitorParkingPassId}/cancel`,
        extendVisitorPass: (visitorParkingPassId: string) => `/parking/visitor-passes/${visitorParkingPassId}/extend`,
        incidents: '/parking/incidents',
        createIncident: '/parking/incidents',
        incidentDetail: (incidentId: string) => `/parking/incidents/${incidentId}`,
        updateIncident: (incidentId: string) => `/parking/incidents/${incidentId}`,
        incidentNotes: (incidentId: string) => `/parking/incidents/${incidentId}/notes`,
        resolveIncident: (incidentId: string) => `/parking/incidents/${incidentId}/resolve`,
        escalateIncident: (incidentId: string) => `/parking/incidents/${incidentId}/escalate`,
        falseResolution: (incidentId: string) => `/parking/incidents/${incidentId}/false-resolution`,
        violations: '/parking/violations',
        violationDetail: (violationId: string) => `/parking/violations/${violationId}`,
        disputeViolation: (violationId: string) => `/parking/violations/${violationId}/dispute`,
        stickers: '/parking/stickers',
        stickerDetail: (stickerId: string) => `/parking/stickers/${stickerId}`,
        requestSticker: '/parking/stickers/request',
        markStickerLost: (stickerId: string) => `/parking/stickers/${stickerId}/mark-lost`,
        requestRfid: '/parking/rfid/request',
        rfidDetail: (rfidTagId: string) => `/parking/rfid/${rfidTagId}`,
        deactivateRfid: (rfidTagId: string) => `/parking/rfid/${rfidTagId}/deactivate`,
        guardVehicleLookup: '/guard/vehicles/lookup',
        guardAllowEntry: (vehicleId: string) => `/guard/vehicles/${vehicleId}/allow-entry`,
        guardMarkSuspicious: (vehicleId: string) => `/guard/vehicles/${vehicleId}/mark-suspicious`,
        guardManualLog: (vehicleId: string) => `/guard/vehicles/${vehicleId}/manual-log`,
        hardwareReadiness: (societyId: string) => `/societies/${societyId}/parking/hardware-readiness`,
        anprConfig: (societyId: string) => `/societies/${societyId}/parking/anpr-config`,
        rfidConfig: (societyId: string) => `/societies/${societyId}/parking/rfid-config`,
        rules: '/parking/rules',
    },
    facilities: {
        list: (societyId: string) => `/societies/${societyId}/facilities`,
        detail: (societyId: string, facilityId: string) => `/societies/${societyId}/facilities/${facilityId}`,
        rules: (societyId: string, facilityId: string) => `/societies/${societyId}/facilities/${facilityId}/rules`,
        availability: (societyId: string, facilityId: string) => `/societies/${societyId}/facilities/${facilityId}/availability`,
        blockedSlots: (societyId: string, facilityId: string) => `/societies/${societyId}/facilities/${facilityId}/blocked-slots`,
        calendar: (societyId: string) => `/societies/${societyId}/facilities/calendar`,
        slots: (facilityId: string) => `/facilities/${facilityId}/slots`,
        bookings: '/facility-bookings',
        bookingDetail: (bookingId: string) => `/facility-bookings/${bookingId}`,
        updateBooking: (bookingId: string) => `/facility-bookings/${bookingId}`,
        submitBooking: (bookingId: string) => `/facility-bookings/${bookingId}/submit`,
        cancelBooking: (bookingId: string) => `/facility-bookings/${bookingId}/cancel`,
        rescheduleBooking: (bookingId: string) => `/facility-bookings/${bookingId}/reschedule`,
        bookingTimeline: (bookingId: string) => `/facility-bookings/${bookingId}/timeline`,
        checkInPass: (bookingId: string) => `/facility-bookings/${bookingId}/check-in-pass`,
        checkIn: (bookingId: string) => `/facility-bookings/${bookingId}/check-in`,
        guestRoomBookings: '/guest-room-bookings',
        guestRoomBookingDetail: (bookingId: string) => `/guest-room-bookings/${bookingId}`,
        cancelGuestRoomBooking: (bookingId: string) => `/guest-room-bookings/${bookingId}/cancel`,
        rescheduleGuestRoomBooking: (bookingId: string) => `/guest-room-bookings/${bookingId}/reschedule`,
        depositRefund: (bookingId: string) => `/facility-bookings/${bookingId}/deposit-refund`,
        depositPaymentOrder: (bookingId: string) => `/facility-bookings/${bookingId}/deposit-payment-order`,
        refundStatus: (bookingId: string) => `/facility-bookings/${bookingId}/refund-status`,
        usageHistory: '/facility-usage-history',
        usageDetail: (usageId: string) => `/facility-usage-history/${usageId}`,
        feedback: (bookingId: string) => `/facility-bookings/${bookingId}/feedback`,
        adminPendingApprovals: '/facility-admin/bookings/pending-approval',
        adminApproveBooking: (bookingId: string) => `/facility-admin/bookings/${bookingId}/approve`,
        adminRejectBooking: (bookingId: string) => `/facility-admin/bookings/${bookingId}/reject`,
        adminBlockSlots: (facilityId: string) => `/facility-admin/facilities/${facilityId}/block-slots`,
        adminDamageInspection: (facilityId: string) => `/facility-admin/facilities/${facilityId}/damage-inspection`,
    },
    facilityOps: {
        dashboard: '/facility-operations/dashboard',
        summary: '/facility-operations/summary',
        complianceExpiry: '/facility-operations/compliance-expiry',
        vendors: '/vendors',
        vendorDetail: (vendorId: string) => `/vendors/${vendorId}`,
        vendorDocuments: (vendorId: string) => `/vendors/${vendorId}/documents`,
        vendorWorkOrders: (vendorId: string) => `/vendors/${vendorId}/work-orders`,
        vendorScorecard: (vendorId: string) => `/vendors/${vendorId}/scorecard`,
        vendorMarkInactive: (vendorId: string) => `/vendors/${vendorId}/mark-inactive`,
        vendorBlacklist: (vendorId: string) => `/vendors/${vendorId}/blacklist`,
        amcContracts: '/amc-contracts',
        amcContractDetail: (contractId: string) => `/amc-contracts/${contractId}`,
        amcServiceHistory: (contractId: string) => `/amc-contracts/${contractId}/service-history`,
        amcRenewalReminders: (contractId: string) => `/amc-contracts/${contractId}/renewal-reminders`,
        amcMarkRenewalStarted: (contractId: string) => `/amc-contracts/${contractId}/mark-renewal-started`,
        amcMarkRenewed: (contractId: string) => `/amc-contracts/${contractId}/mark-renewed`,
        assets: '/assets',
        assetDetail: (assetId: string) => `/assets/${assetId}`,
        assetDocuments: (assetId: string) => `/assets/${assetId}/documents`,
        assetServiceHistory: (assetId: string) => `/assets/${assetId}/service-history`,
        assetWorkOrders: (assetId: string) => `/assets/${assetId}/work-orders`,
        assetReportBreakdown: (assetId: string) => `/assets/${assetId}/report-breakdown`,
        assetMarkRetired: (assetId: string) => `/assets/${assetId}/mark-retired`,
        preventiveSchedules: '/preventive-maintenance/schedules',
        preventiveScheduleDetail: (scheduleId: string) => `/preventive-maintenance/schedules/${scheduleId}`,
        preventiveComplete: (scheduleId: string) => `/preventive-maintenance/schedules/${scheduleId}/complete`,
        preventiveSkip: (scheduleId: string) => `/preventive-maintenance/schedules/${scheduleId}/skip`,
        preventiveReschedule: (scheduleId: string) => `/preventive-maintenance/schedules/${scheduleId}/reschedule`,
        workOrders: '/work-orders',
        workOrderDetail: (workOrderId: string) => `/work-orders/${workOrderId}`,
        workOrderAssignVendor: (workOrderId: string) => `/work-orders/${workOrderId}/assign-vendor`,
        workOrderStart: (workOrderId: string) => `/work-orders/${workOrderId}/start`,
        workOrderComplete: (workOrderId: string) => `/work-orders/${workOrderId}/complete`,
        workOrderVerify: (workOrderId: string) => `/work-orders/${workOrderId}/verify`,
        workOrderClose: (workOrderId: string) => `/work-orders/${workOrderId}/close`,
        workOrderReopen: (workOrderId: string) => `/work-orders/${workOrderId}/reopen`,
        workOrderNotes: (workOrderId: string) => `/work-orders/${workOrderId}/notes`,
        serviceHistory: '/service-history',
        serviceHistoryDetail: (serviceHistoryId: string) => `/service-history/${serviceHistoryId}`,
        inventoryItems: '/inventory/items',
        inventoryItemDetail: (itemId: string) => `/inventory/items/${itemId}`,
        inventoryTransactions: '/inventory/transactions',
        inventoryIssue: (itemId: string) => `/inventory/items/${itemId}/issue`,
        inventoryReturn: (itemId: string) => `/inventory/items/${itemId}/return`,
        inventoryAdjust: (itemId: string) => `/inventory/items/${itemId}/adjust`,
        purchaseRequests: '/purchase-requests',
        purchaseRequestDetail: (purchaseRequestId: string) => `/purchase-requests/${purchaseRequestId}`,
        purchaseSubmit: (purchaseRequestId: string) => `/purchase-requests/${purchaseRequestId}/submit`,
        purchaseCancel: (purchaseRequestId: string) => `/purchase-requests/${purchaseRequestId}/cancel`,
        facilityIncidents: '/facility-incidents',
        facilityIncidentDetail: (incidentId: string) => `/facility-incidents/${incidentId}`,
        facilityIncidentCreateWorkOrder: (incidentId: string) => `/facility-incidents/${incidentId}/create-work-order`,
        facilityIncidentResolve: (incidentId: string) => `/facility-incidents/${incidentId}/resolve`,
    },
    governance: {
        dashboard: '/governance/dashboard',
        summary: '/governance/summary',
        auditLogs: '/governance/audit-logs',
        meetings: '/governance/meetings',
        createMeeting: '/governance/meetings',
        meetingDetail: (meetingId: string) => `/governance/meetings/${meetingId}`,
        updateMeeting: (meetingId: string) => `/governance/meetings/${meetingId}`,
        publishMeetingNotice: (meetingId: string) => `/governance/meetings/${meetingId}/publish-notice`,
        acknowledgeMeetingNotice: (meetingId: string) => `/governance/meetings/${meetingId}/acknowledge`,
        meetingRsvp: (meetingId: string) => `/governance/meetings/${meetingId}/rsvp`,
        meetingAgenda: (meetingId: string) => `/governance/meetings/${meetingId}/agenda`,
        meetingDocuments: (meetingId: string) => `/governance/meetings/${meetingId}/documents`,
        submitMeetingQuestion: (meetingId: string) => `/governance/meetings/${meetingId}/questions`,
        submitProxyAuthorization: (meetingId: string) => `/governance/meetings/${meetingId}/proxy-authorizations`,
        meetingAttendance: (meetingId: string) => `/governance/meetings/${meetingId}/attendance`,
        markAttendance: '/governance/attendance/mark',
        minutes: '/governance/minutes',
        minutesDetail: (minutesId: string) => `/governance/minutes/${minutesId}`,
        submitMinutesReview: (minutesId: string) => `/governance/minutes/${minutesId}/submit-review`,
        requestMinutesChanges: (minutesId: string) => `/governance/minutes/${minutesId}/request-changes`,
        approveMinutes: (minutesId: string) => `/governance/minutes/${minutesId}/approve`,
        publishMinutes: (minutesId: string) => `/governance/minutes/${minutesId}/publish`,
        minutesVersions: (minutesId: string) => `/governance/minutes/${minutesId}/versions`,
        resolutions: '/governance/resolutions',
        createResolution: '/governance/resolutions',
        resolutionDetail: (resolutionId: string) => `/governance/resolutions/${resolutionId}`,
        updateResolution: (resolutionId: string) => `/governance/resolutions/${resolutionId}`,
        openResolutionVoting: (resolutionId: string) => `/governance/resolutions/${resolutionId}/open-voting`,
        closeResolutionVoting: (resolutionId: string) => `/governance/resolutions/${resolutionId}/close-voting`,
        submitResolutionImplementationUpdate: (resolutionId: string) => `/governance/resolutions/${resolutionId}/implementation-updates`,
        resolutionTimeline: (resolutionId: string) => `/governance/resolutions/${resolutionId}/timeline`,
        resolutionResult: (resolutionId: string) => `/governance/resolutions/${resolutionId}/result`,
        polls: '/governance/polls',
        createPoll: '/governance/polls',
        pollDetail: (pollId: string) => `/governance/polls/${pollId}`,
        updatePoll: (pollId: string) => `/governance/polls/${pollId}`,
        publishPoll: (pollId: string) => `/governance/polls/${pollId}/publish`,
        submitPollVote: (pollId: string) => `/governance/polls/${pollId}/vote`,
        pollResult: (pollId: string) => `/governance/polls/${pollId}/result`,
        closePoll: (pollId: string) => `/governance/polls/${pollId}/close`,
        votingEligibility: '/governance/voting-eligibility',
        pollEligibility: (pollId: string) => `/governance/polls/${pollId}/eligibility`,
        proxyAuthorizations: '/governance/proxy-authorizations',
        proxyAuthorizationDetail: (proxyId: string) => `/governance/proxy-authorizations/${proxyId}`,
        cancelProxyAuthorization: (proxyId: string) => `/governance/proxy-authorizations/${proxyId}/cancel`,
        electionReadiness: '/governance/elections/readiness',
        elections: '/governance/elections',
        createElection: '/governance/elections',
        electionDetail: (electionId: string) => `/governance/elections/${electionId}`,
        submitNomination: (electionId: string) => `/governance/elections/${electionId}/nominations`,
        getNominations: (electionId: string) => `/governance/elections/${electionId}/nominations`,
        getCandidates: (electionId: string) => `/governance/elections/${electionId}/candidates`,
        getCandidateProfile: (electionId: string, candidateId: string) => `/governance/elections/${electionId}/candidates/${candidateId}`,
        publishElectionResults: (electionId: string) => `/governance/elections/${electionId}/publish-results`,
        bylaws: '/governance/bylaws',
        bylawDetail: (documentId: string) => `/governance/bylaws/${documentId}`,
        acknowledgeBylaw: (documentId: string) => `/governance/bylaws/${documentId}/acknowledge`,
        memberRegister: '/governance/member-register',
        memberRegisterDetail: (memberId: string) => `/governance/member-register/${memberId}`,
        complianceCalendar: '/governance/compliance-calendar',
        complianceCalendarDetail: (complianceItemId: string) => `/governance/compliance-calendar/${complianceItemId}`,
        markComplianceComplete: (complianceItemId: string) => `/governance/compliance-calendar/${complianceItemId}/mark-complete`,
        legalNotices: '/governance/legal-notices',
        createLegalNotice: '/governance/legal-notices',
        legalNoticeDetail: (legalNoticeId: string) => `/governance/legal-notices/${legalNoticeId}`,
        updateLegalNotice: (legalNoticeId: string) => `/governance/legal-notices/${legalNoticeId}`,
    },
    emergencies: {
        create: '/emergencies',
        detail: (emergencyId: string) => `/emergencies/${emergencyId}`,
        acknowledge: (emergencyId: string) => `/emergencies/${emergencyId}/acknowledge`,
        active: '/emergencies/active',
    },
    features: {
        list: '/features',
        societyFeatures: (societyId: string) => `/societies/${societyId}/features`,
        updateSocietyFeatures: (societyId: string) => `/societies/${societyId}/features`,
    },
    adminOffice: {
        dashboard: '/admin/dashboard',
        societySummary: '/admin/society-summary',
        auditLogs: '/admin/audit-logs',
        units: '/admin/units',
        unitDetail: (unitId: string) => `/admin/units/${unitId}`,
        updateUnit: (unitId: string) => `/admin/units/${unitId}`,
        unitLedgerSummary: (unitId: string) => `/admin/units/${unitId}/ledger-summary`,
        unitOccupancySummary: (unitId: string) => `/admin/units/${unitId}/occupancy-summary`,
        unitAuditLogs: (unitId: string) => `/admin/units/${unitId}/audit-logs`,
        residents: '/admin/residents',
        residentDetail: (residentId: string) => `/admin/residents/${residentId}`,
        updateResident: (residentId: string) => `/admin/residents/${residentId}`,
        requestResidentDocuments: (residentId: string) => `/admin/residents/${residentId}/request-documents`,
        disableResidentAccess: (residentId: string) => `/admin/residents/${residentId}/disable-access`,
        enableResidentAccess: (residentId: string) => `/admin/residents/${residentId}/enable-access`,
        approvals: '/admin/approvals',
        approvalDetail: (approvalId: string) => `/admin/approvals/${approvalId}`,
        approveRequest: (approvalId: string) => `/admin/approvals/${approvalId}/approve`,
        rejectRequest: (approvalId: string) => `/admin/approvals/${approvalId}/reject`,
        requestMoreInfo: (approvalId: string) => `/admin/approvals/${approvalId}/request-more-info`,
        adminNotices: '/admin/notices',
        createAdminNotice: '/admin/notices',
        adminNoticeDetail: (noticeId: string) => `/admin/notices/${noticeId}`,
        updateAdminNotice: (noticeId: string) => `/admin/notices/${noticeId}`,
        publishAdminNotice: (noticeId: string) => `/admin/notices/${noticeId}/publish`,
        archiveAdminNotice: (noticeId: string) => `/admin/notices/${noticeId}/archive`,
        noticeAcknowledgements: (noticeId: string) => `/admin/notices/${noticeId}/acknowledgements`,
        adminComplaints: '/admin/complaints',
        adminComplaintDetail: (complaintId: string) => `/admin/complaints/${complaintId}`,
        assignComplaint: (complaintId: string) => `/admin/complaints/${complaintId}/assign`,
        escalateComplaint: (complaintId: string) => `/admin/complaints/${complaintId}/escalate`,
        resolveComplaint: (complaintId: string) => `/admin/complaints/${complaintId}/resolve`,
        reopenComplaint: (complaintId: string) => `/admin/complaints/${complaintId}/reopen`,
        settings: '/admin/settings',
        rolesPermissions: '/admin/roles-permissions',
        featureConfiguration: '/admin/feature-configuration',
        updateFeatureConfiguration: '/admin/feature-configuration',
        featureConfigurationAuditLogs: '/admin/feature-configuration/audit-logs',
    },
    accounting: {
        dashboard: '/accounting/dashboard',
        collectionSummary: '/accounting/collection-summary',
        recentCollections: '/accounting/recent-collections',
        outstandingSummary: '/accounting/outstanding-summary',
        chargeHeads: '/accounting/charge-heads',
        createChargeHead: '/accounting/charge-heads',
        chargeHeadDetail: (chargeHeadId: string) => `/accounting/charge-heads/${chargeHeadId}`,
        updateChargeHead: (chargeHeadId: string) => `/accounting/charge-heads/${chargeHeadId}`,
        deactivateChargeHead: (chargeHeadId: string) => `/accounting/charge-heads/${chargeHeadId}/deactivate`,
        billingCycles: '/accounting/billing-cycles',
        createBillingCycle: '/accounting/billing-cycles',
        billingCycleDetail: (billingCycleId: string) => `/accounting/billing-cycles/${billingCycleId}`,
        calculateBills: (billingCycleId: string) => `/accounting/billing-cycles/${billingCycleId}/calculate`,
        draftBills: (billingCycleId: string) => `/accounting/billing-cycles/${billingCycleId}/draft-bills`,
        publishBills: (billingCycleId: string) => `/accounting/billing-cycles/${billingCycleId}/publish`,
        closeBillingCycle: (billingCycleId: string) => `/accounting/billing-cycles/${billingCycleId}/close`,
        adminBills: '/accounting/bills',
        adminBillDetail: (billId: string) => `/accounting/bills/${billId}`,
        unitBills: (unitId: string) => `/accounting/units/${unitId}/bills`,
        payments: '/accounting/payments',
        manualPaymentEntry: '/accounting/payments/manual-entry',
        paymentDetail: (paymentId: string) => `/accounting/payments/${paymentId}`,
        reversePayment: (paymentId: string) => `/accounting/payments/${paymentId}/reverse`,
        receipts: '/accounting/receipts',
        receiptDetail: (receiptId: string) => `/accounting/receipts/${receiptId}`,
        flatLedger: (unitId: string) => `/accounting/units/${unitId}/ledger`,
        ledgerEntries: '/accounting/ledger-entries',
        createLedgerAdjustment: '/accounting/ledger-adjustments',
        createLedgerReversal: '/accounting/ledger-reversals',
        defaulters: '/accounting/defaulters',
        sendDefaulterReminder: (unitId: string) => `/accounting/defaulters/${unitId}/send-reminder`,
        generateDefaulterNotice: (unitId: string) => `/accounting/defaulters/${unitId}/generate-notice`,
        bankTransactions: '/accounting/reconciliation/bank-transactions',
        matchBankTransaction: (transactionId: string) => `/accounting/reconciliation/${transactionId}/match`,
        markTransactionReconciled: (transactionId: string) => `/accounting/reconciliation/${transactionId}/mark-reconciled`,
        rejectBankTransaction: (transactionId: string) => `/accounting/reconciliation/${transactionId}/reject`,
        reports: '/accounting/reports',
        generateReport: (reportType: string) => `/accounting/reports/${reportType}/generate`,
        createExport: '/accounting/exports',
        exports: '/accounting/exports',
        exportDetail: (exportId: string) => `/accounting/exports/${exportId}`,
    },
    staffAttendance: {
        staff: '/staff',
        createStaff: '/staff',
        staffDetail: (staffId: string) => `/staff/${staffId}`,
        updateStaff: (staffId: string) => `/staff/${staffId}`,
        markStaffInactive: (staffId: string) => `/staff/${staffId}/mark-inactive`,
        staffAttendanceSummary: (staffId: string) => `/staff/${staffId}/attendance-summary`,
        staffDocuments: (staffId: string) => `/staff/${staffId}/documents`,
        staffIdCard: (staffId: string) => `/staff/${staffId}/id-card`,
        domesticHelp: '/domestic-help',
        createDomesticHelp: '/domestic-help',
        domesticHelpDetail: (domesticHelpId: string) => `/domestic-help/${domesticHelpId}`,
        updateDomesticHelp: (domesticHelpId: string) => `/domestic-help/${domesticHelpId}`,
        verifyDomesticHelp: (domesticHelpId: string) => `/domestic-help/${domesticHelpId}/verify`,
        rejectDomesticHelpVerification: (domesticHelpId: string) => `/domestic-help/${domesticHelpId}/reject-verification`,
        blockDomesticHelpAccess: (domesticHelpId: string) => `/domestic-help/${domesticHelpId}/block-access`,
        linkDomesticHelpToUnit: (domesticHelpId: string) => `/domestic-help/${domesticHelpId}/link-unit`,
        unitDomesticHelp: (unitId: string) => `/units/${unitId}/domestic-help`,
        domesticHelpVerificationChecklist: (domesticHelpId: string) => `/domestic-help/${domesticHelpId}/verification-checklist`,
        shifts: '/attendance/shifts',
        createShift: '/attendance/shifts',
        shiftDetail: (shiftId: string) => `/attendance/shifts/${shiftId}`,
        updateShift: (shiftId: string) => `/attendance/shifts/${shiftId}`,
        assignStaffToShift: (shiftId: string) => `/attendance/shifts/${shiftId}/assign-staff`,
        shiftAssignments: '/attendance/shift-assignments',
        createShiftAssignment: '/attendance/shift-assignments',
        updateShiftAssignment: (assignmentId: string) => `/attendance/shift-assignments/${assignmentId}`,
        attendanceDashboard: '/attendance/dashboard',
        dailyAttendanceSummary: '/attendance/daily-summary',
        attendancePunches: '/attendance/punches',
        createManualPunch: '/attendance/punches/manual',
        punchDetail: (punchId: string) => `/attendance/punches/${punchId}`,
        staffAttendanceDetail: (staffId: string) => `/attendance/staff/${staffId}`,
        staffMonthlyAttendance: (staffId: string) => `/attendance/staff/${staffId}/monthly`,
        correctionRequests: '/attendance/correction-requests',
        createCorrectionRequest: '/attendance/correction-requests',
        correctionRequestDetail: (correctionRequestId: string) => `/attendance/correction-requests/${correctionRequestId}`,
        approveCorrectionRequest: (correctionRequestId: string) => `/attendance/correction-requests/${correctionRequestId}/approve`,
        rejectCorrectionRequest: (correctionRequestId: string) => `/attendance/correction-requests/${correctionRequestId}/reject`,
        requestMoreInfoCorrection: (correctionRequestId: string) => `/attendance/correction-requests/${correctionRequestId}/request-more-info`,
        monthlyAttendanceReport: '/attendance/reports/monthly',
        vendorWiseAttendanceReport: '/attendance/reports/vendor-wise',
        locationWiseAttendanceReport: '/attendance/reports/location-wise',
        exportAttendanceReport: '/attendance/reports/export',
        duplicatePunches: '/attendance/review/duplicates',
        resolveDuplicatePunch: (duplicateId: string) => `/attendance/review/duplicates/${duplicateId}/resolve`,
        missingCheckouts: '/attendance/review/missing-checkout',
        createMissingCheckoutCorrection: (missingCheckoutId: string) => `/attendance/review/missing-checkout/${missingCheckoutId}/create-correction`,
        attendanceHome: '/attendance/home',
        attendanceSettings: '/attendance/settings',
    },
    biometric: {
        devices: '/biometric/devices',
        createDevice: '/biometric/devices',
        deviceDetail: (deviceId: string) => `/biometric/devices/${deviceId}`,
        updateDevice: (deviceId: string) => `/biometric/devices/${deviceId}`,
        markDeviceInactive: (deviceId: string) => `/biometric/devices/${deviceId}/mark-inactive`,
        deviceMappings: (deviceId: string) => `/biometric/devices/${deviceId}/mappings`,
        createMapping: (deviceId: string) => `/biometric/devices/${deviceId}/mappings`,
        updateMapping: (deviceId: string, mappingId: string) => `/biometric/devices/${deviceId}/mappings/${mappingId}`,
        syncJobs: '/biometric/sync-jobs',
        runSyncPlaceholder: '/biometric/sync-jobs/run-placeholder',
        syncJobDetail: (syncJobId: string) => `/biometric/sync-jobs/${syncJobId}`,
        syncJobErrors: (syncJobId: string) => `/biometric/sync-jobs/${syncJobId}/errors`,
        resolveSyncError: (syncErrorId: string) => `/biometric/sync-errors/${syncErrorId}/resolve`,
        ignoreSyncError: (syncErrorId: string) => `/biometric/sync-errors/${syncErrorId}/ignore`,
    },
    emergency: {
        dashboard: '/emergency/dashboard',
        myHistory: '/emergency/my-history',
        activeIncidents: '/emergency/active-incidents',
        auditLogs: '/emergency/audit-logs',
        incidents: '/emergency/incidents',
        incidentDetail: (incidentId: string) => `/emergency/incidents/${incidentId}`,
        updateIncident: (incidentId: string) => `/emergency/incidents/${incidentId}`,
        acknowledgeIncident: (incidentId: string) => `/emergency/incidents/${incidentId}/acknowledge`,
        markReached: (incidentId: string) => `/emergency/incidents/${incidentId}/mark-reached`,
        escalate: (incidentId: string) => `/emergency/incidents/${incidentId}/escalate`,
        markSafe: (incidentId: string) => `/emergency/incidents/${incidentId}/mark-safe`,
        close: (incidentId: string) => `/emergency/incidents/${incidentId}/close`,
        timeline: (incidentId: string) => `/emergency/incidents/${incidentId}/timeline`,
        addTimelineEvent: (incidentId: string) => `/emergency/incidents/${incidentId}/timeline`,
        sos: '/emergency/sos',
        cancelSosFalseAlarm: (incidentId: string) => `/emergency/sos/${incidentId}/cancel-false-alarm`,
        contacts: '/emergency/contacts',
        contactDetail: (contactId: string) => `/emergency/contacts/${contactId}`,
        updateContact: (contactId: string) => `/emergency/contacts/${contactId}`,
        deleteContact: (contactId: string) => `/emergency/contacts/${contactId}`,
        familyConnect: '/emergency/family-connect',
        updateFamilyConnect: '/emergency/family-connect',
        seniorCareProfile: '/safety/senior-care/profile',
        updateSeniorCareProfile: '/safety/senior-care/profile',
        seniorCheckIn: '/safety/senior-care/check-in',
        seniorCheckIns: '/safety/senior-care/check-ins',
        seniorInactivityAlerts: '/safety/senior-care/inactivity-alerts',
        acknowledgeInactivityAlert: (alertId: string) => `/safety/senior-care/inactivity-alerts/${alertId}/acknowledge`,
        escalateInactivityAlert: (alertId: string) => `/safety/senior-care/inactivity-alerts/${alertId}/escalate`,
        volunteers: '/emergency/volunteers',
        volunteerDetail: (volunteerId: string) => `/emergency/volunteers/${volunteerId}`,
        updateVolunteer: (volunteerId: string) => `/emergency/volunteers/${volunteerId}`,
        verifyVolunteerPlaceholder: (volunteerId: string) => `/emergency/volunteers/${volunteerId}/verify-placeholder`,
        volunteerAlerts: '/emergency/volunteer-alerts',
        volunteerAlertDetail: (alertId: string) => `/emergency/volunteer-alerts/${alertId}`,
        acceptVolunteerAlert: (alertId: string) => `/emergency/volunteer-alerts/${alertId}/accept`,
        declineVolunteerAlert: (alertId: string) => `/emergency/volunteer-alerts/${alertId}/decline`,
        volunteerReached: (alertId: string) => `/emergency/volunteer-alerts/${alertId}/mark-reached`,
        guardConsole: '/guard/emergency-console',
        facilityConsole: '/facility/emergency-console',
        assignResponder: (incidentId: string) => `/emergency/incidents/${incidentId}/assign-responder`,
        responderAcknowledge: (responderId: string) => `/emergency/responders/${responderId}/acknowledge`,
        responderUpdateStatus: (responderId: string) => `/emergency/responders/${responderId}/update-status`,
        broadcasts: '/emergency/broadcasts',
        broadcastDetail: (broadcastId: string) => `/emergency/broadcasts/${broadcastId}`,
        cancelBroadcast: (broadcastId: string) => `/emergency/broadcasts/${broadcastId}/cancel`,
        safetyInstructions: '/safety/instructions',
        safetyInstructionDetail: (instructionId: string) => `/safety/instructions/${instructionId}`,
        safetyDrills: '/safety/drills',
        safetyDrillDetail: (drillId: string) => `/safety/drills/${drillId}`,
        updateSafetyDrill: (drillId: string) => `/safety/drills/${drillId}`,
        postIncidentReviews: '/emergency/post-incident-reviews',
        postIncidentReviewDetail: (reviewId: string) => `/emergency/post-incident-reviews/${reviewId}`,
        updatePostIncidentReview: (reviewId: string) => `/emergency/post-incident-reviews/${reviewId}`,
        settings: '/emergency/settings',
        updateSettings: '/emergency/settings',
    },
    interFlat: {
        dashboard: '/inter-flat/dashboard',
        myIssues: '/inter-flat/my-issues',
        auditLogs: '/inter-flat/audit-logs',
        issues: '/inter-flat/issues',
        createIssue: '/inter-flat/issues',
        issueDetail: (issueId: string) => `/inter-flat/issues/${issueId}`,
        updateIssue: (issueId: string) => `/inter-flat/issues/${issueId}`,
        submitResponse: (issueId: string) => `/inter-flat/issues/${issueId}/submit-response`,
        addEvidence: (issueId: string) => `/inter-flat/issues/${issueId}/add-evidence-placeholder`,
        notifyInvolved: (issueId: string) => `/inter-flat/issues/${issueId}/notify-involved-flat`,
        requestInspection: (issueId: string) => `/inter-flat/issues/${issueId}/request-inspection`,
        escalate: (issueId: string) => `/inter-flat/issues/${issueId}/escalate`,
        close: (issueId: string) => `/inter-flat/issues/${issueId}/close`,
        timeline: (issueId: string) => `/inter-flat/issues/${issueId}/timeline`,
        addTimelineEvent: (issueId: string) => `/inter-flat/issues/${issueId}/timeline`,
        inspections: '/inter-flat/inspections',
        inspectionDetail: (inspectionId: string) => `/inter-flat/inspections/${inspectionId}`,
        startInspection: (inspectionId: string) => `/inter-flat/inspections/${inspectionId}/start`,
        completeInspection: (inspectionId: string) => `/inter-flat/inspections/${inspectionId}/complete`,
        requestRevisit: (inspectionId: string) => `/inter-flat/inspections/${inspectionId}/request-revisit`,
        mediations: '/inter-flat/mediations',
        mediationDetail: (mediationId: string) => `/inter-flat/mediations/${mediationId}`,
        assignMediator: (mediationId: string) => `/inter-flat/mediations/${mediationId}/assign-mediator`,
        addMediatorNote: (mediationId: string) => `/inter-flat/mediations/${mediationId}/notes`,
        proposals: (mediationId: string) => `/inter-flat/mediations/${mediationId}/resolution-proposals`,
        resolutionProposalDetail: (proposalId: string) => `/inter-flat/resolution-proposals/${proposalId}`,
        acceptProposal: (proposalId: string) => `/inter-flat/resolution-proposals/${proposalId}/accept`,
        rejectProposal: (proposalId: string) => `/inter-flat/resolution-proposals/${proposalId}/reject`,
        submitClosureProof: (proposalId: string) => `/inter-flat/resolution-proposals/${proposalId}/closure-proof`,
        disputeHistory: '/inter-flat/dispute-history',
        unitHistory: (unitId: string) => `/units/${unitId}/inter-flat-history`,
        rules: '/rules',
        createRule: '/rules',
        ruleDetail: (ruleId: string) => `/rules/${ruleId}`,
        updateRule: (ruleId: string) => `/rules/${ruleId}`,
        categories: '/rules/categories',
        categoryDetail: (categoryId: string) => `/rules/categories/${categoryId}`,
        ruleVersions: (ruleId: string) => `/rules/${ruleId}/versions`,
        publishVersion: (ruleId: string) => `/rules/${ruleId}/publish-version`,
        myAcknowledgements: '/rules/acknowledgements/my',
        acknowledgeRule: (ruleId: string) => `/rules/${ruleId}/acknowledge`,
        acknowledgementReport: (ruleId: string) => `/rules/${ruleId}/acknowledgement-report`,
        allAcknowledgementReports: '/rules/acknowledgement-reports',
        exportReportPlaceholder: '/rules/acknowledgement-reports/export-placeholder',
        violations: '/rules/violations',
        createViolationPlaceholder: '/rules/violations/placeholder',
        penaltyReadiness: '/rules/penalty-readiness',
        settings: '/inter-flat/settings',
        updateSettings: '/inter-flat/settings',
    },
    compliance: {
        dashboard: '/compliance/dashboard',
        calendar: '/compliance/calendar',
        tasks: '/compliance/tasks',
        createTask: '/compliance/tasks',
        taskDetail: (taskId: string) => `/compliance/tasks/${taskId}`,
        updateTask: (taskId: string) => `/compliance/tasks/${taskId}`,
        startTask: (taskId: string) => `/compliance/tasks/${taskId}/start`,
        completeTask: (taskId: string) => `/compliance/tasks/${taskId}/complete`,
        verifyTask: (taskId: string) => `/compliance/tasks/${taskId}/verify`,
        reopenTask: (taskId: string) => `/compliance/tasks/${taskId}/reopen`,
        auditLogs: '/compliance/audit-logs',
        settings: '/compliance/settings',
        updateSettings: '/compliance/settings',
        wasteDashboard: '/compliance/waste/dashboard',
        wastePickupSchedule: '/compliance/waste/pickup-schedule',
        markWastePickupCompleted: (scheduleId: string) => `/compliance/waste/pickup-schedule/${scheduleId}/mark-completed`,
        submitWasteSegregationChecklist: '/compliance/waste/segregation-checklists',
        submitMissedGarbagePickup: '/compliance/waste/missed-pickups',
        getMissedGarbagePickups: '/compliance/waste/missed-pickups',
        createWasteViolationPlaceholder: '/compliance/waste/violations/placeholder',
        wasteReports: '/compliance/waste/reports',
        housekeepingDashboard: '/compliance/housekeeping/dashboard',
        housekeepingSchedules: '/compliance/housekeeping/schedules',
        housekeepingRounds: '/compliance/housekeeping/rounds',
        housekeepingRoundDetail: (roundId: string) => `/compliance/housekeeping/rounds/${roundId}`,
        startHousekeepingRound: (roundId: string) => `/compliance/housekeeping/rounds/${roundId}/start`,
        completeHousekeepingRound: (roundId: string) => `/compliance/housekeeping/rounds/${roundId}/complete`,
        submitFloorCleaningChecklist: '/compliance/housekeeping/checklists',
        submitCommonAreaInspection: '/compliance/housekeeping/common-area-inspections',
        submitSupervisorVerification: '/compliance/housekeeping/supervisor-verifications',
        reportHousekeepingIssue: '/compliance/housekeeping/issues',
        housekeepingReports: '/compliance/housekeeping/reports',
        liftDashboard: '/compliance/lifts/dashboard',
        lifts: '/compliance/lifts',
        liftDetail: (liftId: string) => `/compliance/lifts/${liftId}`,
        updateLift: (liftId: string) => `/compliance/lifts/${liftId}`,
        reportLiftBreakdown: (liftId: string) => `/compliance/lifts/${liftId}/breakdowns`,
        getLiftBreakdowns: (liftId: string) => `/compliance/lifts/${liftId}/breakdowns`,
        addLiftMaintenanceVisit: (liftId: string) => `/compliance/lifts/${liftId}/maintenance-visits`,
        getLiftMaintenanceVisits: (liftId: string) => `/compliance/lifts/${liftId}/maintenance-visits`,
        getLiftCertificates: (liftId: string) => `/compliance/lifts/${liftId}/certificates`,
        startLiftCertificateRenewal: (liftId: string) => `/compliance/lifts/${liftId}/certificates/renewal-placeholder`,
        liftDowntimeReport: '/compliance/lifts/downtime-report',
        liftSafetyDocuments: '/compliance/lifts/safety-documents',
        fireDashboard: '/compliance/fire/dashboard',
        fireEquipment: '/compliance/fire/equipment',
        createFireEquipment: '/compliance/fire/equipment',
        fireEquipmentDetail: (equipmentId: string) => `/compliance/fire/equipment/${equipmentId}`,
        updateFireEquipment: (equipmentId: string) => `/compliance/fire/equipment/${equipmentId}`,
        submitFireEquipmentInspection: (equipmentId: string) => `/compliance/fire/equipment/${equipmentId}/inspection`,
        markFireEquipmentFaulty: (equipmentId: string) => `/compliance/fire/equipment/${equipmentId}/mark-faulty`,
        markFireEquipmentReplaced: (equipmentId: string) => `/compliance/fire/equipment/${equipmentId}/mark-replaced`,
        fireExtinguisherExpiry: '/compliance/fire/extinguisher-expiry',
        fireNoc: '/compliance/fire/noc',
        startFireNocRenewal: '/compliance/fire/noc/start-renewal-placeholder',
        submitHydrantPumpChecklist: '/compliance/fire/hydrant-pump-checklists',
        fireDrills: '/compliance/fire/drills',
        createFireDrill: '/compliance/fire/drills',
        fireDrillDetail: (drillId: string) => `/compliance/fire/drills/${drillId}`,
        updateFireDrill: (drillId: string) => `/compliance/fire/drills/${drillId}`,
        completeFireDrill: (drillId: string) => `/compliance/fire/drills/${drillId}/complete`,
        fireEvacuationPlan: '/compliance/fire/evacuation-plan',
        reports: '/compliance/reports',
        generateReportPlaceholder: (reportType: string) => `/compliance/reports/${reportType}/generate-placeholder`,
        exportReportPlaceholder: '/compliance/reports/export-placeholder',
    },
    community: {
        dashboard: '/community/dashboard',
        listings: '/community/marketplace/listings',
        myListings: '/community/marketplace/listings/me',
        listingDetail: (listingId: string) => `/community/marketplace/listings/${listingId}`,
        createListing: '/community/marketplace/listings',
        updateListing: (listingId: string) => `/community/marketplace/listings/${listingId}`,
        reportListing: (listingId: string) => `/community/marketplace/listings/${listingId}/report`,
        moderationQueue: '/community/marketplace/moderation-queue',
        moderateListing: (listingId: string) => `/community/marketplace/listings/${listingId}/moderate`,
        skills: '/community/skills',
        skillDetail: (skillId: string) => `/community/skills/${skillId}`,
        createSkillProfile: '/community/skills',
        updateSkillProfile: '/community/skills/me',
        services: '/community/skills/services',
        serviceCategories: '/community/services/categories',
        featuredServiceCategory: '/community/services/categories/featured',
        serviceProviders: '/community/services/providers',
        vendorRatings: (providerId: string) => `/community/services/providers/${providerId}/ratings`,
        serviceRequests: '/community/skills/service-requests',
        serviceRequestDetail: (requestId: string) => `/community/skills/service-requests/${requestId}`,
        createServiceRequest: '/community/skills/service-requests',
        contactRequest: '/community/contact-requests',
        borrowableItems: '/community/borrow/items',
        myBorrowableItems: '/community/borrow/items/me',
        borrowableItemDetail: (itemId: string) => `/community/borrow/items/${itemId}`,
        createBorrowableItem: '/community/borrow/items',
        borrowRequests: '/community/borrow/requests',
        borrowRequestDetail: (requestId: string) => `/community/borrow/requests/${requestId}`,
        createBorrowRequest: '/community/borrow/requests',
        decideBorrowRequest: (requestId: string) => `/community/borrow/requests/${requestId}/decide`,
        confirmReturn: (requestId: string) => `/community/borrow/requests/${requestId}/confirm-return`,
        borrowHistory: '/community/borrow/history',
        lostFound: '/community/lost-found',
        lostFoundDetail: (itemId: string) => `/community/lost-found/${itemId}`,
        createLostFound: '/community/lost-found',
        claimLostFound: (itemId: string) => `/community/lost-found/${itemId}/claim`,
        auditLogs: '/community/audit-logs',
        settings: '/community/settings',
        updateSettings: '/community/settings',
    },
    platform: {
        dashboard: '/platform/dashboard',
        healthOverview: '/platform/health-overview',
        auditLogs: '/platform/audit-logs',
        settings: '/platform/settings',
        societies: '/platform/societies',
        societyDetail: (societyId: string) => `/platform/societies/${societyId}`,
        updateSociety: (societyId: string) => `/platform/societies/${societyId}`,
        activateSociety: (societyId: string) => `/platform/societies/${societyId}/activate`,
        suspendSocietyPlaceholder: (societyId: string) => `/platform/societies/${societyId}/suspend-placeholder`,
        societyAdmins: (societyId: string) => `/platform/societies/${societyId}/admins`,
        inviteAdminPlaceholder: (societyId: string) => `/platform/societies/${societyId}/admins/invite-placeholder`,
        disableAdminPlaceholder: (societyId: string, adminUserId: string) => `/platform/societies/${societyId}/admins/${adminUserId}/disable-placeholder`,
        onboardingDrafts: '/platform/onboarding/drafts',
        createOnboardingDraft: '/platform/onboarding/drafts',
        onboardingDraftDetail: (draftId: string) => `/platform/onboarding/drafts/${draftId}`,
        updateOnboardingDraft: (draftId: string) => `/platform/onboarding/drafts/${draftId}`,
        reviewOnboardingDraft: (draftId: string) => `/platform/onboarding/drafts/${draftId}/review`,
        activateOnboardingPlaceholder: (draftId: string) => `/platform/onboarding/drafts/${draftId}/activate-placeholder`,
        hierarchyTemplates: '/platform/hierarchy-templates',
        hierarchyTemplateDetail: (templateId: string) => `/platform/hierarchy-templates/${templateId}`,
        applyHierarchyTemplatePlaceholder: (societyId: string) => `/platform/societies/${societyId}/apply-hierarchy-template-placeholder`,
        featureFlags: '/platform/feature-flags',
        featureFlagDetail: (flagKey: string) => `/platform/feature-flags/${flagKey}`,
        changeFeatureFlag: (flagKey: string) => `/platform/feature-flags/${flagKey}/change`,
        societyModules: (societyId: string) => `/platform/societies/${societyId}/modules`,
        updateSocietyModules: (societyId: string) => `/platform/societies/${societyId}/modules`,
        societyFeatureFlags: (societyId: string) => `/platform/societies/${societyId}/feature-flags`,
        updateSocietyFeatureFlags: (societyId: string) => `/platform/societies/${societyId}/feature-flags`,
        commercialControls: (societyId: string) => `/platform/societies/${societyId}/commercial-controls`,
        updateCommercialControls: (societyId: string) => `/platform/societies/${societyId}/commercial-controls`,
        freeLaunchPlanMapping: (societyId: string) => `/platform/societies/${societyId}/free-launch-plan-mapping`,
        freeLaunchBatches: '/platform/commercial/free-launch-batches',
        supportTickets: '/platform/support/tickets',
        supportTicketDetail: (ticketId: string) => `/platform/support/tickets/${ticketId}`,
        assignSupportTicket: (ticketId: string) => `/platform/support/tickets/${ticketId}/assign`,
        addInternalNote: (ticketId: string) => `/platform/support/tickets/${ticketId}/internal-notes`,
        requestInfo: (ticketId: string) => `/platform/support/tickets/${ticketId}/request-info`,
        escalateSupportTicket: (ticketId: string) => `/platform/support/tickets/${ticketId}/escalate`,
        resolveSupportTicket: (ticketId: string) => `/platform/support/tickets/${ticketId}/resolve`,
        closeSupportTicket: (ticketId: string) => `/platform/support/tickets/${ticketId}/close`,
        userSearch: '/platform/users/search',
        userDetail: (userId: string) => `/platform/users/${userId}`,
        userAuditSummary: (userId: string) => `/platform/users/${userId}/safe-audit-summary`,
        usageAnalytics: '/platform/analytics/usage',
        moduleAdoption: '/platform/analytics/module-adoption',
        societyHealth: '/platform/analytics/society-health',
        supportLoad: '/platform/analytics/support-load',
        operationalAlerts: '/platform/operational-alerts',
        operationalAlertDetail: (alertId: string) => `/platform/operational-alerts/${alertId}`,
        acknowledgeAlert: (alertId: string) => `/platform/operational-alerts/${alertId}/acknowledge`,
        assignAlertOwner: (alertId: string) => `/platform/operational-alerts/${alertId}/assign-owner`,
        closeAlert: (alertId: string) => `/platform/operational-alerts/${alertId}/close`,
        integrationStatus: '/platform/integrations/status',
        notificationChannelStatus: '/platform/notifications/channels/status',
        testNotificationPlaceholder: '/platform/notifications/channels/test-placeholder',
        dataExportRequests: '/platform/data-export-requests',
        createDataExportRequest: '/platform/data-export-requests',
        dataExportRequestDetail: (exportRequestId: string) => `/platform/data-export-requests/${exportRequestId}`,
        impersonationPlaceholderOpen: '/platform/impersonation/placeholder-open',
        impersonationPlaceholderRequest: '/platform/impersonation/placeholder-request',
        releases: '/platform/releases',
        createReleasePlaceholder: '/platform/releases/placeholder',
        rollouts: '/platform/rollouts',
        createRolloutPlaceholder: '/platform/rollouts/placeholder',
    },
    hardware: {
        dashboard: '/hardware/dashboard',
        integrationHealth: '/hardware/integration-health',
        auditLogs: '/hardware/audit-logs',
        settings: '/hardware/settings',
        updateSettings: '/hardware/settings',
        devices: '/hardware/devices',
        createDevice: '/hardware/devices',
        deviceDetail: (deviceId: string) => `/hardware/devices/${deviceId}`,
        updateDevice: (deviceId: string) => `/hardware/devices/${deviceId}`,
        markDeviceInactive: (deviceId: string) => `/hardware/devices/${deviceId}/mark-inactive`,
        testDeviceSyncPlaceholder: (deviceId: string) => `/hardware/devices/${deviceId}/test-sync-placeholder`,
        deviceEvents: (deviceId: string) => `/hardware/devices/${deviceId}/events`,
        deviceSyncJobs: (deviceId: string) => `/hardware/devices/${deviceId}/sync-jobs`,
        deviceErrors: (deviceId: string) => `/hardware/devices/${deviceId}/errors`,
        deviceLocationMappings: '/hardware/device-location-mappings',
        createDeviceLocationMapping: '/hardware/device-location-mappings',
        updateDeviceLocationMapping: (mappingId: string) => `/hardware/device-location-mappings/${mappingId}`,
        gateDashboard: '/hardware/gate/dashboard',
        rfidReadiness: '/hardware/rfid/readiness',
        rfidTagMappings: '/hardware/rfid/tag-mappings',
        createRfidTagMapping: '/hardware/rfid/tag-mappings',
        updateRfidTagMapping: (mappingId: string) => `/hardware/rfid/tag-mappings/${mappingId}`,
        anprReadiness: '/hardware/anpr/readiness',
        anprEvents: '/hardware/anpr/events',
        reviewAnprVehicleMatch: (eventId: string) => `/hardware/anpr/events/${eventId}/review-match`,
        boomBarriers: '/hardware/boom-barriers',
        boomBarrierDetail: (barrierId: string) => `/hardware/boom-barriers/${barrierId}`,
        requestBoomBarrierManualOverridePlaceholder: (barrierId: string) => `/hardware/boom-barriers/${barrierId}/manual-override-placeholder`,
        cctvAccessPlaceholder: '/hardware/cctv/access-placeholder',
        cctvCameras: '/hardware/cctv/cameras',
        cctvCameraDetail: (cameraId: string) => `/hardware/cctv/cameras/${cameraId}`,
        createCctvAccessRequestPlaceholder: '/hardware/cctv/access-requests-placeholder',
        smartMeterDashboard: '/hardware/smart-meters/dashboard',
        smartMeters: '/hardware/smart-meters',
        smartMeterDetail: (meterId: string) => `/hardware/smart-meters/${meterId}`,
        smartMeterReadings: (meterId: string) => `/hardware/smart-meters/${meterId}/readings`,
        importMeterReadingsPlaceholder: '/hardware/smart-meters/readings/import-placeholder',
        smartMeterReadingErrors: '/hardware/smart-meters/readings/errors',
        evChargingDashboard: '/hardware/ev-charging/dashboard',
        evChargers: '/hardware/ev-chargers',
        evChargerDetail: (chargerId: string) => `/hardware/ev-chargers/${chargerId}`,
        evChargingSessions: '/hardware/ev-charging/sessions',
        evChargingSessionDetail: (sessionId: string) => `/hardware/ev-charging/sessions/${sessionId}`,
        biometricAlignment: '/hardware/biometric/alignment',
        biometricDevices: '/hardware/biometric/devices',
        biometricSyncHealth: '/hardware/biometric/sync-health',
        biometricUnmappedEmployeeCodes: '/hardware/biometric/unmapped-employee-codes',
        syncJobs: '/hardware/sync-jobs',
        syncJobDetail: (syncJobId: string) => `/hardware/sync-jobs/${syncJobId}`,
        events: '/hardware/events',
        eventDetail: (eventId: string) => `/hardware/events/${eventId}`,
        errors: '/hardware/errors',
        errorDetail: (errorId: string) => `/hardware/errors/${errorId}`,
        resolveHardwareErrorPlaceholder: (errorId: string) => `/hardware/errors/${errorId}/resolve-placeholder`,
        ignoreHardwareErrorPlaceholder: (errorId: string) => `/hardware/errors/${errorId}/ignore-placeholder`,
        escalateHardwareErrorPlaceholder: (errorId: string) => `/hardware/errors/${errorId}/escalate-placeholder`,
    },
} as const;

