export const motion = {
  duration: {
    instant: 0,
    xs: 80,
    fast: 120,
    fastPlus: 160,
    normal: 200,
    normalPlus: 240,
    slow: 280,
    slowPlus: 320,
    slower: 500,
    slowest: 600,
    modal: 320,
    sheet: 400,
    popover: 200,
    toast: 240,
    enter: 280,
    exit: 200,
    shimmer: 1600,
    ambient: 3000,
  },

  easing: {
    linear: 'linear',
    easeIn: 'ease-in',
    easeOut: 'ease-out',
    easeInOut: 'ease-in-out',
    standard: 'cubic-bezier(0.4, 0.0, 0.2, 1)',
    accelerate: 'cubic-bezier(0.4, 0.0, 1, 1)',
    decelerate: 'cubic-bezier(0.0, 0.0, 0.2, 1)',
    standardSpring: 'cubic-bezier(0.34, 1.56, 0.64, 1)',
    bounce: 'cubic-bezier(0.68, -0.55, 0.265, 1.55)',
    elastic: 'cubic-bezier(0.175, 0.885, 0.32, 1.275)',
    sharp: 'cubic-bezier(0.4, 0.0, 0.6, 1)',
    smooth: 'cubic-bezier(0.25, 0.1, 0.25, 1)',
  },

  spring: {
    gentle: { damping: 24, stiffness: 100, mass: 1 },
    standard: { damping: 20, stiffness: 180, mass: 1 },
    stiff: { damping: 18, stiffness: 280, mass: 1 },
    bouncy: { damping: 14, stiffness: 180, mass: 1 },
    wobbly: { damping: 12, stiffness: 150, mass: 1 },
    press: { damping: 14, stiffness: 450, mass: 1 },
    card: { damping: 16, stiffness: 280, mass: 1 },
    entrance: { damping: 18, stiffness: 200, mass: 1 },
    tabIcon: { damping: 22, stiffness: 360, overshootClamping: true, mass: 1 },
    focus: { damping: 20, stiffness: 260, overshootClamping: true, mass: 1 },
    modal: { damping: 22, stiffness: 220, mass: 1 },
    sheet: { damping: 24, stiffness: 200, mass: 1 },
    popover: { damping: 20, stiffness: 260, mass: 1 },
    toast: { damping: 18, stiffness: 220, mass: 1 },
    listReorder: { damping: 16, stiffness: 200, mass: 1 },
    drag: { damping: 16, stiffness: 200, mass: 1 },
    scale: { damping: 14, stiffness: 450, mass: 1 },
  },

  stagger: {
    tight: 20,
    normal: 40,
    relaxed: 60,
    slow: 100,
    cascade: 80,
  },

  scale: {
    press: 0.965,
    active: 1.015,
    hover: 1.01,
    focus: 0.98,
    disabled: 1,
    enter: 0.95,
    modalEnter: 0.94,
    sheetEnter: 0.96,
    popoverEnter: 0.97,
  },

  opacity: {
    disabled: 0.48,
    hover: 0.8,
    active: 0.64,
    focus: 0.12,
    overlay: 0.4,
    modalOverlay: 0.5,
    skeleton: 0.5,
    shimmer: 0.4,
  },

  translate: {
    slideUp: { x: 0, y: -20 },
    slideDown: { x: 0, y: 20 },
    slideLeft: { x: -20, y: 0 },
    slideRight: { x: 20, y: 0 },
    press: { x: 0, y: 1.5 },
    cardHover: { x: 0, y: -4 },
    modalEnter: { x: 0, y: 30 },
    sheetEnter: { x: 0, y: 100 },
    popoverEnter: { x: 0, y: 10 },
    toastEnter: { x: 0, y: 40 },
    drag: { x: 0, y: 0 },
  },

  blur: {
    none: 0,
    xs: 4,
    sm: 8,
    md: 16,
    lg: 24,
    xl: 32,
    '2xl': 48,
    modal: 30,
    sheet: 20,
  },

  intent: {
    WORLD_TRANSITION: { duration: 400, easing: 'spring', spring: 'standard' },
    FOCUS_ENTER: { duration: 120, easing: 'standard' },
    FOCUS_EXIT: { duration: 200, easing: 'standard' },
    FLOW_STEP_FORWARD: { duration: 200, easing: 'decelerate' },
    FLOW_STEP_BACK: { duration: 200, easing: 'accelerate' },
    SUBTLE_REFRESH: { duration: 160, easing: 'standard' },
    CARD_PRESS: { duration: 0, easing: 'standard', spring: 'press' },
    SHIMMER_PULSE: { duration: 1600, easing: 'linear' },
    MODAL_ENTER: { duration: 320, easing: 'spring', spring: 'modal' },
    MODAL_EXIT: { duration: 160, easing: 'accelerate' },
    SHEET_ENTER: { duration: 400, easing: 'spring', spring: 'sheet' },
    SHEET_EXIT: { duration: 200, easing: 'accelerate' },
    TOAST_ENTER: { duration: 240, easing: 'spring', spring: 'toast' },
    TOAST_EXIT: { duration: 160, easing: 'accelerate' },
    POPOVER_ENTER: { duration: 160, easing: 'spring', spring: 'popover' },
    POPOVER_EXIT: { duration: 160, easing: 'accelerate' },
    DROPDOWN_ENTER: { duration: 140, easing: 'standard' },
    DROPDOWN_EXIT: { duration: 140, easing: 'accelerate' },
    TAB_SWITCH: { duration: 240, easing: 'spring', spring: 'tabIcon' },
    SCREEN_TRANSITION: { duration: 280, easing: 'standard' },
    LIST_REORDER: { duration: 240, easing: 'spring', spring: 'listReorder' },
    DRAG_START: { duration: 120, easing: 'decelerate' },
    DRAG_END: { duration: 240, easing: 'spring', spring: 'bouncy' },
    LIST_ITEM_ENTER: { duration: 240, easing: 'spring', spring: 'entrance' },
    SKELETON_PULSE: { duration: 1600, easing: 'linear' },
  } as const,
} as const;

export type PremiumMotion = typeof motion;

export const getMotionConfig = (intent: keyof typeof motion.intent) => {
  return motion.intent[intent] || { duration: motion.duration.normal, easing: motion.easing.standard };
};