import type { BlueprintFeature } from './blueprintFeature.types';

export const blueprintFeatures: BlueprintFeature[] = [
  {
    id: 'setup-hierarchy',
    title: 'SocietyHierarchy',
    phase: 'MVP',
    moduleName: 'societySetup',
    featureFlag: 'societySetup',
    permissions: ['READ_SOCIETY'],
    roles: ["RESIDENT"],
    routeNames: ['SOCIETY_HIERARCHY'],
    screenNames: ['SocietyHierarchyScreen'],
    hookNames: ['useSocietyHierarchy'],
    repositoryMethods: ['getSocietyHierarchy'],
    mockDataKeys: ['greenValleyHeightsHierarchy'],
    requiredActions: ['Add tower wing floor wing locally in mock state'],
    status: 'IMPLEMENTED',
  },
  {
    id: 'setup-tower-wing-floor',
    title: 'TowerWingFloorSetup',
    phase: 'MVP',
    moduleName: 'societySetup',
    featureFlag: 'societySetup',
    permissions: ['WRITE_SOCIETY'],
    roles: ["RESIDENT"],
    routeNames: ['TOWER_WING_FLOOR_SETUP'],
    screenNames: ['TowerWingFloorSetupScreen'],
    hookNames: ['useTowerWingFloorSetup'],
    repositoryMethods: ['addTower'],
    mockDataKeys: ['towerWingFloorMockData'],
    requiredActions: ['Create tower/wing/floor locally and show success state'],
    status: 'IMPLEMENTED',
  },
  {
    id: 'setup-unit-master',
    title: 'UnitMaster',
    phase: 'MVP',
    moduleName: 'societySetup',
    featureFlag: 'unitMaster',
    permissions: ['READ_SOCIETY'],
    roles: ["RESIDENT"],
    routeNames: ['UNIT_MASTER'],
    screenNames: ['UnitMasterScreen'],
    hookNames: ['useUnitMaster'],
    repositoryMethods: ['listUnits'],
    mockDataKeys: ['unitMasterMockData'],
    requiredActions: ['Search and filter units by tower wing floor'],
    status: 'IMPLEMENTED',
  },
  {
    id: 'setup-unit-detail',
    title: 'UnitDetail',
    phase: 'MVP',
    moduleName: 'societySetup',
    featureFlag: 'unitMaster',
    permissions: ['READ_SOCIETY'],
    roles: ["RESIDENT"],
    routeNames: ['UNIT_DETAIL'],
    screenNames: ['UnitDetailScreen'],
    hookNames: ['useUnitDetail'],
    repositoryMethods: ['getUnitById'],
    mockDataKeys: ['unitDetailMockData'],
    requiredActions: ['Change occupancy status in mock state'],
    status: 'IMPLEMENTED',
  },
  {
    id: 'setup-unit-import',
    title: 'UnitImportPreview',
    phase: 'MVP',
    moduleName: 'societySetup',
    featureFlag: 'unitMaster',
    permissions: ['WRITE_SOCIETY'],
    roles: ["RESIDENT"],
    routeNames: ['UNIT_IMPORT_PREVIEW'],
    screenNames: ['UnitImportPreviewScreen'],
    hookNames: ['useUnitImportPreview'],
    repositoryMethods: ['previewUnitImport'],
    mockDataKeys: ['unitImportPreviewRows'],
    requiredActions: ['Show duplicate rows, validation errors, confirm mock import, rollback'],
    status: 'IMPLEMENTED',
  },
  {
    id: 'res-directory',
    title: 'ResidentDirectory',
    phase: 'MVP',
    moduleName: 'residents',
    featureFlag: 'adminResidentDirectory',
    permissions: ['READ_RESIDENT'],
    roles: ["RESIDENT"],
    routeNames: ['RESIDENT_DIRECTORY'],
    screenNames: ['ResidentDirectoryScreen'],
    hookNames: ['useResidentDirectory'],
    repositoryMethods: ['listResidents'],
    mockDataKeys: ['residentDirectoryMockData'],
    requiredActions: ['Search by name/flat/role and filter by owner/tenant/family'],
    status: 'IMPLEMENTED',
  },
  {
    id: 'res-owner-profile',
    title: 'OwnerProfile',
    phase: 'MVP',
    moduleName: 'residents',
    featureFlag: 'ownerTenantHistory',
    permissions: ['READ_RESIDENT'],
    roles: ["RESIDENT"],
    routeNames: ['OWNER_PROFILE'],
    screenNames: ['OwnerProfileScreen'],
    hookNames: ['useOwnerProfile'],
    repositoryMethods: ['getOwnerProfile'],
    mockDataKeys: ['ownerProfileMockData'],
    requiredActions: ['Display owner KYC, documents, vehicles, family and contact preferences'],
    status: 'IMPLEMENTED',
  },
  {
    id: 'res-tenant-profile',
    title: 'TenantProfile',
    phase: 'MVP',
    moduleName: 'residents',
    featureFlag: 'ownerTenantHistory',
    permissions: ['READ_RESIDENT'],
    roles: ["RESIDENT"],
    routeNames: ['TENANT_PROFILE'],
    screenNames: ['TenantProfileScreen'],
    hookNames: ['useTenantProfile'],
    repositoryMethods: ['getTenantProfile'],
    mockDataKeys: ['tenantProfileMockData'],
    requiredActions: ['Update police verification status and agreement metadata in mock state'],
    status: 'IMPLEMENTED',
  },
  {
    id: 'res-family',
    title: 'FamilyMembers',
    phase: 'MVP',
    moduleName: 'residents',
    featureFlag: 'ownerTenantHistory',
    permissions: ['READ_RESIDENT'],
    roles: ["RESIDENT"],
    routeNames: ['FAMILY_MEMBERS'],
    screenNames: ['FamilyMembersScreen'],
    hookNames: ['useFamilyMembers'],
    repositoryMethods: ['listFamilyMembers'],
    mockDataKeys: ['familyMembersMockData'],
    requiredActions: ['Add family member and change limited access status'],
    status: 'IMPLEMENTED',
  },
  {
    id: 'res-kyc',
    title: 'ResidentKyc',
    phase: 'MVP',
    moduleName: 'residents',
    featureFlag: 'adminPendingApprovals',
    permissions: ['WRITE_RESIDENT'],
    roles: ["RESIDENT"],
    routeNames: ['RESIDENT_KYC'],
    screenNames: ['ResidentKycScreen'],
    hookNames: ['useResidentKyc'],
    repositoryMethods: ['getResidentKyc'],
    mockDataKeys: ['residentKycMockData'],
    requiredActions: ['Mark KYC as pending, verified, rejected with reason'],
    status: 'IMPLEMENTED',
  },
  {
    id: 'res-approval',
    title: 'ResidentApprovalQueue',
    phase: 'MVP',
    moduleName: 'residents',
    featureFlag: 'adminPendingApprovals',
    permissions: ['WRITE_RESIDENT'],
    roles: ["RESIDENT"],
    routeNames: ['RESIDENT_APPROVAL_QUEUE'],
    screenNames: ['ResidentApprovalQueueScreen'],
    hookNames: ['useResidentApprovals'],
    repositoryMethods: ['listPendingResidentApprovals'],
    mockDataKeys: ['residentApprovalQueueMockData'],
    requiredActions: ['Approve/reject resident onboarding request'],
    status: 'IMPLEMENTED',
  },
  {
    id: 'vis-create',
    title: 'CreateVisitor',
    phase: 'MVP',
    moduleName: 'visitors',
    featureFlag: 'visitorManagement',
    permissions: ['CREATE_VISITOR'],
    roles: ["RESIDENT"],
    routeNames: ['CREATE_VISITOR'],
    screenNames: ['CreateVisitorScreen'],
    hookNames: ['useCreateVisitor'],
    repositoryMethods: ['createVisitorPass'],
    mockDataKeys: ['visitorPassMockData'],
    requiredActions: ['Submit visitor form and create visitor pass with OTP/QR'],
    status: 'IMPLEMENTED',
  },
  {
    id: 'vis-qr-otp',
    title: 'VisitorPassQrOtp',
    phase: 'MVP',
    moduleName: 'visitors',
    featureFlag: 'visitorManagement',
    permissions: ['CREATE_VISITOR'],
    roles: ["RESIDENT"],
    routeNames: ['VISITOR_PASS_QR_OTP'],
    screenNames: ['VisitorPassQrOtpScreen'],
    hookNames: ['useVisitorPassQrOtp'],
    repositoryMethods: ['getVisitorPassCode'],
    mockDataKeys: ['visitorQrOtpMockData'],
    requiredActions: ['Show QR placeholder, OTP code, validity time'],
    status: 'IMPLEMENTED',
  },
  {
    id: 'guard-expected',
    title: 'ExpectedVisitors',
    phase: 'MVP',
    moduleName: 'guard',
    featureFlag: 'guardApp',
    permissions: ['GATE_VERIFICATION'],
    roles: ["GUARD"],
    routeNames: ['EXPECTED_VISITORS'],
    screenNames: ['ExpectedVisitorsScreen'],
    hookNames: ['useExpectedVisitors'],
    repositoryMethods: ['listExpectedVisitors'],
    mockDataKeys: ['expectedVisitorsMockData'],
    requiredActions: ['Search expected visitors and open verification screen'],
    status: 'IMPLEMENTED',
  },
  {
    id: 'guard-verify',
    title: 'VerifyVisitor',
    phase: 'MVP',
    moduleName: 'guard',
    featureFlag: 'guardApp',
    permissions: ['GATE_VERIFICATION'],
    roles: ["GUARD"],
    routeNames: ['VERIFY_VISITOR'],
    screenNames: ['VerifyVisitorScreen'],
    hookNames: ['useVerifyVisitor'],
    repositoryMethods: ['verifyVisitorPass'],
    mockDataKeys: ['verifyVisitorMockData'],
    requiredActions: ['Verify OTP/QR placeholder and create gate log'],
    status: 'IMPLEMENTED',
  },
  {
    id: 'guard-manual',
    title: 'ManualGateEntry',
    phase: 'MVP',
    moduleName: 'guard',
    featureFlag: 'guardApp',
    permissions: ['GATE_VERIFICATION'],
    roles: ["GUARD"],
    routeNames: ['MANUAL_GATE_ENTRY'],
    screenNames: ['ManualGateEntryScreen'],
    hookNames: ['useManualGateEntry'],
    repositoryMethods: ['createManualGateEntry'],
    mockDataKeys: ['manualGateEntryMockData'],
    requiredActions: ['Create walk-in visitor gate entry with reason and flat number'],
    status: 'IMPLEMENTED',
  },
  {
    id: 'guard-delivery',
    title: 'DeliveryEntry',
    phase: 'MVP',
    moduleName: 'guard',
    featureFlag: 'guardApp',
    permissions: ['GATE_VERIFICATION'],
    roles: ["GUARD"],
    routeNames: ['DELIVERY_ENTRY'],
    screenNames: ['DeliveryEntryScreen'],
    hookNames: ['useDeliveryEntry'],
    repositoryMethods: ['createDeliveryEntry'],
    mockDataKeys: ['deliveryEntryMockData'],
    requiredActions: ['Add delivery partner entry and mark collected/returned'],
    status: 'IMPLEMENTED',
  },
  {
    id: 'guard-cab',
    title: 'CabEntry',
    phase: 'MVP',
    moduleName: 'guard',
    featureFlag: 'guardApp',
    permissions: ['GATE_VERIFICATION'],
    roles: ["GUARD"],
    routeNames: ['CAB_ENTRY'],
    screenNames: ['CabEntryScreen'],
    hookNames: ['useCabEntry'],
    repositoryMethods: ['createCabEntry'],
    mockDataKeys: ['cabEntryMockData'],
    requiredActions: ['Record cab number, driver name and flat visit'],
    status: 'IMPLEMENTED',
  },
  {
    id: 'guard-vendor',
    title: 'VendorEntry',
    phase: 'MVP',
    moduleName: 'guard',
    featureFlag: 'guardApp',
    permissions: ['GATE_VERIFICATION'],
    roles: ["GUARD"],
    routeNames: ['VENDOR_ENTRY'],
    screenNames: ['VendorEntryScreen'],
    hookNames: ['useVendorEntry'],
    repositoryMethods: ['createVendorGateEntry'],
    mockDataKeys: ['vendorGateEntryMockData'],
    requiredActions: ['Record vendor/company purpose and check-in/check-out'],
    status: 'IMPLEMENTED',
  },
  {
    id: 'guard-material',
    title: 'MaterialEntry',
    phase: 'MVP',
    moduleName: 'guard',
    featureFlag: 'guardApp',
    permissions: ['GATE_VERIFICATION'],
    roles: ["GUARD"],
    routeNames: ['MATERIAL_ENTRY'],
    screenNames: ['MaterialEntryScreen'],
    hookNames: ['useMaterialEntry'],
    repositoryMethods: ['createMaterialGatePass'],
    mockDataKeys: ['materialGatePassMockData'],
    requiredActions: ['Record inward/outward material with approval placeholder'],
    status: 'IMPLEMENTED',
  },
  {
    id: 'guard-logs',
    title: 'GateLogs',
    phase: 'MVP',
    moduleName: 'guard',
    featureFlag: 'guardApp',
    permissions: ['GATE_VERIFICATION'],
    roles: ["GUARD"],
    routeNames: ['GATE_LOGS'],
    screenNames: ['GateLogsScreen'],
    hookNames: ['useGateLogs'],
    repositoryMethods: ['listGateLogs'],
    mockDataKeys: ['gateLogsMockData'],
    requiredActions: ['Filter logs by gate, guard, type and date'],
    status: 'IMPLEMENTED',
  },
  {
    id: 'guard-offline',
    title: 'OfflineQueuePlaceholder',
    phase: 'MVP',
    moduleName: 'guard',
    featureFlag: 'guardApp',
    permissions: ['GATE_VERIFICATION'],
    roles: ["GUARD"],
    routeNames: ['OFFLINE_QUEUE'],
    screenNames: ['OfflineQueuePlaceholderScreen'],
    hookNames: ['useOfflineGateQueue'],
    repositoryMethods: ['listOfflineGateEntries'],
    mockDataKeys: ['offlineGateQueueMockData'],
    requiredActions: ['Add offline entry and sync placeholder'],
    status: 'IMPLEMENTED',
  },
  {
    id: 'guard-watchlist',
    title: 'BlacklistWatchlist',
    phase: 'MVP',
    moduleName: 'guard',
    featureFlag: 'guardApp',
    permissions: ['GATE_VERIFICATION'],
    roles: ["GUARD"],
    routeNames: ['BLACKLIST_WATCHLIST'],
    screenNames: ['BlacklistWatchlistScreen'],
    hookNames: ['useBlacklistWatchlist'],
    repositoryMethods: ['listWatchlistEntries'],
    mockDataKeys: ['blacklistWatchlistMockData'],
    requiredActions: ['Add/remove visitor/vehicle watchlist entry'],
    status: 'IMPLEMENTED',
  },
  {
    id: 'bill-chargeheads',
    title: 'ChargeHeads',
    phase: 'MVP',
    moduleName: 'billing',
    featureFlag: 'chargeHeadManagement',
    permissions: ['BILL_VIEW'],
    roles: ["ADMIN"],
    routeNames: ['CHARGE_HEADS'],
    screenNames: ['ChargeHeadsScreen'],
    hookNames: ['useChargeHeads'],
    repositoryMethods: ['listChargeHeads'],
    mockDataKeys: ['chargeHeadsMockData'],
    requiredActions: ['Add maintenance/parking/penalty charge head'],
    status: 'IMPLEMENTED',
  },
  {
    id: 'bill-generate',
    title: 'GenerateBills',
    phase: 'MVP',
    moduleName: 'billing',
    featureFlag: 'billingCycleManagement',
    permissions: ['BILL_WRITE'],
    roles: ["ADMIN"],
    routeNames: ['GENERATE_BILLS'],
    screenNames: ['GenerateBillsScreen'],
    hookNames: ['useGenerateBills'],
    repositoryMethods: ['generateMonthlyBills'],
    mockDataKeys: ['billingCycleMockData'],
    requiredActions: ['Generate draft bills for selected month'],
    status: 'IMPLEMENTED',
  },
  {
    id: 'bill-draftreview',
    title: 'DraftBillReview',
    phase: 'MVP',
    moduleName: 'billing',
    featureFlag: 'billingCycleManagement',
    permissions: ['BILL_WRITE'],
    roles: ["ADMIN"],
    routeNames: ['DRAFT_BILL_REVIEW'],
    screenNames: ['DraftBillReviewScreen'],
    hookNames: ['useDraftBills'],
    repositoryMethods: ['listDraftBills'],
    mockDataKeys: ['draftBillsMockData'],
    requiredActions: ['Review draft bill and update mock charges'],
    status: 'IMPLEMENTED',
  },
  {
    id: 'bill-publish',
    title: 'PublishBillsConfirmation',
    phase: 'MVP',
    moduleName: 'billing',
    featureFlag: 'billingCycleManagement',
    permissions: ['BILL_WRITE'],
    roles: ["ADMIN"],
    routeNames: ['PUBLISH_BILLS_CONFIRMATION'],
    screenNames: ['PublishBillsConfirmationScreen'],
    hookNames: ['usePublishBills'],
    repositoryMethods: ['publishBillingCycle'],
    mockDataKeys: ['publishedBillsMockData'],
    requiredActions: ['Publish bills and update resident bill list'],
    status: 'IMPLEMENTED',
  },
  {
    id: 'bill-residentlist',
    title: 'ResidentBillList',
    phase: 'MVP',
    moduleName: 'billing',
    featureFlag: 'maintenanceBilling',
    permissions: ['BILL_VIEW'],
    roles: ["ADMIN"],
    routeNames: ['RESIDENT_BILL_LIST'],
    screenNames: ['ResidentBillListScreen'],
    hookNames: ['useResidentBills'],
    repositoryMethods: ['listResidentBills'],
    mockDataKeys: ['residentBillsMockData'],
    requiredActions: ['Filter bills by unpaid, paid, overdue'],
    status: 'IMPLEMENTED',
  },
  {
    id: 'bill-mockpayment',
    title: 'MockPayment',
    phase: 'MVP',
    moduleName: 'billing',
    featureFlag: 'maintenanceBilling',
    permissions: ['BILL_VIEW'],
    roles: ["ADMIN"],
    routeNames: ['MOCK_PAYMENT'],
    screenNames: ['MockPaymentScreen'],
    hookNames: ['useMockPayment'],
    repositoryMethods: ['payBillInMockMode'],
    mockDataKeys: ['mockPaymentMockData'],
    requiredActions: ['Pay selected bill in mock mode and create receipt'],
    status: 'IMPLEMENTED',
  },
  {
    id: 'bill-receipt',
    title: 'ReceiptDetail',
    phase: 'MVP',
    moduleName: 'billing',
    featureFlag: 'maintenanceBilling',
    permissions: ['BILL_VIEW'],
    roles: ["ADMIN"],
    routeNames: ['RECEIPT_DETAIL'],
    screenNames: ['ReceiptDetailScreen'],
    hookNames: ['useReceiptDetail'],
    repositoryMethods: ['getReceiptById'],
    mockDataKeys: ['receiptMockData'],
    requiredActions: ['Show generated receipt and payment reference'],
    status: 'IMPLEMENTED',
  },
  {
    id: 'bill-flatledger',
    title: 'FlatLedger',
    phase: 'MVP',
    moduleName: 'billing',
    featureFlag: 'flatLedger',
    permissions: ['BILL_VIEW'],
    roles: ["ADMIN"],
    routeNames: ['FLAT_LEDGER'],
    screenNames: ['FlatLedgerScreen'],
    hookNames: ['useFlatLedger'],
    repositoryMethods: ['getFlatLedger'],
    mockDataKeys: ['flatLedgerMockData'],
    requiredActions: ['Show debit/credit ledger entries and running balance'],
    status: 'IMPLEMENTED',
  },
  {
    id: 'bill-defaulter',
    title: 'DefaulterReport',
    phase: 'MVP',
    moduleName: 'billing',
    featureFlag: 'defaulterReport',
    permissions: ['BILL_WRITE'],
    roles: ["ADMIN"],
    routeNames: ['DEFAULTER_REPORT'],
    screenNames: ['DefaulterReportScreen'],
    hookNames: ['useDefaulterReport'],
    repositoryMethods: ['listDefaulters'],
    mockDataKeys: ['defaulterReportMockData'],
    requiredActions: ['Filter defaulters by amount, tower, overdue days'],
    status: 'IMPLEMENTED',
  },
  {
    id: 'bill-manualentry',
    title: 'ManualPaymentEntry',
    phase: 'MVP',
    moduleName: 'billing',
    featureFlag: 'manualPaymentEntry',
    permissions: ['BILL_WRITE'],
    roles: ["ADMIN"],
    routeNames: ['MANUAL_PAYMENT_ENTRY'],
    screenNames: ['ManualPaymentEntryScreen'],
    hookNames: ['useManualPaymentEntry'],
    repositoryMethods: ['recordManualPayment'],
    mockDataKeys: ['manualPaymentMockData'],
    requiredActions: ['Record cash/cheque payment and generate receipt'],
    status: 'IMPLEMENTED',
  },
  {
    id: 'bill-correction',
    title: 'ReversalCorrectionPlaceholder',
    phase: 'MVP',
    moduleName: 'billing',
    featureFlag: 'adjustmentEntry',
    permissions: ['BILL_WRITE'],
    roles: ["ADMIN"],
    routeNames: ['REVERSAL_CORRECTION'],
    screenNames: ['ReversalCorrectionPlaceholderScreen'],
    hookNames: ['useBillingCorrection'],
    repositoryMethods: ['createBillingCorrectionRequest'],
    mockDataKeys: ['billingCorrectionMockData'],
    requiredActions: ['Create reversal/correction request with reason'],
    status: 'IMPLEMENTED',
  },
  {
    id: 'comp-create',
    title: 'CreateComplaint',
    phase: 'MVP',
    moduleName: 'complaints',
    featureFlag: 'complaints',
    permissions: ['COMPLAINT_WRITE'],
    roles: ["RESIDENT"],
    routeNames: ['CREATE_COMPLAINT'],
    screenNames: ['CreateComplaintScreen'],
    hookNames: ['useCreateComplaint'],
    repositoryMethods: ['createComplaint'],
    mockDataKeys: ['complaintsMockData'],
    requiredActions: ['Submit complaint with category, priority, description, photo/file'],
    status: 'IMPLEMENTED',
  },
  {
    id: 'comp-sla',
    title: 'ComplaintSlaDashboard',
    phase: 'MVP',
    moduleName: 'complaints',
    featureFlag: 'adminComplaintControl',
    permissions: ['COMPLAINT_WRITE'],
    roles: ["RESIDENT"],
    routeNames: ['COMPLAINT_SLA_DASHBOARD'],
    screenNames: ['ComplaintSlaDashboardScreen'],
    hookNames: ['useComplaintSla'],
    repositoryMethods: ['getComplaintSlaSummary'],
    mockDataKeys: ['complaintSlaMockData'],
    requiredActions: ['Filter SLA by breached, due today, on track'],
    status: 'IMPLEMENTED',
  },
  {
    id: 'comp-assign',
    title: 'ComplaintAssignment',
    phase: 'MVP',
    moduleName: 'complaints',
    featureFlag: 'adminComplaintControl',
    permissions: ['COMPLAINT_WRITE'],
    roles: ["RESIDENT"],
    routeNames: ['COMPLAINT_ASSIGNMENT'],
    screenNames: ['ComplaintAssignmentScreen'],
    hookNames: ['useAssignComplaint'],
    repositoryMethods: ['assignComplaint'],
    mockDataKeys: ['complaintAssignmentMockData'],
    requiredActions: ['Assign complaint to facility manager, vendor or staff'],
    status: 'IMPLEMENTED',
  },
  {
    id: 'comp-statusupdate',
    title: 'ComplaintStatusUpdate',
    phase: 'MVP',
    moduleName: 'complaints',
    featureFlag: 'adminComplaintControl',
    permissions: ['COMPLAINT_WRITE'],
    roles: ["RESIDENT"],
    routeNames: ['COMPLAINT_STATUS_UPDATE'],
    screenNames: ['ComplaintStatusUpdateScreen'],
    hookNames: ['useUpdateComplaintStatus'],
    repositoryMethods: ['updateComplaintStatus'],
    mockDataKeys: ['complaintStatusMockData'],
    requiredActions: ['Change status to in progress, resolved, closed'],
    status: 'IMPLEMENTED',
  },
  {
    id: 'comp-reopen',
    title: 'ComplaintReopen',
    phase: 'MVP',
    moduleName: 'complaints',
    featureFlag: 'complaints',
    permissions: ['COMPLAINT_WRITE'],
    roles: ["RESIDENT"],
    routeNames: ['COMPLAINT_REOPEN'],
    screenNames: ['ComplaintReopenScreen'],
    hookNames: ['useReopenComplaint'],
    repositoryMethods: ['reopenComplaint'],
    mockDataKeys: ['complaintReopenMockData'],
    requiredActions: ['Reopen closed complaint with reason'],
    status: 'IMPLEMENTED',
  },
  {
    id: 'comp-feedback',
    title: 'ComplaintFeedback',
    phase: 'MVP',
    moduleName: 'complaints',
    featureFlag: 'complaints',
    permissions: ['COMPLAINT_WRITE'],
    roles: ["RESIDENT"],
    routeNames: ['COMPLAINT_FEEDBACK'],
    screenNames: ['ComplaintFeedbackScreen'],
    hookNames: ['useComplaintFeedback'],
    repositoryMethods: ['submitComplaintFeedback'],
    mockDataKeys: ['complaintFeedbackMockData'],
    requiredActions: ['Submit rating and feedback after closure'],
    status: 'IMPLEMENTED',
  },
  {
    id: 'comp-private',
    title: 'PrivateComplaintPlaceholder',
    phase: 'MVP',
    moduleName: 'complaints',
    featureFlag: 'complaints',
    permissions: ['COMPLAINT_WRITE'],
    roles: ["RESIDENT"],
    routeNames: ['PRIVATE_COMPLAINT'],
    screenNames: ['PrivateComplaintPlaceholderScreen'],
    hookNames: ['usePrivateComplaint'],
    repositoryMethods: ['createPrivateComplaint'],
    mockDataKeys: ['privateComplaintMockData'],
    requiredActions: ['Submit private complaint with restricted visibility notice'],
    status: 'IMPLEMENTED',
  },
  {
    id: 'notice-create',
    title: 'CreateNotice',
    phase: 'MVP',
    moduleName: 'notices',
    featureFlag: 'adminNoticeControl',
    permissions: ['NOTICE_WRITE'],
    roles: ["RESIDENT"],
    routeNames: ['CREATE_NOTICE'],
    screenNames: ['CreateNoticeScreen'],
    hookNames: ['useCreateNotice'],
    repositoryMethods: ['createNoticeDraft'],
    mockDataKeys: ['noticeDraftMockData'],
    requiredActions: ['Create notice draft with title, body, category and priority'],
    status: 'IMPLEMENTED',
  },
  {
    id: 'notice-audience',
    title: 'NoticeAudienceSelection',
    phase: 'MVP',
    moduleName: 'notices',
    featureFlag: 'adminNoticeControl',
    permissions: ['NOTICE_WRITE'],
    roles: ["RESIDENT"],
    routeNames: ['NOTICE_AUDIENCE_SELECTION'],
    screenNames: ['NoticeAudienceSelectionScreen'],
    hookNames: ['useNoticeAudienceSelection'],
    repositoryMethods: ['updateNoticeAudience'],
    mockDataKeys: ['noticeAudienceMockData'],
    requiredActions: ['Select all residents, tower, owners, tenants, staff or committee'],
    status: 'IMPLEMENTED',
  },
  {
    id: 'notice-publish',
    title: 'PublishNotice',
    phase: 'MVP',
    moduleName: 'notices',
    featureFlag: 'adminNoticeControl',
    permissions: ['NOTICE_WRITE'],
    roles: ["RESIDENT"],
    routeNames: ['PUBLISH_NOTICE'],
    screenNames: ['PublishNoticeScreen'],
    hookNames: ['usePublishNotice'],
    repositoryMethods: ['publishNotice'],
    mockDataKeys: ['publishedNoticeMockData'],
    requiredActions: ['Publish notice and show it in resident notice list'],
    status: 'IMPLEMENTED',
  },
  {
    id: 'notice-readstatus',
    title: 'NoticeReadStatus',
    phase: 'MVP',
    moduleName: 'notices',
    featureFlag: 'notices',
    permissions: ['NOTICE_VIEW'],
    roles: ["RESIDENT"],
    routeNames: ['NOTICE_READ_STATUS'],
    screenNames: ['NoticeReadStatusScreen'],
    hookNames: ['useNoticeReadStatus'],
    repositoryMethods: ['markNoticeRead'],
    mockDataKeys: ['noticeReadStatusMockData'],
    requiredActions: ['Mark notice as read and update read count'],
    status: 'IMPLEMENTED',
  },
  {
    id: 'notice-ackreport',
    title: 'NoticeAcknowledgementReport',
    phase: 'MVP',
    moduleName: 'notices',
    featureFlag: 'adminNoticeControl',
    permissions: ['NOTICE_WRITE'],
    roles: ["RESIDENT"],
    routeNames: ['NOTICE_ACKNOWLEDGEMENT_REPORT'],
    screenNames: ['NoticeAcknowledgementReportScreen'],
    hookNames: ['useNoticeAcknowledgementReport'],
    repositoryMethods: ['getNoticeAcknowledgementReport'],
    mockDataKeys: ['noticeAcknowledgementMockData'],
    requiredActions: ['Filter acknowledged and pending residents'],
    status: 'IMPLEMENTED',
  },
  {
    id: 'doc-upload',
    title: 'DocumentUploadPlaceholder',
    phase: 'MVP',
    moduleName: 'documents',
    featureFlag: 'documentVault',
    permissions: ['DOCUMENT_WRITE'],
    roles: ["RESIDENT"],
    routeNames: ['DOCUMENT_UPLOAD'],
    screenNames: ['DocumentUploadPlaceholderScreen'],
    hookNames: ['useCreateDocument'],
    repositoryMethods: ['createDocumentMetadata'],
    mockDataKeys: ['documentUploadMockData'],
    requiredActions: ['Select file/camera image, enter metadata, create mock document'],
    status: 'IMPLEMENTED',
  },
  {
    id: 'doc-society',
    title: 'SocietyDocuments',
    phase: 'MVP',
    moduleName: 'documents',
    featureFlag: 'documentVault',
    permissions: ['DOCUMENT_VIEW'],
    roles: ["RESIDENT"],
    routeNames: ['SOCIETY_DOCUMENTS'],
    screenNames: ['SocietyDocumentsScreen'],
    hookNames: ['useDocumentsByCategory'],
    repositoryMethods: ['listDocumentsByCategory'],
    mockDataKeys: ['categorizedDocumentsMockData'],
    requiredActions: ['Filter documents by category, sensitivity and expiry'],
    status: 'IMPLEMENTED',
  },
  {
    id: 'doc-owner',
    title: 'OwnerDocuments',
    phase: 'MVP',
    moduleName: 'documents',
    featureFlag: 'documentVault',
    permissions: ['DOCUMENT_VIEW'],
    roles: ["RESIDENT"],
    routeNames: ['OWNER_DOCUMENTS'],
    screenNames: ['OwnerDocumentsScreen'],
    hookNames: ['useDocumentsByCategory'],
    repositoryMethods: ['listDocumentsByCategory'],
    mockDataKeys: ['categorizedDocumentsMockData'],
    requiredActions: ['Filter owner documents'],
    status: 'IMPLEMENTED',
  },
  {
    id: 'doc-tenant',
    title: 'TenantDocuments',
    phase: 'MVP',
    moduleName: 'documents',
    featureFlag: 'documentVault',
    permissions: ['DOCUMENT_VIEW'],
    roles: ["RESIDENT"],
    routeNames: ['TENANT_DOCUMENTS'],
    screenNames: ['TenantDocumentsScreen'],
    hookNames: ['useDocumentsByCategory'],
    repositoryMethods: ['listDocumentsByCategory'],
    mockDataKeys: ['categorizedDocumentsMockData'],
    requiredActions: ['Filter tenant documents'],
    status: 'IMPLEMENTED',
  },
  {
    id: 'doc-movein',
    title: 'MoveInDocuments',
    phase: 'MVP',
    moduleName: 'documents',
    featureFlag: 'documentVault',
    permissions: ['DOCUMENT_VIEW'],
    roles: ["RESIDENT"],
    routeNames: ['MOVE_IN_DOCUMENTS'],
    screenNames: ['MoveInDocumentsScreen'],
    hookNames: ['useDocumentsByCategory'],
    repositoryMethods: ['listDocumentsByCategory'],
    mockDataKeys: ['categorizedDocumentsMockData'],
    requiredActions: ['Filter move-in documents'],
    status: 'IMPLEMENTED',
  },
  {
    id: 'doc-moveout',
    title: 'MoveOutDocuments',
    phase: 'MVP',
    moduleName: 'documents',
    featureFlag: 'documentVault',
    permissions: ['DOCUMENT_VIEW'],
    roles: ["RESIDENT"],
    routeNames: ['MOVE_OUT_DOCUMENTS'],
    screenNames: ['MoveOutDocumentsScreen'],
    hookNames: ['useDocumentsByCategory'],
    repositoryMethods: ['listDocumentsByCategory'],
    mockDataKeys: ['categorizedDocumentsMockData'],
    requiredActions: ['Filter move-out documents'],
    status: 'IMPLEMENTED',
  },
  {
    id: 'doc-staffvendor',
    title: 'StaffVendorDocuments',
    phase: 'MVP',
    moduleName: 'documents',
    featureFlag: 'documentVault',
    permissions: ['DOCUMENT_VIEW'],
    roles: ["RESIDENT"],
    routeNames: ['STAFF_VENDOR_DOCUMENTS'],
    screenNames: ['StaffVendorDocumentsScreen'],
    hookNames: ['useDocumentsByCategory'],
    repositoryMethods: ['listDocumentsByCategory'],
    mockDataKeys: ['categorizedDocumentsMockData'],
    requiredActions: ['Filter staff documents'],
    status: 'IMPLEMENTED',
  },
  {
    id: 'doc-compliance',
    title: 'ComplianceDocuments',
    phase: 'MVP',
    moduleName: 'documents',
    featureFlag: 'documentVault',
    permissions: ['DOCUMENT_VIEW'],
    roles: ["RESIDENT"],
    routeNames: ['COMPLIANCE_DOCUMENTS'],
    screenNames: ['ComplianceDocumentsScreen'],
    hookNames: ['useDocumentsByCategory'],
    repositoryMethods: ['listDocumentsByCategory'],
    mockDataKeys: ['categorizedDocumentsMockData'],
    requiredActions: ['Filter compliance documents'],
    status: 'IMPLEMENTED',
  },
  {
    id: 'doc-accesslog',
    title: 'DocumentAccessLog',
    phase: 'MVP',
    moduleName: 'documents',
    featureFlag: 'documentVault',
    permissions: ['DOCUMENT_VIEW'],
    roles: ["RESIDENT"],
    routeNames: ['DOCUMENT_ACCESS_LOG'],
    screenNames: ['DocumentAccessLogScreen'],
    hookNames: ['useDocumentAccessLog'],
    repositoryMethods: ['listDocumentAccessLogs'],
    mockDataKeys: ['documentAccessLogMockData'],
    requiredActions: ['Add mock access log when document detail is opened'],
    status: 'IMPLEMENTED',
  },
  {
    id: 'doc-versionhistory',
    title: 'DocumentVersionHistory',
    phase: 'MVP',
    moduleName: 'documents',
    featureFlag: 'documentVault',
    permissions: ['DOCUMENT_VIEW'],
    roles: ["RESIDENT"],
    routeNames: ['DOCUMENT_VERSION_HISTORY'],
    screenNames: ['DocumentVersionHistoryScreen'],
    hookNames: ['useDocumentVersionHistory'],
    repositoryMethods: ['listDocumentVersions'],
    mockDataKeys: ['documentVersionHistoryMockData'],
    requiredActions: ['Show versions, uploaded by, expiry and status'],
    status: 'IMPLEMENTED',
  },
  {
    id: 'doc-restricted',
    title: 'RestrictedDocumentAccess',
    phase: 'MVP',
    moduleName: 'documents',
    featureFlag: 'documentVault',
    permissions: ['DOCUMENT_VIEW'],
    roles: ["RESIDENT"],
    routeNames: ['RESTRICTED_DOCUMENT_ACCESS'],
    screenNames: ['RestrictedDocumentAccessScreen'],
    hookNames: ['useRestrictedDocumentAccess'],
    repositoryMethods: ['requestDocumentAccess'],
    mockDataKeys: ['restrictedDocumentAccessMockData'],
    requiredActions: ['Show permission denied and request access placeholder'],
    status: 'IMPLEMENTED',
  },
  {
    id: 'noc-create',
    title: 'CreateNocRequest',
    phase: 'MVP',
    moduleName: 'noc',
    featureFlag: 'digitalNocRequests',
    permissions: ['NOC_WRITE'],
    roles: ["RESIDENT"],
    routeNames: ['CREATE_NOC_REQUEST'],
    screenNames: ['CreateNocRequestScreen'],
    hookNames: ['useCreateNocRequest'],
    repositoryMethods: ['createNocRequest'],
    mockDataKeys: ['nocRequestMockData'],
    requiredActions: ['Select NOC type, attach documents, submit request'],
    status: 'IMPLEMENTED',
  },
  {
    id: 'noc-clearance',
    title: 'NocClearanceChecklist',
    phase: 'MVP',
    moduleName: 'noc',
    featureFlag: 'moveOutNocMandatory',
    permissions: ['NOC_WRITE'],
    roles: ["RESIDENT"],
    routeNames: ['NOC_CLEARANCE_CHECKLIST'],
    screenNames: ['NocClearanceChecklistScreen'],
    hookNames: ['useNocClearanceChecklist'],
    repositoryMethods: ['runNocClearanceChecklist'],
    mockDataKeys: ['nocClearanceChecklistMockData'],
    requiredActions: ['Check dues, complaints, parking sticker, access card and documents'],
    status: 'IMPLEMENTED',
  },
  {
    id: 'noc-nodues',
    title: 'NoDuesCertificate',
    phase: 'MVP',
    moduleName: 'noc',
    featureFlag: 'certificateRequests',
    permissions: ['NOC_VIEW'],
    roles: ["RESIDENT"],
    routeNames: ['NO_DUES_CERTIFICATE'],
    screenNames: ['NoDuesCertificateScreen'],
    hookNames: ['useNoDuesCertificate'],
    repositoryMethods: ['generateNoDuesCertificatePreview'],
    mockDataKeys: ['noDuesCertificateMockData'],
    requiredActions: ['Generate no dues preview after mock clearance'],
    status: 'IMPLEMENTED',
  },
  {
    id: 'noc-moveout',
    title: 'MoveOutNoc',
    phase: 'MVP',
    moduleName: 'noc',
    featureFlag: 'moveOutNocMandatory',
    permissions: ['NOC_VIEW'],
    roles: ["RESIDENT"],
    routeNames: ['MOVE_OUT_NOC'],
    screenNames: ['MoveOutNocScreen'],
    hookNames: ['useMoveOutNoc'],
    repositoryMethods: ['generateMoveOutNocPreview'],
    mockDataKeys: ['moveOutNocMockData'],
    requiredActions: ['Generate move-out NOC preview after clearances'],
    status: 'IMPLEMENTED',
  },
  {
    id: 'noc-tenant',
    title: 'TenantNoc',
    phase: 'MVP',
    moduleName: 'noc',
    featureFlag: 'digitalNocRequests',
    permissions: ['NOC_VIEW'],
    roles: ["RESIDENT"],
    routeNames: ['TENANT_NOC'],
    screenNames: ['TenantNocScreen'],
    hookNames: ['useTenantNoc'],
    repositoryMethods: ['generateTenantNocPreview'],
    mockDataKeys: ['tenantNocMockData'],
    requiredActions: ['Check owner approval, KYC, agreement, police verification'],
    status: 'IMPLEMENTED',
  },
  {
    id: 'noc-parking',
    title: 'ParkingNoc',
    phase: 'MVP',
    moduleName: 'noc',
    featureFlag: 'digitalNocRequests',
    permissions: ['NOC_VIEW'],
    roles: ["RESIDENT"],
    routeNames: ['PARKING_NOC'],
    screenNames: ['ParkingNocScreen'],
    hookNames: ['useParkingNoc'],
    repositoryMethods: ['generateParkingNocPreview'],
    mockDataKeys: ['parkingNocMockData'],
    requiredActions: ['Check parking dues, sticker return and violations'],
    status: 'IMPLEMENTED',
  },
  {
    id: 'noc-renovation',
    title: 'RenovationNoc',
    phase: 'MVP',
    moduleName: 'noc',
    featureFlag: 'renovationWorkflow',
    permissions: ['NOC_VIEW'],
    roles: ["RESIDENT"],
    routeNames: ['RENOVATION_NOC'],
    screenNames: ['RenovationNocScreen'],
    hookNames: ['useRenovationNoc'],
    repositoryMethods: ['generateRenovationNocPreview'],
    mockDataKeys: ['renovationNocMockData'],
    requiredActions: ['Check damage inspection and debris clearance'],
    status: 'IMPLEMENTED',
  },
  {
    id: 'noc-residence',
    title: 'ResidenceCertificate',
    phase: 'MVP',
    moduleName: 'noc',
    featureFlag: 'certificateRequests',
    permissions: ['NOC_VIEW'],
    roles: ["RESIDENT"],
    routeNames: ['RESIDENCE_CERTIFICATE'],
    screenNames: ['ResidenceCertificateScreen'],
    hookNames: ['useResidenceCertificate'],
    repositoryMethods: ['generateResidenceCertificatePreview'],
    mockDataKeys: ['residenceCertificateMockData'],
    requiredActions: ['Check active occupancy and document verification'],
    status: 'IMPLEMENTED',
  },
  {
    id: 'noc-qrverifiable',
    title: 'QrVerifiableCertificatePlaceholder',
    phase: 'MVP',
    moduleName: 'noc',
    featureFlag: 'certificateRequests',
    permissions: ['NOC_VIEW'],
    roles: ["RESIDENT"],
    routeNames: ['QR_VERIFIABLE_CERTIFICATE'],
    screenNames: ['QrVerifiableCertificatePlaceholderScreen'],
    hookNames: ['useQrVerifiableCertificate'],
    repositoryMethods: ['generateQrCertificatePlaceholder'],
    mockDataKeys: ['qrCertificateMockData'],
    requiredActions: ['Show certificate QR placeholder and verification code'],
    status: 'IMPLEMENTED',
  },
  {
    id: 'hist-occupancy',
    title: 'OccupancyHistory',
    phase: 'MVP',
    moduleName: 'occupancy',
    featureFlag: 'occupancyHistory',
    permissions: ['READ_SOCIETY'],
    roles: ["RESIDENT"],
    routeNames: ['OCCUPANCY_HISTORY'],
    screenNames: ['OccupancyHistoryScreen'],
    hookNames: ['useOccupancyHistory'],
    repositoryMethods: ['listOccupancyHistoryByUnit'],
    mockDataKeys: ['occupancyHistoryMockData'],
    requiredActions: ['Filter history by owner, tenant, active, moved out'],
    status: 'IMPLEMENTED',
  },
  {
    id: 'hist-owner',
    title: 'OwnerHistory',
    phase: 'MVP',
    moduleName: 'occupancy',
    featureFlag: 'ownerTenantHistory',
    permissions: ['READ_SOCIETY'],
    roles: ["RESIDENT"],
    routeNames: ['OWNER_HISTORY'],
    screenNames: ['OwnerHistoryScreen'],
    hookNames: ['useOwnerHistory'],
    repositoryMethods: ['listOwnerHistoryByUnit'],
    mockDataKeys: ['ownerHistoryMockData'],
    requiredActions: ['Open previous owner detail and linked documents'],
    status: 'IMPLEMENTED',
  },
  {
    id: 'hist-tenant',
    title: 'TenantHistory',
    phase: 'MVP',
    moduleName: 'occupancy',
    featureFlag: 'ownerTenantHistory',
    permissions: ['READ_SOCIETY'],
    roles: ["RESIDENT"],
    routeNames: ['TENANT_HISTORY'],
    screenNames: ['TenantHistoryScreen'],
    hookNames: ['useTenantHistory'],
    repositoryMethods: ['listTenantHistoryByUnit'],
    mockDataKeys: ['tenantHistoryMockData'],
    requiredActions: ['Open previous tenant detail, NOC status and dues status'],
    status: 'IMPLEMENTED',
  },
  {
    id: 'hist-timeline',
    title: 'FlatTimeline',
    phase: 'MVP',
    moduleName: 'occupancy',
    featureFlag: 'ownerTenantHistory',
    permissions: ['READ_SOCIETY'],
    roles: ["RESIDENT"],
    routeNames: ['FLAT_TIMELINE'],
    screenNames: ['FlatTimelineScreen'],
    hookNames: ['useFlatTimeline'],
    repositoryMethods: ['getFlatTimeline'],
    mockDataKeys: ['flatTimelineMockData'],
    requiredActions: ['Show owner change, tenant move-in, move-out, NOC and access events'],
    status: 'IMPLEMENTED',
  },
  {
    id: 'hist-archive',
    title: 'PreviousResidentDocumentArchive',
    phase: 'MVP',
    moduleName: 'occupancy',
    featureFlag: 'residentDocumentArchive',
    permissions: ['DOCUMENT_VIEW'],
    roles: ["RESIDENT"],
    routeNames: ['PREVIOUS_RESIDENT_DOCUMENT_ARCHIVE'],
    screenNames: ['PreviousResidentDocumentArchiveScreen'],
    hookNames: ['usePreviousResidentDocumentArchive'],
    repositoryMethods: ['listPreviousResidentDocuments'],
    mockDataKeys: ['previousResidentDocumentsMockData'],
    requiredActions: ['Show restricted archive and hide from new residents'],
    status: 'IMPLEMENTED',
  },
  {
    id: 'hist-movein',
    title: 'MoveInRequest',
    phase: 'MVP',
    moduleName: 'occupancy',
    featureFlag: 'moveInMoveOutLogistics',
    permissions: ['NOC_WRITE'],
    roles: ["RESIDENT"],
    routeNames: ['MOVE_IN_REQUEST'],
    screenNames: ['MoveInRequestScreen'],
    hookNames: ['useCreateMoveInRequest'],
    repositoryMethods: ['createMoveInRequest'],
    mockDataKeys: ['moveInRequestMockData'],
    requiredActions: ['Submit move-in request with document upload and lift slot'],
    status: 'IMPLEMENTED',
  },
  {
    id: 'hist-moveout',
    title: 'MoveOutRequest',
    phase: 'MVP',
    moduleName: 'occupancy',
    featureFlag: 'moveInMoveOutLogistics',
    permissions: ['NOC_WRITE'],
    roles: ["RESIDENT"],
    routeNames: ['MOVE_OUT_REQUEST'],
    screenNames: ['MoveOutRequestScreen'],
    hookNames: ['useCreateMoveOutRequest'],
    repositoryMethods: ['createMoveOutRequest'],
    mockDataKeys: ['moveOutRequestMockData'],
    requiredActions: ['Submit move-out request and require NOC checklist'],
    status: 'IMPLEMENTED',
  },
  {
    id: 'hist-activation',
    title: 'AccessActivationRevocation',
    phase: 'MVP',
    moduleName: 'occupancy',
    featureFlag: 'moveInMoveOutLogistics',
    permissions: ['WRITE_SOCIETY'],
    roles: ["RESIDENT"],
    routeNames: ['ACCESS_ACTIVATION_REVOCATION'],
    screenNames: ['AccessActivationRevocationScreen'],
    hookNames: ['useAccessActivationRevocation'],
    repositoryMethods: ['activateResidentAccess'],
    mockDataKeys: ['accessActivationRevocationMockData'],
    requiredActions: ['Activate/revoke access in mock state with audit note'],
    status: 'IMPLEMENTED',
  },
  {
    id: 'conn-privacy',
    title: 'ResidentDirectoryPrivacy',
    phase: 'MVP',
    moduleName: 'residentConnect',
    featureFlag: 'privacyDirectory',
    permissions: ['READ_RESIDENT'],
    roles: ["RESIDENT"],
    routeNames: ['RESIDENT_DIRECTORY_PRIVACY'],
    screenNames: ['ResidentDirectoryPrivacyScreen'],
    hookNames: ['useResidentDirectoryPrivacy'],
    repositoryMethods: ['updateDirectoryVisibility'],
    mockDataKeys: ['directoryPrivacyMockData'],
    requiredActions: ['Opt in/out of name, flat and contact visibility'],
    status: 'IMPLEMENTED',
  },
  {
    id: 'conn-search',
    title: 'SearchFlatResident',
    phase: 'MVP',
    moduleName: 'residentConnect',
    featureFlag: 'privacyDirectory',
    permissions: ['READ_RESIDENT'],
    roles: ["RESIDENT"],
    routeNames: ['SEARCH_FLAT_RESIDENT'],
    screenNames: ['SearchFlatResidentScreen'],
    hookNames: ['useSearchFlatResident'],
    repositoryMethods: ['searchFlatResident'],
    mockDataKeys: ['searchableResidentsMockData'],
    requiredActions: ['Search by flat number without exposing phone number'],
    status: 'IMPLEMENTED',
  },
  {
    id: 'conn-firstcontact',
    title: 'FirstContactRequest',
    phase: 'MVP',
    moduleName: 'residentConnect',
    featureFlag: 'residentMessenger',
    permissions: ['READ_RESIDENT'],
    roles: ["RESIDENT"],
    routeNames: ['FIRST_CONTACT_REQUEST'],
    screenNames: ['FirstContactRequestScreen'],
    hookNames: ['useCreateFirstContactRequest'],
    repositoryMethods: ['createFirstContactRequest'],
    mockDataKeys: ['firstContactRequestMockData'],
    requiredActions: ['Send request with required subject and reason'],
    status: 'IMPLEMENTED',
  },
  {
    id: 'conn-requestdetail',
    title: 'ContactRequestDetail',
    phase: 'MVP',
    moduleName: 'residentConnect',
    featureFlag: 'residentMessenger',
    permissions: ['READ_RESIDENT'],
    roles: ["RESIDENT"],
    routeNames: ['CONTACT_REQUEST_DETAIL'],
    screenNames: ['ContactRequestDetailScreen'],
    hookNames: ['useContactRequestDecision'],
    repositoryMethods: ['acceptContactRequest'],
    mockDataKeys: ['contactRequestDecisionMockData'],
    requiredActions: ['Accept, reject, block or report request'],
    status: 'IMPLEMENTED',
  },
  {
    id: 'conn-chat',
    title: 'PrivateChatThread',
    phase: 'MVP',
    moduleName: 'residentConnect',
    featureFlag: 'residentMessenger',
    permissions: ['READ_RESIDENT'],
    roles: ["RESIDENT"],
    routeNames: ['PRIVATE_CHAT_THREAD'],
    screenNames: ['PrivateChatThreadScreen'],
    hookNames: ['usePrivateChatThread'],
    repositoryMethods: ['sendPrivateChatMessage'],
    mockDataKeys: ['privateChatThreadMockData'],
    requiredActions: ['Send mock message after accepted contact request'],
    status: 'IMPLEMENTED',
  },
  {
    id: 'conn-deptchat',
    title: 'DepartmentChat',
    phase: 'MVP',
    moduleName: 'residentConnect',
    featureFlag: 'residentMessenger',
    permissions: ['READ_RESIDENT'],
    roles: ["RESIDENT"],
    routeNames: ['DEPARTMENT_CHAT'],
    screenNames: ['DepartmentChatScreen'],
    hookNames: ['useDepartmentChat'],
    repositoryMethods: ['sendDepartmentMessage'],
    mockDataKeys: ['departmentChatMockData'],
    requiredActions: ['Send message to accounts department'],
    status: 'IMPLEMENTED',
  },
  {
    id: 'conn-groupchat',
    title: 'ControlledGroupChat',
    phase: 'MVP',
    moduleName: 'residentConnect',
    featureFlag: 'controlledGroupChat',
    permissions: ['READ_RESIDENT'],
    roles: ["RESIDENT"],
    routeNames: ['CONTROLLED_GROUP_CHAT'],
    screenNames: ['ControlledGroupChatScreen'],
    hookNames: ['useControlledGroupChat'],
    repositoryMethods: ['sendGroupMessage'],
    mockDataKeys: ['controlledGroupChatMockData'],
    requiredActions: ['Send message to tower/floor/owners/tenants group'],
    status: 'IMPLEMENTED',
  },
  {
    id: 'conn-blocked',
    title: 'BlockedReportedUsers',
    phase: 'MVP',
    moduleName: 'residentConnect',
    featureFlag: 'residentMessenger',
    permissions: ['READ_RESIDENT'],
    roles: ["RESIDENT"],
    routeNames: ['BLOCKED_REPORTED_USERS'],
    screenNames: ['BlockedReportedUsersScreen'],
    hookNames: ['useBlockedReportedUsers'],
    repositoryMethods: ['listBlockedUsers'],
    mockDataKeys: ['blockedReportedUsersMockData'],
    requiredActions: ['Unblock user and show reported metadata'],
    status: 'IMPLEMENTED',
  },
  {
    id: 'conn-moderation',
    title: 'ReportedMessageModerationPlaceholder',
    phase: 'MVP',
    moduleName: 'residentConnect',
    featureFlag: 'residentMessenger',
    permissions: ['WRITE_SOCIETY'],
    roles: ["RESIDENT"],
    routeNames: ['REPORTED_MESSAGE_MODERATION'],
    screenNames: ['ReportedMessageModerationPlaceholderScreen'],
    hookNames: ['useReportedMessageModeration'],
    repositoryMethods: ['listReportedMessages'],
    mockDataKeys: ['reportedMessageModerationMockData'],
    requiredActions: ['Show only reported messages and metadata, not full private chat'],
    status: 'IMPLEMENTED',
  },
  {
    id: 'issue-leakage',
    title: 'WaterLeakageIssue',
    phase: 'MVP',
    moduleName: 'interFlatIssues',
    featureFlag: 'interFlatIssues',
    permissions: ['COMPLAINT_WRITE'],
    roles: ["RESIDENT"],
    routeNames: ['WATER_LEAKAGE_ISSUE'],
    screenNames: ['WaterLeakageIssueScreen'],
    hookNames: ['useCreateWaterLeakageIssue'],
    repositoryMethods: ['createWaterLeakageIssue'],
    mockDataKeys: ['waterLeakageIssueMockData'],
    requiredActions: ['Submit water leakage issue with affected flat and evidence'],
    status: 'IMPLEMENTED',
  },
  {
    id: 'issue-noise',
    title: 'NoiseComplaintIssue',
    phase: 'MVP',
    moduleName: 'interFlatIssues',
    featureFlag: 'interFlatIssues',
    permissions: ['COMPLAINT_WRITE'],
    roles: ["RESIDENT"],
    routeNames: ['NOISE_COMPLAINT_ISSUE'],
    screenNames: ['NoiseComplaintIssueScreen'],
    hookNames: ['useCreateNoiseComplaintIssue'],
    repositoryMethods: ['createNoiseComplaintIssue'],
    mockDataKeys: ['noiseComplaintIssueMockData'],
    requiredActions: ['Submit noise issue with quiet-hours note'],
    status: 'IMPLEMENTED',
  },
  {
    id: 'issue-renovation',
    title: 'RenovationDisturbanceIssue',
    phase: 'MVP',
    moduleName: 'interFlatIssues',
    featureFlag: 'interFlatIssues',
    permissions: ['COMPLAINT_WRITE'],
    roles: ["RESIDENT"],
    routeNames: ['RENOVATION_DISTURBANCE_ISSUE'],
    screenNames: ['RenovationDisturbanceIssueScreen'],
    hookNames: ['useCreateRenovationDisturbanceIssue'],
    repositoryMethods: ['createRenovationDisturbanceIssue'],
    mockDataKeys: ['renovationDisturbanceIssueMockData'],
    requiredActions: ['Submit renovation disturbance with contractor/pass reference'],
    status: 'IMPLEMENTED',
  },
  {
    id: 'issue-pet',
    title: 'PetNuisanceIssue',
    phase: 'MVP',
    moduleName: 'interFlatIssues',
    featureFlag: 'interFlatIssues',
    permissions: ['COMPLAINT_WRITE'],
    roles: ["RESIDENT"],
    routeNames: ['PET_NUISANCE_ISSUE'],
    screenNames: ['PetNuisanceIssueScreen'],
    hookNames: ['useCreatePetNuisanceIssue'],
    repositoryMethods: ['createPetNuisanceIssue'],
    mockDataKeys: ['petNuisanceIssueMockData'],
    requiredActions: ['Submit pet nuisance issue with polite notification text'],
    status: 'IMPLEMENTED',
  },
  {
    id: 'issue-damage',
    title: 'DamageClaimIssue',
    phase: 'MVP',
    moduleName: 'interFlatIssues',
    featureFlag: 'interFlatIssues',
    permissions: ['COMPLAINT_WRITE'],
    roles: ["RESIDENT"],
    routeNames: ['DAMAGE_CLAIM_ISSUE'],
    screenNames: ['DamageClaimIssueScreen'],
    hookNames: ['useCreateDamageClaimIssue'],
    repositoryMethods: ['createDamageClaimIssue'],
    mockDataKeys: ['damageClaimIssueMockData'],
    requiredActions: ['Submit damage claim with estimated amount and evidence'],
    status: 'IMPLEMENTED',
  },
  {
    id: 'issue-parking',
    title: 'WrongParkingIssue',
    phase: 'MVP',
    moduleName: 'interFlatIssues',
    featureFlag: 'interFlatIssues',
    permissions: ['COMPLAINT_WRITE'],
    roles: ["RESIDENT"],
    routeNames: ['WRONG_PARKING_ISSUE'],
    screenNames: ['WrongParkingIssueScreen'],
    hookNames: ['useCreateWrongParkingIssue'],
    repositoryMethods: ['createWrongParkingIssue'],
    mockDataKeys: ['wrongParkingIssueMockData'],
    requiredActions: ['Submit wrong parking issue with vehicle number and photo'],
    status: 'IMPLEMENTED',
  },
  {
    id: 'issue-mediation',
    title: 'MediationAssignment',
    phase: 'MVP',
    moduleName: 'interFlatIssues',
    featureFlag: 'disputeMediation',
    permissions: ['COMPLAINT_WRITE'],
    roles: ["RESIDENT"],
    routeNames: ['MEDIATION_ASSIGNMENT'],
    screenNames: ['MediationAssignmentScreen'],
    hookNames: ['useMediationAssignment'],
    repositoryMethods: ['assignMediator'],
    mockDataKeys: ['mediationAssignmentMockData'],
    requiredActions: ['Assign facility manager/committee mediator'],
    status: 'IMPLEMENTED',
  },
  {
    id: 'issue-proposal',
    title: 'ResolutionProposal',
    phase: 'MVP',
    moduleName: 'interFlatIssues',
    featureFlag: 'disputeMediation',
    permissions: ['COMPLAINT_WRITE'],
    roles: ["RESIDENT"],
    routeNames: ['RESOLUTION_PROPOSAL'],
    screenNames: ['ResolutionProposalScreen'],
    hookNames: ['useResolutionProposal'],
    repositoryMethods: ['submitResolutionProposal'],
    mockDataKeys: ['resolutionProposalMockData'],
    requiredActions: ['Submit proposed resolution and mark accepted/rejected'],
    status: 'IMPLEMENTED',
  },
  {
    id: 'issue-closure',
    title: 'ClosureProof',
    phase: 'MVP',
    moduleName: 'interFlatIssues',
    featureFlag: 'disputeMediation',
    permissions: ['COMPLAINT_WRITE'],
    roles: ["RESIDENT"],
    routeNames: ['CLOSURE_PROOF'],
    screenNames: ['ClosureProofScreen'],
    hookNames: ['useClosureProof'],
    repositoryMethods: ['submitClosureProof'],
    mockDataKeys: ['closureProofMockData'],
    requiredActions: ['Attach closure proof and close issue'],
    status: 'IMPLEMENTED',
  },
  {
    id: 'parcel-request',
    title: 'ParcelHandoverRequest',
    phase: 'MVP',
    moduleName: 'parcelHandover',
    featureFlag: 'parcelHandover',
    permissions: ['GATE_VERIFICATION'],
    roles: ["RESIDENT"],
    routeNames: ['PARCEL_HANDOVER_REQUEST'],
    screenNames: ['ParcelHandoverRequestScreen'],
    hookNames: ['useCreateParcelHandoverRequest'],
    repositoryMethods: ['createParcelHandoverRequest'],
    mockDataKeys: ['parcelHandoverMockData'],
    requiredActions: ['Create parcel handover request for resident'],
    status: 'IMPLEMENTED',
  },
  {
    id: 'parcel-otpqrdoc',
    title: 'ParcelOtpQrPlaceholder',
    phase: 'MVP',
    moduleName: 'parcelHandover',
    featureFlag: 'parcelHandover',
    permissions: ['GATE_VERIFICATION'],
    roles: ["RESIDENT"],
    routeNames: ['PARCEL_OTP_QR'],
    screenNames: ['ParcelOtpQrPlaceholderScreen'],
    hookNames: ['useParcelOtpQr'],
    repositoryMethods: ['getParcelOtpQr'],
    mockDataKeys: ['parcelOtpQrMockData'],
    requiredActions: ['Show OTP/QR placeholder for parcel pickup'],
    status: 'IMPLEMENTED',
  },
  {
    id: 'parcel-confirm',
    title: 'ParcelPickupConfirmation',
    phase: 'MVP',
    moduleName: 'parcelHandover',
    featureFlag: 'parcelHandover',
    permissions: ['GATE_VERIFICATION'],
    roles: ["RESIDENT"],
    routeNames: ['PARCEL_PICKUP_CONFIRMATION'],
    screenNames: ['ParcelPickupConfirmationScreen'],
    hookNames: ['useParcelPickupConfirmation'],
    repositoryMethods: ['confirmParcelPickup'],
    mockDataKeys: ['parcelPickupConfirmationMockData'],
    requiredActions: ['Confirm pickup and update parcel history'],
    status: 'IMPLEMENTED',
  },
  {
    id: 'fac-list',
    title: 'FacilityList',
    phase: 'MVP',
    moduleName: 'facilityBooking',
    featureFlag: 'facilityBooking',
    permissions: ['READ_SOCIETY'],
    roles: ["RESIDENT"],
    routeNames: ['FACILITY_LIST'],
    screenNames: ['FacilityListScreen'],
    hookNames: ['useFacilities'],
    repositoryMethods: ['listFacilities'],
    mockDataKeys: ['facilitiesMockData'],
    requiredActions: ['Open facility detail and show capacity/rules/charges'],
    status: 'IMPLEMENTED',
  },
  {
    id: 'fac-slots',
    title: 'SlotAvailability',
    phase: 'MVP',
    moduleName: 'facilityBooking',
    featureFlag: 'facilityBooking',
    permissions: ['READ_SOCIETY'],
    roles: ["RESIDENT"],
    routeNames: ['SLOT_AVAILABILITY'],
    screenNames: ['SlotAvailabilityScreen'],
    hookNames: ['useFacilitySlotAvailability'],
    repositoryMethods: ['listAvailableFacilitySlots'],
    mockDataKeys: ['facilitySlotsMockData'],
    requiredActions: ['Select available slot and block double booking in mock mode'],
    status: 'IMPLEMENTED',
  },
  {
    id: 'fac-booking',
    title: 'CreateFacilityBooking',
    phase: 'MVP',
    moduleName: 'facilityBooking',
    featureFlag: 'facilityBooking',
    permissions: ['READ_SOCIETY'],
    roles: ["RESIDENT"],
    routeNames: ['CREATE_FACILITY_BOOKING'],
    screenNames: ['CreateFacilityBookingScreen'],
    hookNames: ['useCreateFacilityBooking'],
    repositoryMethods: ['createFacilityBooking'],
    mockDataKeys: ['facilityBookingMockData'],
    requiredActions: ['Create booking with date, slot, purpose and guest count'],
    status: 'IMPLEMENTED',
  },
  {
    id: 'fac-approval',
    title: 'BookingApproval',
    phase: 'MVP',
    moduleName: 'facilityBooking',
    featureFlag: 'facilityAdminApproval',
    permissions: ['WRITE_SOCIETY'],
    roles: ["RESIDENT"],
    routeNames: ['BOOKING_APPROVAL'],
    screenNames: ['BookingApprovalScreen'],
    hookNames: ['useFacilityBookingApproval'],
    repositoryMethods: ['approveFacilityBooking'],
    mockDataKeys: ['bookingApprovalMockData'],
    requiredActions: ['Approve or reject booking in mock state'],
    status: 'IMPLEMENTED',
  },
  {
    id: 'fac-cancel',
    title: 'BookingCancellation',
    phase: 'MVP',
    moduleName: 'facilityBooking',
    featureFlag: 'facilityBooking',
    permissions: ['READ_SOCIETY'],
    roles: ["RESIDENT"],
    routeNames: ['BOOKING_CANCELLATION'],
    screenNames: ['BookingCancellationScreen'],
    hookNames: ['useCancelFacilityBooking'],
    repositoryMethods: ['cancelFacilityBooking'],
    mockDataKeys: ['bookingCancellationMockData'],
    requiredActions: ['Cancel booking with reason'],
    status: 'IMPLEMENTED',
  },
  {
    id: 'fac-qrcheckin',
    title: 'QrCheckInPlaceholder',
    phase: 'MVP',
    moduleName: 'facilityBooking',
    featureFlag: 'facilityQrCheckIn',
    permissions: ['READ_SOCIETY'],
    roles: ["RESIDENT"],
    routeNames: ['FACILITY_QR_CHECK_IN'],
    screenNames: ['QrCheckInPlaceholderScreen'],
    hookNames: ['useFacilityQrCheckIn'],
    repositoryMethods: ['createFacilityQrCheckInPlaceholder'],
    mockDataKeys: ['facilityQrCheckInMockData'],
    requiredActions: ['Show QR check-in placeholder and mark checked-in'],
    status: 'IMPLEMENTED',
  },
  {
    id: 'park-register',
    title: 'VehicleRegistration',
    phase: 'MVP',
    moduleName: 'parking',
    featureFlag: 'parkingVehicles',
    permissions: ['READ_SOCIETY'],
    roles: ["RESIDENT"],
    routeNames: ['VEHICLE_REGISTRATION'],
    screenNames: ['VehicleRegistrationScreen'],
    hookNames: ['useVehicleRegistration'],
    repositoryMethods: ['registerVehicle'],
    mockDataKeys: ['vehicleRegistrationMockData'],
    requiredActions: ['Register vehicle with number, type, owner and parking need'],
    status: 'IMPLEMENTED',
  },
  {
    id: 'park-alloc',
    title: 'ParkingAllocation',
    phase: 'MVP',
    moduleName: 'parking',
    featureFlag: 'parking',
    permissions: ['WRITE_SOCIETY'],
    roles: ["RESIDENT"],
    routeNames: ['PARKING_ALLOCATION'],
    screenNames: ['ParkingAllocationScreen'],
    hookNames: ['useParkingAllocation'],
    repositoryMethods: ['allocateParkingSlot'],
    mockDataKeys: ['parkingAllocationMockData'],
    requiredActions: ['Allocate slot to unit/vehicle'],
    status: 'IMPLEMENTED',
  },
  {
    id: 'park-visitor',
    title: 'VisitorParkingPass',
    phase: 'MVP',
    moduleName: 'parking',
    featureFlag: 'visitorParking',
    permissions: ['CREATE_VISITOR'],
    roles: ["RESIDENT"],
    routeNames: ['VISITOR_PARKING_PASS'],
    screenNames: ['VisitorParkingPassScreen'],
    hookNames: ['useVisitorParkingPass'],
    repositoryMethods: ['createVisitorParkingPass'],
    mockDataKeys: ['visitorParkingPassMockData'],
    requiredActions: ['Create visitor parking pass with expiry'],
    status: 'IMPLEMENTED',
  },
  {
    id: 'park-temp',
    title: 'TemporaryVehiclePass',
    phase: 'MVP',
    moduleName: 'parking',
    featureFlag: 'visitorParking',
    permissions: ['CREATE_VISITOR'],
    roles: ["RESIDENT"],
    routeNames: ['TEMPORARY_VEHICLE_PASS'],
    screenNames: ['TemporaryVehiclePassScreen'],
    hookNames: ['useTemporaryVehiclePass'],
    repositoryMethods: ['createTemporaryVehiclePass'],
    mockDataKeys: ['temporaryVehiclePassMockData'],
    requiredActions: ['Create temporary pass for rented/guest vehicle'],
    status: 'IMPLEMENTED',
  },
  {
    id: 'park-violations',
    title: 'ParkingViolationHistory',
    phase: 'MVP',
    moduleName: 'parking',
    featureFlag: 'wrongParkingReports',
    permissions: ['READ_SOCIETY'],
    roles: ["RESIDENT"],
    routeNames: ['PARKING_VIOLATION_HISTORY'],
    screenNames: ['ParkingViolationHistoryScreen'],
    hookNames: ['useParkingViolationHistory'],
    repositoryMethods: ['listParkingViolations'],
    mockDataKeys: ['parkingViolationHistoryMockData'],
    requiredActions: ['Add wrong parking/blocking violation'],
    status: 'IMPLEMENTED',
  },
  {
    id: 'park-rfid',
    title: 'RfidReadinessPlaceholder',
    phase: 'Frontend Ready / Integration Required',
    moduleName: 'parking',
    featureFlag: 'rfidReadiness',
    permissions: ['READ_SOCIETY'],
    roles: ["RESIDENT"],
    routeNames: ['RFID_READINESS'],
    screenNames: ['RfidReadinessPlaceholderScreen'],
    hookNames: ['useRfidReadiness'],
    repositoryMethods: ['getRfidReadinessStatus'],
    mockDataKeys: ['rfidReadinessMockData'],
    requiredActions: ['Show RFID gate receiver alignment logs'],
    status: 'FRONTEND_READY_INTEGRATION_REQUIRED',
  },
  {
    id: 'vend-dir',
    title: 'VendorDirectory',
    phase: 'MVP',
    moduleName: 'vendorAssets',
    featureFlag: 'vendorManagement',
    permissions: ['READ_SOCIETY'],
    roles: ["ADMIN"],
    routeNames: ['VENDOR_DIRECTORY'],
    screenNames: ['VendorDirectoryScreen'],
    hookNames: ['useVendorDirectory'],
    repositoryMethods: ['listVendors'],
    mockDataKeys: ['vendorDirectoryMockData'],
    requiredActions: ['Search vendors by service, status and AMC expiry'],
    status: 'IMPLEMENTED',
  },
  {
    id: 'vend-contract',
    title: 'VendorContract',
    phase: 'MVP',
    moduleName: 'vendorAssets',
    featureFlag: 'amcManagement',
    permissions: ['READ_SOCIETY'],
    roles: ["ADMIN"],
    routeNames: ['VENDOR_CONTRACT'],
    screenNames: ['VendorContractScreen'],
    hookNames: ['useVendorContract'],
    repositoryMethods: ['getVendorContract'],
    mockDataKeys: ['vendorContractMockData'],
    requiredActions: ['Show contract period, documents and renewal reminder'],
    status: 'IMPLEMENTED',
  },
  {
    id: 'vend-reminders',
    title: 'AmcReminderDashboard',
    phase: 'MVP',
    moduleName: 'vendorAssets',
    featureFlag: 'amcManagement',
    permissions: ['READ_SOCIETY'],
    roles: ["ADMIN"],
    routeNames: ['AMC_REMINDER_DASHBOARD'],
    screenNames: ['AmcReminderDashboardScreen'],
    hookNames: ['useAmcReminders'],
    repositoryMethods: ['listAmcReminders'],
    mockDataKeys: ['amcReminderMockData'],
    requiredActions: ['Filter expired, expiring soon and active AMCs'],
    status: 'IMPLEMENTED',
  },
  {
    id: 'vend-register',
    title: 'AssetRegister',
    phase: 'MVP',
    moduleName: 'vendorAssets',
    featureFlag: 'assetManagement',
    permissions: ['READ_SOCIETY'],
    roles: ["ADMIN"],
    routeNames: ['ASSET_REGISTER'],
    screenNames: ['AssetRegisterScreen'],
    hookNames: ['useAssetRegister'],
    repositoryMethods: ['listAssets'],
    mockDataKeys: ['assetRegisterMockData'],
    requiredActions: ['Add asset with category, location, warranty and AMC'],
    status: 'IMPLEMENTED',
  },
  {
    id: 'vend-schedule',
    title: 'AssetServiceSchedule',
    phase: 'MVP',
    moduleName: 'vendorAssets',
    featureFlag: 'predictiveMaintenance',
    permissions: ['READ_SOCIETY'],
    roles: ["ADMIN"],
    routeNames: ['ASSET_SERVICE_SCHEDULE'],
    screenNames: ['AssetServiceScheduleScreen'],
    hookNames: ['useAssetServiceSchedule'],
    repositoryMethods: ['listAssetServiceSchedules'],
    mockDataKeys: ['assetServiceScheduleMockData'],
    requiredActions: ['Add service schedule and mark service completed'],
    status: 'IMPLEMENTED',
  },
  {
    id: 'vend-inventory',
    title: 'InventoryIssueReturn',
    phase: 'MVP',
    moduleName: 'vendorAssets',
    featureFlag: 'inventoryManagement',
    permissions: ['READ_SOCIETY'],
    roles: ["ADMIN"],
    routeNames: ['INVENTORY_ISSUE_RETURN'],
    screenNames: ['InventoryIssueReturnScreen'],
    hookNames: ['useInventoryIssueReturn'],
    repositoryMethods: ['issueInventoryItem'],
    mockDataKeys: ['inventoryIssueReturnMockData'],
    requiredActions: ['Issue and return inventory item in mock state'],
    status: 'IMPLEMENTED',
  },
  {
    id: 'vend-scorecard',
    title: 'VendorScorecard',
    phase: 'MVP',
    moduleName: 'vendorAssets',
    featureFlag: 'vendorScorecards',
    permissions: ['READ_SOCIETY'],
    roles: ["ADMIN"],
    routeNames: ['VENDOR_SCORECARD'],
    screenNames: ['VendorScorecardScreen'],
    hookNames: ['useVendorScorecard'],
    repositoryMethods: ['getVendorScorecard'],
    mockDataKeys: ['vendorScorecardMockData'],
    requiredActions: ['Show SLA, complaint feedback and service score'],
    status: 'IMPLEMENTED',
  },
  {
    id: 'gov-notice',
    title: 'CreateMeetingNotice',
    phase: 'MVP',
    moduleName: 'governance',
    featureFlag: 'agmSgmMeetings',
    permissions: ['WRITE_SOCIETY'],
    roles: ["RESIDENT"],
    routeNames: ['CREATE_MEETING_NOTICE'],
    screenNames: ['CreateMeetingNoticeScreen'],
    hookNames: ['useCreateMeetingNotice'],
    repositoryMethods: ['createMeetingNotice'],
    mockDataKeys: ['meetingNoticeMockData'],
    requiredActions: ['Create AGM/SGM notice with agenda date and audience'],
    status: 'IMPLEMENTED',
  },
  {
    id: 'gov-agenda',
    title: 'MeetingAgenda',
    phase: 'MVP',
    moduleName: 'governance',
    featureFlag: 'agmSgmMeetings',
    permissions: ['READ_SOCIETY'],
    roles: ["RESIDENT"],
    routeNames: ['MEETING_AGENDA'],
    screenNames: ['MeetingAgendaScreen'],
    hookNames: ['useMeetingAgenda'],
    repositoryMethods: ['listAgendaItems'],
    mockDataKeys: ['meetingAgendaMockData'],
    requiredActions: ['Add agenda item'],
    status: 'IMPLEMENTED',
  },
  {
    id: 'gov-rsvp',
    title: 'MeetingRsvp',
    phase: 'MVP',
    moduleName: 'governance',
    featureFlag: 'agmSgmMeetings',
    permissions: ['READ_SOCIETY'],
    roles: ["RESIDENT"],
    routeNames: ['MEETING_RSVP'],
    screenNames: ['MeetingRsvpScreen'],
    hookNames: ['useMeetingRsvp'],
    repositoryMethods: ['submitMeetingRsvp'],
    mockDataKeys: ['meetingRsvpMockData'],
    requiredActions: ['RSVP attending/not attending'],
    status: 'IMPLEMENTED',
  },
  {
    id: 'gov-proxy',
    title: 'ProxyAuthorization',
    phase: 'MVP',
    moduleName: 'governance',
    featureFlag: 'proxyAuthorization',
    permissions: ['READ_SOCIETY'],
    roles: ["RESIDENT"],
    routeNames: ['PROXY_AUTHORIZATION'],
    screenNames: ['ProxyAuthorizationScreen'],
    hookNames: ['useProxyAuthorization'],
    repositoryMethods: ['submitProxyAuthorization'],
    mockDataKeys: ['proxyAuthorizationMockData'],
    requiredActions: ['Submit proxy authorization placeholder'],
    status: 'IMPLEMENTED',
  },
  {
    id: 'gov-question',
    title: 'QuestionSubmission',
    phase: 'MVP',
    moduleName: 'governance',
    featureFlag: 'agmSgmMeetings',
    permissions: ['READ_SOCIETY'],
    roles: ["RESIDENT"],
    routeNames: ['QUESTION_SUBMISSION'],
    screenNames: ['QuestionSubmissionScreen'],
    hookNames: ['useQuestionSubmission'],
    repositoryMethods: ['submitMeetingQuestion'],
    mockDataKeys: ['meetingQuestionMockData'],
    requiredActions: ['Submit question before meeting'],
    status: 'IMPLEMENTED',
  },
  {
    id: 'gov-mom',
    title: 'MinutesOfMeeting',
    phase: 'MVP',
    moduleName: 'governance',
    featureFlag: 'meetingRecords',
    permissions: ['WRITE_SOCIETY'],
    roles: ["RESIDENT"],
    routeNames: ['MINUTES_OF_MEETING'],
    screenNames: ['MinutesOfMeetingScreen'],
    hookNames: ['useMinutesOfMeeting'],
    repositoryMethods: ['createMinutesOfMeeting'],
    mockDataKeys: ['minutesOfMeetingMockData'],
    requiredActions: ['Add MOM notes and publish placeholder'],
    status: 'IMPLEMENTED',
  },
  {
    id: 'gov-resolutions',
    title: 'ResolutionTracker',
    phase: 'MVP',
    moduleName: 'governance',
    featureFlag: 'resolutionTracker',
    permissions: ['READ_SOCIETY'],
    roles: ["RESIDENT"],
    routeNames: ['RESOLUTION_TRACKER'],
    screenNames: ['ResolutionTrackerScreen'],
    hookNames: ['useResolutionTracker'],
    repositoryMethods: ['listResolutions'],
    mockDataKeys: ['resolutionTrackerMockData'],
    requiredActions: ['Change resolution status'],
    status: 'IMPLEMENTED',
  },
  {
    id: 'gov-createpoll',
    title: 'CreatePoll',
    phase: 'MVP',
    moduleName: 'governance',
    featureFlag: 'polls',
    permissions: ['WRITE_SOCIETY'],
    roles: ["RESIDENT"],
    routeNames: ['CREATE_POLL'],
    screenNames: ['CreatePollScreen'],
    hookNames: ['useCreatePoll'],
    repositoryMethods: ['createPoll'],
    mockDataKeys: ['pollMockData'],
    requiredActions: ['Create poll with options'],
    status: 'IMPLEMENTED',
  },
  {
    id: 'gov-polldetail',
    title: 'PollDetail',
    phase: 'MVP',
    moduleName: 'governance',
    featureFlag: 'polls',
    permissions: ['READ_SOCIETY'],
    roles: ["RESIDENT"],
    routeNames: ['POLL_DETAIL'],
    screenNames: ['PollDetailScreen'],
    hookNames: ['usePollDetail'],
    repositoryMethods: ['submitPollVote'],
    mockDataKeys: ['pollVoteMockData'],
    requiredActions: ['Vote in poll and update result'],
    status: 'IMPLEMENTED',
  },
  {
    id: 'gov-evotingreadiness',
    title: 'EVotingReadiness',
    phase: 'Frontend Ready / Backend Required',
    moduleName: 'governance',
    featureFlag: 'eVoting',
    permissions: ['READ_SOCIETY'],
    roles: ["RESIDENT"],
    routeNames: ['E_VOTING_READINESS'],
    screenNames: ['EVotingReadinessScreen'],
    hookNames: ['useElectionReadiness'],
    repositoryMethods: ['getElectionReadinessStatus'],
    mockDataKeys: ['electionReadinessMockData'],
    requiredActions: ['Check Evoting parameters & regulations compliance status'],
    status: 'FRONTEND_READY_BACKEND_REQUIRED',
  },
  {
    id: 'gov-electionsetup',
    title: 'ElectionSetupPlaceholder',
    phase: 'Frontend Ready / Backend Required',
    moduleName: 'governance',
    featureFlag: 'committeeElection',
    permissions: ['WRITE_SOCIETY'],
    roles: ["RESIDENT"],
    routeNames: ['ELECTION_SETUP'],
    screenNames: ['ElectionSetupPlaceholderScreen'],
    hookNames: ['useElectionReadiness'],
    repositoryMethods: ['getElectionReadinessStatus'],
    mockDataKeys: ['electionReadinessMockData'],
    requiredActions: ['Setup nomination dates, polling windows, and committee positions'],
    status: 'FRONTEND_READY_BACKEND_REQUIRED',
  },
  {
    id: 'gov-nomination',
    title: 'NominationPlaceholder',
    phase: 'Frontend Ready / Backend Required',
    moduleName: 'governance',
    featureFlag: 'committeeElection',
    permissions: ['READ_SOCIETY'],
    roles: ["RESIDENT"],
    routeNames: ['NOMINATION_PLACEHOLDER'],
    screenNames: ['NominationPlaceholderScreen'],
    hookNames: ['useElectionReadiness'],
    repositoryMethods: ['getElectionReadinessStatus'],
    mockDataKeys: ['electionReadinessMockData'],
    requiredActions: ['Submit nomination form with seconder name and signature placeholder'],
    status: 'FRONTEND_READY_BACKEND_REQUIRED',
  },
  {
    id: 'gov-candidate',
    title: 'CandidateProfile',
    phase: 'Frontend Ready / Backend Required',
    moduleName: 'governance',
    featureFlag: 'committeeElection',
    permissions: ['READ_SOCIETY'],
    roles: ["RESIDENT"],
    routeNames: ['CANDIDATE_PROFILE'],
    screenNames: ['CandidateProfileScreen'],
    hookNames: ['useElectionReadiness'],
    repositoryMethods: ['getElectionReadinessStatus'],
    mockDataKeys: ['electionReadinessMockData'],
    requiredActions: ['View candidate photo, manifesto document, and bio'],
    status: 'FRONTEND_READY_BACKEND_REQUIRED',
  },
  {
    id: 'gov-votingeligibility',
    title: 'VotingEligibility',
    phase: 'Frontend Ready / Backend Required',
    moduleName: 'governance',
    featureFlag: 'committeeElection',
    permissions: ['READ_SOCIETY'],
    roles: ["RESIDENT"],
    routeNames: ['VOTING_ELIGIBILITY'],
    screenNames: ['VotingEligibilityScreen'],
    hookNames: ['useElectionReadiness'],
    repositoryMethods: ['getElectionReadinessStatus'],
    mockDataKeys: ['electionReadinessMockData'],
    requiredActions: ['Validate owner occupancy record & financial dues clearance to unlock ballot key'],
    status: 'FRONTEND_READY_BACKEND_REQUIRED',
  },
  {
    id: 'gov-votingresult',
    title: 'VotingResultPlaceholder',
    phase: 'Frontend Ready / Backend Required',
    moduleName: 'governance',
    featureFlag: 'committeeElection',
    permissions: ['READ_SOCIETY'],
    roles: ["RESIDENT"],
    routeNames: ['VOTING_RESULT_PLACEHOLDER'],
    screenNames: ['VotingResultPlaceholderScreen'],
    hookNames: ['useElectionReadiness'],
    repositoryMethods: ['getElectionReadinessStatus'],
    mockDataKeys: ['electionReadinessMockData'],
    requiredActions: ['View live election vote counts & bar chart placeholder'],
    status: 'FRONTEND_READY_BACKEND_REQUIRED',
  },
  {
    id: 'rule-ack',
    title: 'RuleAcknowledgement',
    phase: 'MVP',
    moduleName: 'compliance',
    featureFlag: 'societyRulesAcknowledgement',
    permissions: ['READ_SOCIETY'],
    roles: ["ADMIN"],
    routeNames: ['RULE_ACKNOWLEDGEMENT'],
    screenNames: ['RuleAcknowledgementScreen'],
    hookNames: ['useRuleAcknowledgement'],
    repositoryMethods: ['acknowledgeSocietyRules'],
    mockDataKeys: ['ruleAcknowledgementMockData'],
    requiredActions: ['Acknowledge latest society rules version'],
    status: 'IMPLEMENTED',
  },
  {
    id: 'rule-ackreport',
    title: 'RuleAcknowledgementReport',
    phase: 'MVP',
    moduleName: 'compliance',
    featureFlag: 'societyRulesAcknowledgement',
    permissions: ['WRITE_SOCIETY'],
    roles: ["ADMIN"],
    routeNames: ['RULE_ACKNOWLEDGEMENT_REPORT'],
    screenNames: ['RuleAcknowledgementReportScreen'],
    hookNames: ['useRuleAcknowledgementReport'],
    repositoryMethods: ['getRuleAcknowledgementReport'],
    mockDataKeys: ['ruleAcknowledgementReportMockData'],
    requiredActions: ['Filter acknowledged and pending residents'],
    status: 'IMPLEMENTED',
  },
  {
    id: 'renov-request',
    title: 'RenovationRequest',
    phase: 'MVP',
    moduleName: 'compliance',
    featureFlag: 'renovationWorkflow',
    permissions: ['NOC_WRITE'],
    roles: ["ADMIN"],
    routeNames: ['RENOVATION_REQUEST'],
    screenNames: ['RenovationRequestScreen'],
    hookNames: ['useCreateRenovationRequest'],
    repositoryMethods: ['createRenovationRequest'],
    mockDataKeys: ['renovationRequestMockData'],
    requiredActions: ['Submit renovation request with dates, contractor and affected flats'],
    status: 'IMPLEMENTED',
  },
  {
    id: 'renov-pass',
    title: 'ContractorPass',
    phase: 'MVP',
    moduleName: 'compliance',
    featureFlag: 'renovationWorkflow',
    permissions: ['GATE_VERIFICATION'],
    roles: ["ADMIN"],
    routeNames: ['CONTRACTOR_PASS'],
    screenNames: ['ContractorPassScreen'],
    hookNames: ['useContractorPass'],
    repositoryMethods: ['createContractorPass'],
    mockDataKeys: ['contractorPassMockData'],
    requiredActions: ['Generate contractor pass placeholder'],
    status: 'IMPLEMENTED',
  },
  {
    id: 'renov-debris',
    title: 'DebrisClearanceChecklist',
    phase: 'MVP',
    moduleName: 'compliance',
    featureFlag: 'renovationWorkflow',
    permissions: ['WRITE_SOCIETY'],
    roles: ["ADMIN"],
    routeNames: ['DEBRIS_CLEARANCE_CHECKLIST'],
    screenNames: ['DebrisClearanceChecklistScreen'],
    hookNames: ['useDebrisClearanceChecklist'],
    repositoryMethods: ['updateDebrisClearanceChecklist'],
    mockDataKeys: ['debrisClearanceChecklistMockData'],
    requiredActions: ['Mark debris clearance items completed'],
    status: 'IMPLEMENTED',
  },
  {
    id: 'renov-inspection',
    title: 'DamageInspection',
    phase: 'MVP',
    moduleName: 'compliance',
    featureFlag: 'renovationWorkflow',
    permissions: ['WRITE_SOCIETY'],
    roles: ["ADMIN"],
    routeNames: ['DAMAGE_INSPECTION'],
    screenNames: ['DamageInspectionScreen'],
    hookNames: ['useDamageInspection'],
    repositoryMethods: ['submitDamageInspection'],
    mockDataKeys: ['damageInspectionMockData'],
    requiredActions: ['Submit damage inspection with photo/file proof'],
    status: 'IMPLEMENTED',
  },
  {
    id: 'sos-alert',
    title: 'Sos',
    phase: 'MVP',
    moduleName: 'emergency',
    featureFlag: 'emergency',
    permissions: ['TRIGGER_SOS_ALARM'],
    roles: ["RESIDENT"],
    routeNames: ['SOS'],
    screenNames: ['SosScreen'],
    hookNames: ['useSosAlert'],
    repositoryMethods: ['triggerSosAlert'],
    mockDataKeys: ['sosAlertMockData'],
    requiredActions: ['Trigger mock SOS alert and create incident timeline entry'],
    status: 'IMPLEMENTED',
  },
  {
    id: 'sos-medical',
    title: 'MedicalEmergency',
    phase: 'MVP',
    moduleName: 'emergency',
    featureFlag: 'seniorCitizenCare',
    permissions: ['TRIGGER_SOS_ALARM'],
    roles: ["RESIDENT"],
    routeNames: ['MEDICAL_EMERGENCY'],
    screenNames: ['MedicalEmergencyScreen'],
    hookNames: ['useMedicalEmergency'],
    repositoryMethods: ['triggerMedicalEmergency'],
    mockDataKeys: ['medicalEmergencyMockData'],
    requiredActions: ['Trigger medical emergency mock alert'],
    status: 'IMPLEMENTED',
  },
  {
    id: 'sos-fire',
    title: 'FireAlert',
    phase: 'MVP',
    moduleName: 'emergency',
    featureFlag: 'emergency',
    permissions: ['TRIGGER_SOS_ALARM'],
    roles: ["RESIDENT"],
    routeNames: ['FIRE_ALERT'],
    screenNames: ['FireAlertScreen'],
    hookNames: ['useFireAlert'],
    repositoryMethods: ['triggerFireAlert'],
    mockDataKeys: ['fireAlertMockData'],
    requiredActions: ['Trigger fire alert mock incident'],
    status: 'IMPLEMENTED',
  },
  {
    id: 'sos-lift',
    title: 'LiftStuckAlert',
    phase: 'MVP',
    moduleName: 'emergency',
    featureFlag: 'emergency',
    permissions: ['TRIGGER_SOS_ALARM'],
    roles: ["RESIDENT"],
    routeNames: ['LIFT_STUCK_ALERT'],
    screenNames: ['LiftStuckAlertScreen'],
    hookNames: ['useLiftStuckAlert'],
    repositoryMethods: ['triggerLiftStuckAlert'],
    mockDataKeys: ['liftStuckAlertMockData'],
    requiredActions: ['Trigger lift stuck alert with lift number'],
    status: 'IMPLEMENTED',
  },
  {
    id: 'sos-ack',
    title: 'EmergencyAcknowledgement',
    phase: 'MVP',
    moduleName: 'emergency',
    featureFlag: 'emergency',
    permissions: ['TRIGGER_SOS_ALARM'],
    roles: ["RESIDENT"],
    routeNames: ['EMERGENCY_ACKNOWLEDGEMENT'],
    screenNames: ['EmergencyAcknowledgementScreen'],
    hookNames: ['useEmergencyAcknowledgement'],
    repositoryMethods: ['acknowledgeEmergencyAlert'],
    mockDataKeys: ['emergencyAcknowledgementMockData'],
    requiredActions: ['Responder acknowledges alert'],
    status: 'IMPLEMENTED',
  },
  {
    id: 'sos-timeline',
    title: 'IncidentTimeline',
    phase: 'MVP',
    moduleName: 'emergency',
    featureFlag: 'emergency',
    permissions: ['TRIGGER_SOS_ALARM'],
    roles: ["RESIDENT"],
    routeNames: ['INCIDENT_TIMELINE'],
    screenNames: ['IncidentTimelineScreen'],
    hookNames: ['useIncidentTimeline'],
    repositoryMethods: ['getIncidentTimeline'],
    mockDataKeys: ['incidentTimelineMockData'],
    requiredActions: ['Show alert, acknowledgement and closure events'],
    status: 'IMPLEMENTED',
  },
  {
    id: 'sos-seniorcheckin',
    title: 'SeniorCitizenDailyCheckIn',
    phase: 'MVP',
    moduleName: 'emergency',
    featureFlag: 'seniorCitizenCare',
    permissions: ['READ_RESIDENT'],
    roles: ["RESIDENT"],
    routeNames: ['SENIOR_CITIZEN_DAILY_CHECK_IN'],
    screenNames: ['SeniorCitizenDailyCheckInScreen'],
    hookNames: ['useSeniorDailyCheckIn'],
    repositoryMethods: ['submitSeniorDailyCheckIn'],
    mockDataKeys: ['seniorDailyCheckInMockData'],
    requiredActions: ['Submit daily check-in status'],
    status: 'IMPLEMENTED',
  },
  {
    id: 'sos-volunteers',
    title: 'EmergencyVolunteerNetwork',
    phase: 'MVP',
    moduleName: 'emergency',
    featureFlag: 'emergencyVolunteers',
    permissions: ['READ_RESIDENT'],
    roles: ["RESIDENT"],
    routeNames: ['EMERGENCY_VOLUNTEER_NETWORK'],
    screenNames: ['EmergencyVolunteerNetworkScreen'],
    hookNames: ['useEmergencyVolunteers'],
    repositoryMethods: ['listEmergencyVolunteers'],
    mockDataKeys: ['emergencyVolunteerMockData'],
    requiredActions: ['Register as emergency volunteer'],
    status: 'IMPLEMENTED',
  }
];
