import type { ScenarioDefinition, ScenarioPresetId } from './scenario.types';

export const scenarioPresets: Record<ScenarioPresetId, ScenarioDefinition> = {
  FIRST_INSTALL: {
    id: 'FIRST_INSTALL',
    name: '1. First App Install',
    category: 'onboarding',
    description: 'Fresh application install with zero cached authentication or residences.',
    role: 'owner',
    membershipStatus: 'INVITED',
    residenceCount: 0,
    activeResidenceName: 'No Home Linked',
    activeUnitNumber: '',
    networkState: 'online',
    domain: { isZeroDataHome: true },
    expectedNarrative: 'Connect Your Home',
    expectedPrimaryAction: 'Link a residence or accept invitation',
  },
  NO_HOME: {
    id: 'NO_HOME',
    name: '2. No Linked Residence',
    category: 'onboarding',
    description: 'Authenticated user with zero linked memberships.',
    role: 'owner',
    membershipStatus: 'ENDED',
    residenceCount: 0,
    activeResidenceName: 'No Active Residence',
    activeUnitNumber: '',
    networkState: 'online',
    domain: { isZeroDataHome: true },
    expectedNarrative: 'No Active Home Found',
    expectedPrimaryAction: 'Connect Your Home',
  },
  PENDING_HOME: {
    id: 'PENDING_HOME',
    name: '3. Pending Link Approval',
    category: 'onboarding',
    description: 'Residence link request has been submitted and is under committee review.',
    role: 'tenant',
    membershipStatus: 'PENDING_APPROVAL',
    residenceCount: 1,
    activeResidenceName: 'Green Valley Heights',
    activeUnitNumber: 'A-1204',
    networkState: 'online',
    domain: {},
    expectedNarrative: 'Link Request Under Review',
    expectedPrimaryAction: 'View request progress or withdraw',
  },
  CALM_HOME: {
    id: 'CALM_HOME',
    name: '4. Calm & Peaceful Day',
    category: 'daily_rhythm',
    description: 'All dues clear, no pending issues, no unexpected arrivals. Peaceful Home Pulse.',
    role: 'owner',
    membershipStatus: 'ACTIVE',
    residenceCount: 1,
    activeResidenceName: 'SocietyOS Palms',
    activeUnitNumber: 'Flat 402',
    networkState: 'online',
    domain: {},
    expectedNarrative: 'Home is quiet. Everything is up to date.',
    expectedPrimaryAction: 'Explore society amenities or community',
  },
  BUSY_EVENING: {
    id: 'BUSY_EVENING',
    name: '5. Busy Evening Flow',
    category: 'daily_rhythm',
    description: 'Visitor arriving in 20 min, parcel waiting at gate, maintenance bill due, badminton tonight.',
    role: 'owner',
    membershipStatus: 'ACTIVE',
    residenceCount: 1,
    activeResidenceName: 'SocietyOS Palms',
    activeUnitNumber: 'Flat 402',
    networkState: 'online',
    domain: {
      hasVisitorApproaching: true,
      hasWaitingParcel: true,
      hasDueBill: true,
      hasUpcomingFacilityBooking: true,
      hasStaffInside: true,
    },
    expectedNarrative: 'Moments around home requiring your attention',
    expectedPrimaryAction: 'Review arriving visitor pass & pay dues',
  },
  ATTENTION_OVERLOAD: {
    id: 'ATTENTION_OVERLOAD',
    name: '6. Attention Overload (20+ Signals)',
    category: 'stress_test',
    description: 'High volume of simultaneous signals (overdue bill, critical water leakage, AGM notice, visitors).',
    role: 'owner',
    membershipStatus: 'ACTIVE',
    residenceCount: 1,
    activeResidenceName: 'SocietyOS Palms',
    activeUnitNumber: 'Flat 402',
    networkState: 'online',
    domain: {
      isDenseDataHome: true,
      hasOverdueBill: true,
      hasUrgentComplaint: true,
      hasUrgentNotice: true,
      hasWaitingAtGate: true,
    },
    expectedNarrative: 'Critical items require immediate review',
    expectedPrimaryAction: 'Review emergency water leakage & gate alert',
  },
  PAYMENT_PROCESSING: {
    id: 'PAYMENT_PROCESSING',
    name: '7. Payment In-Flight & App Switch',
    category: 'interruption',
    description: 'User initiated UPI payment of ₹4,850 and switched apps. State must reconcile on resume.',
    role: 'owner',
    membershipStatus: 'ACTIVE',
    residenceCount: 1,
    activeResidenceName: 'SocietyOS Palms',
    activeUnitNumber: 'Flat 402',
    networkState: 'online',
    domain: { hasDueBill: true },
    expectedNarrative: 'Payment processing for August maintenance',
    expectedPrimaryAction: 'Reconcile payment status',
  },
  VISITOR_AT_GATE: {
    id: 'VISITOR_AT_GATE',
    name: '8. Visitor Waiting at Gate',
    category: 'daily_rhythm',
    description: 'Delivery/Guest has arrived at Main Gate and awaits resident confirmation.',
    role: 'owner',
    membershipStatus: 'ACTIVE',
    residenceCount: 1,
    activeResidenceName: 'SocietyOS Palms',
    activeUnitNumber: 'Flat 402',
    networkState: 'online',
    domain: { hasWaitingAtGate: true },
    expectedNarrative: 'Rohan is waiting at Main Gate',
    expectedPrimaryAction: 'Allow gate entry or call security',
  },
  COMPLAINT_WAITING: {
    id: 'COMPLAINT_WAITING',
    name: '9. Active Complaint Repair',
    category: 'lifecycle',
    description: 'Basement plumbing complaint assigned to facility technician with 24h SLA.',
    role: 'tenant',
    membershipStatus: 'ACTIVE',
    residenceCount: 1,
    activeResidenceName: 'SocietyOS Palms',
    activeUnitNumber: 'Flat 402',
    networkState: 'online',
    domain: { hasUrgentComplaint: true },
    expectedNarrative: 'Plumbing repair in progress by facility team',
    expectedPrimaryAction: 'Track repair progress and technician notes',
  },
  DOCUMENT_EXPIRING: {
    id: 'DOCUMENT_EXPIRING',
    name: '10. Document Expiring (3 Days)',
    category: 'lifecycle',
    description: 'Rental agreement document expires in 72 hours; prompt renewal.',
    role: 'tenant',
    membershipStatus: 'EXPIRING',
    residenceCount: 1,
    activeResidenceName: 'SocietyOS Palms',
    activeUnitNumber: 'Flat 402',
    networkState: 'online',
    domain: { hasExpiringDocument: true },
    expectedNarrative: 'Rental agreement expires in 3 days',
    expectedPrimaryAction: 'Upload renewed rental agreement',
  },
  RESTRICTED_ROLE: {
    id: 'RESTRICTED_ROLE',
    name: '11. Restricted Occupant Role',
    category: 'lifecycle',
    description: 'Authorized occupant role with view-only notices and limited booking rights.',
    role: 'authorizedOccupant',
    membershipStatus: 'LIMITED',
    residenceCount: 1,
    activeResidenceName: 'SocietyOS Palms',
    activeUnitNumber: 'Flat 402',
    networkState: 'online',
    domain: {},
    expectedNarrative: 'Authorized Occupant Mode',
    expectedPrimaryAction: 'View society notices and household directory',
  },
  TENANCY_EXPIRING: {
    id: 'TENANCY_EXPIRING',
    name: '12. Tenancy Expiring & Move-Out Prompt',
    category: 'lifecycle',
    description: 'Lease reaches expiry date; prompt tenant move-out clearance or lease extension.',
    role: 'tenant',
    membershipStatus: 'EXPIRING',
    residenceCount: 1,
    activeResidenceName: 'SocietyOS Palms',
    activeUnitNumber: 'Flat 402',
    networkState: 'online',
    domain: { hasExpiringDocument: true },
    expectedNarrative: 'Tenancy term ending on 31 August',
    expectedPrimaryAction: 'Request tenancy extension or start move-out',
  },
  MOVE_OUT: {
    id: 'MOVE_OUT',
    name: '13. Move-Out Clearance Flow',
    category: 'lifecycle',
    description: 'Move-out initiated. Clearance items across finance, parking, and facility pending.',
    role: 'tenant',
    membershipStatus: 'TRANSFER_PENDING',
    residenceCount: 1,
    activeResidenceName: 'SocietyOS Palms',
    activeUnitNumber: 'Flat 402',
    networkState: 'online',
    domain: {},
    expectedNarrative: 'Move-out clearance checklist in progress',
    expectedPrimaryAction: 'Complete utility and parking clearance',
  },
  MULTI_HOME: {
    id: 'MULTI_HOME',
    name: '14. Multi-Home Fast Switching',
    category: 'daily_rhythm',
    description: 'Resident owns Flat 402 in Palms and Flat B-2101 in Rohan Ananta.',
    role: 'owner',
    membershipStatus: 'ACTIVE',
    residenceCount: 2,
    activeResidenceName: 'SocietyOS Palms',
    activeUnitNumber: 'Flat 402',
    networkState: 'online',
    domain: {},
    expectedNarrative: 'Switch between Palms and Rohan Ananta seamlessly',
    expectedPrimaryAction: 'Open Residence Switcher',
  },
  WRONG_HOME_NOTIF: {
    id: 'WRONG_HOME_NOTIF',
    name: '15. Cross-Home Notification Deep Link',
    category: 'interruption',
    description: 'Notification for Home B arrives while user is actively viewing Home A.',
    role: 'owner',
    membershipStatus: 'ACTIVE',
    residenceCount: 2,
    activeResidenceName: 'SocietyOS Palms',
    activeUnitNumber: 'Flat 402',
    networkState: 'online',
    domain: {},
    expectedNarrative: 'Notification targets Flat B-2101 Rohan Ananta',
    expectedPrimaryAction: 'Switch context safely to Rohan Ananta',
  },
  OFFLINE: {
    id: 'OFFLINE',
    name: '16. Complete Offline Mode',
    category: 'stress_test',
    description: 'Network disconnected; cached data displayed, write operations safe-locked.',
    role: 'owner',
    membershipStatus: 'ACTIVE',
    residenceCount: 1,
    activeResidenceName: 'SocietyOS Palms',
    activeUnitNumber: 'Flat 402',
    networkState: 'offline',
    domain: {},
    expectedNarrative: 'Offline mode — viewing cached records',
    expectedPrimaryAction: 'Reconnect to sync gate passes and payments',
  },
  SLOW_NETWORK: {
    id: 'SLOW_NETWORK',
    name: '17. Slow 3G / High Latency',
    category: 'stress_test',
    description: '2,500ms latency injected; shimmer skeletons display without freezing UI.',
    role: 'owner',
    membershipStatus: 'ACTIVE',
    residenceCount: 1,
    activeResidenceName: 'SocietyOS Palms',
    activeUnitNumber: 'Flat 402',
    networkState: 'slow',
    domain: {},
    expectedNarrative: 'Syncing live updates...',
    expectedPrimaryAction: 'Browse available cached feeds while loading',
  },
  SESSION_EXPIRED: {
    id: 'SESSION_EXPIRED',
    name: '18. Session Expired During Form',
    category: 'interruption',
    description: 'Auth session expired while resident was composing a visitor pass.',
    role: 'owner',
    membershipStatus: 'ACTIVE',
    residenceCount: 1,
    activeResidenceName: 'SocietyOS Palms',
    activeUnitNumber: 'Flat 402',
    networkState: 'online',
    domain: {},
    expectedNarrative: 'Session expired — re-authenticate to continue',
    expectedPrimaryAction: 'Re-authenticate and restore composer draft',
  },
  EMERGENCY_ACTIVE: {
    id: 'EMERGENCY_ACTIVE',
    name: '19. Active Crisis / SOS Emergency',
    category: 'interruption',
    description: 'Active medical/fire emergency triggered; Crisis Mode active in society.',
    role: 'owner',
    membershipStatus: 'ACTIVE',
    residenceCount: 1,
    activeResidenceName: 'SocietyOS Palms',
    activeUnitNumber: 'Flat 402',
    networkState: 'online',
    domain: { hasActiveSosEmergency: true },
    expectedNarrative: 'EMERGENCY ALERT: Medical responder dispatched to Tower B',
    expectedPrimaryAction: 'View incident response timeline and guard contacts',
  },
  ZERO_DATA: {
    id: 'ZERO_DATA',
    name: '20. Brand New Flat (Zero Data)',
    category: 'daily_rhythm',
    description: 'First day in unit: no historical visitors, no bills yet, clean slate.',
    role: 'owner',
    membershipStatus: 'ACTIVE',
    residenceCount: 1,
    activeResidenceName: 'SocietyOS Palms',
    activeUnitNumber: 'Flat 402',
    networkState: 'online',
    domain: { isZeroDataHome: true },
    expectedNarrative: 'Welcome to your new home. You are all set up.',
    expectedPrimaryAction: 'Create your first visitor pass or explore amenities',
  },
  HIGH_FONT_SCALE: {
    id: 'HIGH_FONT_SCALE',
    name: '21. 200% Accessibility Font Scale',
    category: 'stress_test',
    description: 'System font set to 200%; verify no layout clipping or button collapse.',
    role: 'owner',
    membershipStatus: 'ACTIVE',
    residenceCount: 1,
    activeResidenceName: 'SocietyOS Palms',
    activeUnitNumber: 'Flat 402',
    networkState: 'online',
    textScale: 2.0,
    domain: {},
    expectedNarrative: 'Accessible high-contrast layout active',
    expectedPrimaryAction: 'Verify typography reflow across all cards',
  },
  TABLET_MULTI_PANE: {
    id: 'TABLET_MULTI_PANE',
    name: '22. Tablet Dual-Pane Landscape View',
    category: 'stress_test',
    description: 'Wide viewport ($> 680px$) rendering master-detail navigation split.',
    role: 'owner',
    membershipStatus: 'ACTIVE',
    residenceCount: 1,
    activeResidenceName: 'SocietyOS Palms',
    activeUnitNumber: 'Flat 402',
    networkState: 'online',
    domain: {},
    expectedNarrative: 'Tablet landscape view with dual-pane layout',
    expectedPrimaryAction: 'Interact with master list alongside detail panel',
  },
};
