import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  screen: { flex: 1 },
  root: {
    ...StyleSheet.absoluteFill,
    zIndex: 1000,
    elevation: 1000,
  },
  safe: { flex: 1 },
  canvas: { flex: 1, paddingHorizontal: 20, paddingTop: 8, paddingBottom: 16 },
  topRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingBottom: 12,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: 'rgba(255, 255, 255, 0.1)',
  },
  context: { flex: 1, gap: 4 },
  liveIndicatorRow: { flexDirection: 'row', alignItems: 'center', gap: 6 },
  pulsingDot: { width: 8, height: 8, borderRadius: 4, backgroundColor: '#EF4444' },
  eyebrow: { letterSpacing: 1.2, fontWeight: '800' },
  residenceText: { letterSpacing: 0.2 },
  cancel: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: 'rgba(255, 255, 255, 0.08)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  scrollCanvas: { paddingVertical: 12, gap: 20 },
  heroCoreSection: { alignItems: 'center', justifyContent: 'center', paddingVertical: 10 },
  radarOuterRing: {
    width: 200,
    height: 200,
    borderRadius: 100,
    backgroundColor: 'rgba(225, 29, 72, 0.08)',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: 'rgba(225, 29, 72, 0.2)',
  },
  radarMiddleRing: {
    width: 160,
    height: 160,
    borderRadius: 80,
    backgroundColor: 'rgba(225, 29, 72, 0.16)',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1.5,
    borderColor: 'rgba(225, 29, 72, 0.4)',
  },
  massiveCore: {
    width: 124,
    height: 124,
    borderRadius: 62,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#E11D48',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.5,
    shadowRadius: 16,
    elevation: 8,
  },
  massiveCoreLabel: { color: '#FFFFFF', fontWeight: '900', letterSpacing: 1, marginTop: 2 },
  massiveCoreSubtext: { color: 'rgba(255, 255, 255, 0.85)', fontSize: 10, marginTop: 2 },
  sectionHeader: { gap: 4 },
  categoryGrid: { gap: 10 },
  categoryCard: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 14,
    borderRadius: 16,
    borderWidth: 1,
    gap: 12,
  },
  categoryIconWrap: {
    width: 44,
    height: 44,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  categoryContent: { flex: 1, gap: 2 },
  categoryTitleRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  guardHotlineCard: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: 14,
    borderRadius: 14,
    marginTop: 4,
  },
  guardHotlineInfo: { flexDirection: 'row', alignItems: 'center', gap: 10, flex: 1 },
  callGuardButton: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#10B981',
  },
  selectedField: { flex: 1, alignItems: 'center', justifyContent: 'center', paddingHorizontal: 16, gap: 20 },
  confirmHeader: { alignItems: 'center', gap: 12 },
  confirmEyebrow: { letterSpacing: 1.2, fontWeight: '800' },
  confirmTitle: { fontWeight: '800' },
  selectedIcon: { width: 96, height: 96, borderRadius: 48, alignItems: 'center', justifyContent: 'center', borderWidth: 2 },
  selectedCopy: { maxWidth: 360, textAlign: 'center' },
  dispatchTargetBox: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    padding: 14,
    borderRadius: 12,
    maxWidth: 420,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.08)',
  },
  commandArea: { width: '100%', gap: 10, paddingTop: 8 },
  command: { minHeight: 56, borderRadius: 16, alignItems: 'center', justifyContent: 'center', paddingHorizontal: 20 },
  secondaryCommand: { minHeight: 44, alignItems: 'center', justifyContent: 'center' },
  liveField: { flex: 1, paddingTop: 16 },
  liveCore: { alignSelf: 'center', width: 92, height: 92, borderRadius: 46, alignItems: 'center', justifyContent: 'center', borderWidth: 2 },
  liveTitle: { marginTop: 14, fontWeight: '800' },
  liveSubtitle: { marginTop: 4 },
  timeline: { marginTop: 24, paddingHorizontal: 12, gap: 0 },
  timelineRow: { minHeight: 68, flexDirection: 'row', gap: 14 },
  timelineRail: { width: 20, alignItems: 'center' },
  timelineDot: { width: 12, height: 12, borderRadius: 6 },
  timelineLine: { width: 1.5, flex: 1 },
  timelineCopy: { flex: 1, paddingBottom: 14, gap: 2 },
  disclosure: { textAlign: 'center', marginTop: 8, opacity: 0.7 },
  fullWidthCommand: { alignSelf: 'stretch' },
});

export function createColor(color: string) { return { color } as const; }
export function createBackground(backgroundColor: string) { return { backgroundColor } as const; }
export function createBorder(borderColor: string) { return { borderColor } as const; }
export function createPosition(left: number, top: number) { return { left, top } as const; }
