export const lightPalette = {
  background: '#F8F9FC',
  backgroundSoft: '#F0F2F7',
  surface: '#FFFFFF',
  surfaceRaised: '#FFFFFF',
  surfaceMuted: '#F5F7FA',
  surfaceGlass: 'rgba(255,255,255,0.82)',
  surfaceAccent: '#F0F4FF',
  shimmer: '#E8ECF4',
  textPrimary: '#0F1729',
  textSecondary: '#3D4A5C',
  textMuted: '#6B7A8D',
  textDisabled: '#9CAABA',
  border: '#E2E6EE',
  borderStrong: '#CDD4DE',
  divider: '#ECEEF3',
  primary: '#172554',
  primarySoft: '#E0E7FF',
  primaryPressed: '#1E3A8A',
  accentIndigo: '#4F46E5',
  accentTeal: '#0F766E',
  accentGold: '#B7791F',
  accentSky: '#0284C7',
  accentRose: '#BE123C',
  success: '#15803D',
  successSoft: '#DCFCE7',
  warning: '#B45309',
  warningSoft: '#FEF3C7',
  danger: '#B91C1C',
  dangerSoft: '#FEE2E2',
  info: '#0369A1',
  infoSoft: '#E0F2FE',
} as const;

export const darkPalette = {
  background: '#070B14',
  backgroundSoft: '#0C1322',
  surface: '#111827',
  surfaceRaised: '#1A2438',
  surfaceMuted: '#0F172A',
  surfaceGlass: 'rgba(17,24,39,0.78)',
  surfaceAccent: '#141E35',
  shimmer: '#1E293B',
  textPrimary: '#F8FAFC',
  textSecondary: '#CBD5E1',
  textMuted: '#94A3B8',
  textDisabled: '#64748B',
  border: '#263149',
  borderStrong: '#334155',
  divider: '#1E293B',
  primary: '#A5B4FC',
  primarySoft: '#1E1B4B',
  primaryPressed: '#818CF8',
  accentIndigo: '#818CF8',
  accentTeal: '#2DD4BF',
  accentGold: '#FBBF24',
  accentSky: '#38BDF8',
  accentRose: '#FB7185',
  success: '#4ADE80',
  successSoft: '#052E16',
  warning: '#FBBF24',
  warningSoft: '#451A03',
  danger: '#F87171',
  dangerSoft: '#450A0A',
  info: '#38BDF8',
  infoSoft: '#082F49',
} as const;

export const palette = {
  ...lightPalette,
  primaryDark: lightPalette.primaryPressed,
  secondary: lightPalette.accentTeal,
  secondarySoft: '#CCFBF1',
  neutral: lightPalette.textSecondary,
  neutralSoft: lightPalette.backgroundSoft,
  white: '#FFFFFF',
  black: '#000000',
  backgroundElevated: lightPalette.surfaceRaised,
  surfaceSoft: lightPalette.backgroundSoft,
  disabled: lightPalette.textDisabled,
  resident: lightPalette.accentIndigo,
  guard: lightPalette.accentTeal,
  admin: lightPalette.accentSky,
  treasurer: lightPalette.accentGold,
  facility: '#7C3AED',
  superAdmin: lightPalette.accentRose,
} as const;

export type Palette = typeof palette;
export type PaletteColor = keyof Palette;
export type ColorToken = PaletteColor;

