import { lightColors, darkColors } from './colorPalette';

export const semanticTokens = {
  light: {
    background: lightColors.appBackground,
    backgroundAlt: lightColors.appBackgroundAlt,
    surface: lightColors.surface,
    surfaceRaised: lightColors.surfaceRaised,
    surfaceMuted: lightColors.surfaceMuted,
    textPrimary: lightColors.textPrimary,
    textSecondary: lightColors.textSecondary,
    textMuted: lightColors.textMuted,
    borderSubtle: lightColors.borderSubtle,
    borderStrong: lightColors.borderStrong,
    success: lightColors.success,
    successBg: lightColors.successBackground,
    warning: lightColors.warning,
    warningBg: lightColors.warningBackground,
    danger: lightColors.danger,
    dangerBg: lightColors.dangerBackground,
    info: lightColors.info,
    infoBg: lightColors.infoBackground,
  },
  dark: {
    background: darkColors.appBackground,
    backgroundAlt: darkColors.appBackgroundAlt,
    surface: darkColors.surface,
    surfaceRaised: darkColors.surfaceRaised,
    surfaceMuted: darkColors.surfaceMuted,
    textPrimary: darkColors.textPrimary,
    textSecondary: darkColors.textSecondary,
    textMuted: darkColors.textMuted,
    borderSubtle: darkColors.borderSubtle,
    borderStrong: darkColors.borderStrong,
    success: darkColors.success,
    successBg: darkColors.successBackground,
    warning: darkColors.warning,
    warningBg: darkColors.warningBackground,
    danger: darkColors.danger,
    dangerBg: darkColors.dangerBackground,
    info: darkColors.info,
    infoBg: darkColors.infoBackground,
  },
};
