import { StyleSheet } from "react-native";
export const styles = StyleSheet.create({
    section: {
        paddingHorizontal: 20,
        marginBottom: 20,
    },
    card: {
        borderRadius: 18,
        borderWidth: 1,
        borderColor: '#e5e7eb',
        padding: 16,
        backgroundColor: '#ffffff',
    },
    row: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    rowBetween: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
    },
    listContainer: {
        padding: 20,
    },
    formContainer: {
        padding: 20,
        gap: 16,
    },
    viewFlexGap: { flex: 1, gap: 6 },
    viewMarginTopGap: { marginTop: 12, gap: 12 },
    viewAlignItems: { alignItems: 'center' },
    shimmerBlockMarginVertical: { marginVertical: 4 },
    viewFlexGap2: { flex: 1, gap: 6 },
    shimmerBlockMarginBottom: { marginBottom: 12 },
    viewGap: { gap: 6 },
    shimmerBlockMarginBottom2: { marginBottom: 12 },
    shimmerBlockMarginBottom3: { marginBottom: 12 },
    shimmerBlockMarginBottom4: { marginBottom: 12 },
    viewFlexGap3: { flex: 1, gap: 6 },
    shimmerBlockMarginBottom5: { marginBottom: 12 },
    viewFlexGap4: { flex: 1, gap: 6 },
    shimmerBlockMarginBottom6: { marginBottom: 12 },
    shimmerBlockMarginBottom7: { marginBottom: 12 },
    shimmerBlockMarginBottom8: { marginBottom: 12 },
    viewGap2: { gap: 10 },
    viewFlexGap5: { flex: 1, gap: 4 },
    viewPaddingVertical: { paddingVertical: 12 },
    viewFlexGap6: { flex: 1, gap: 8 },
    viewGapMarginVertical: { gap: 16, marginVertical: 8 },
    viewAlignSelfMaxWidth: { alignSelf: 'flex-end', maxWidth: '75%' },
    viewGap3: { gap: 6 },
    viewGap4: { gap: 6 },
    viewGap5: { gap: 6 },
    shimmerBlockMarginTop: { marginTop: 12 },
    shimmerBlockMarginBottom9: { marginBottom: 16 },
    shimmerBlockMarginBottom10: { marginBottom: 12 },
    shimmerBlockMarginBottom11: { marginBottom: 14 },
    viewGap6: { gap: 6 },
    viewHeightBackgroundColor: { height: 1, backgroundColor: '#e5e7eb' },
    shimmerBlockMarginTop2: { marginTop: 12 },
    shimmerBlockMarginLeftMarginBottom: { marginLeft: 6, marginBottom: 12 },
    viewGapPaddingLeft: { gap: 12, paddingLeft: 12 },
    shimmerBlockMarginTop3: { marginTop: 4 },
    viewFlexGap7: { flex: 1, gap: 4 },
    viewGap7: { gap: 12 },
    viewHeightBackgroundColorMarginVertical: { height: 1, backgroundColor: '#e5e7eb', marginVertical: 4 },
    shimmerBlockMarginTop4: { marginTop: 6 },
    viewFlexGap8: { flex: 1, gap: 6 },
    viewFlexGap9: { flex: 1, gap: 6 },
    shimmerBlockMarginBottom12: { marginBottom: 16 },
    viewGap8: { gap: 12 },
    shimmerBlockMarginBottom13: { marginBottom: 16 },
    viewGap9: { gap: 12 },
    viewFlexGap10: { flex: 1, gap: 6 },
    viewFlexGap11: { flex: 1, gap: 6 },
    viewAlignItemsGapMarginBottom: { alignItems: 'center', gap: 12, marginBottom: 24 },
    viewGapMarginTop: { gap: 12, marginTop: 12 },
    viewMarginTopGap2: { marginTop: 12, gap: 16 },
    viewGap10: { gap: 12 },
    viewFlexWrapGap: { flexWrap: 'wrap', gap: 8 },
    viewGap11: { gap: 12 },
    viewFlex: { flex: 1 },
    viewGap12: { gap: 10 },
    viewMarginBottom: { marginBottom: 14 },
    viewMarginBottom2: { marginBottom: 8 },
    viewMarginTop: { marginTop: 8 },
    viewGap13: { gap: 12 },
    viewGapMarginTop2: { gap: 12, marginTop: 12 },
    viewGap14: { gap: 12 },
    viewGap15: { gap: 12 },
    viewGapFlexWrap: { gap: 10, flexWrap: 'wrap' },
    viewGap16: { gap: 12 },
    viewGapPaddingVerticalBorderBottomWidthBorderBottomColor: { gap: 12, paddingVertical: 14, borderBottomWidth: 1, borderBottomColor: '#f3f4f6' },
    viewPaddingBottom: { paddingBottom: 80 },
    viewAlignSelfGapMaxWidth: { alignSelf: 'flex-start', gap: 8, maxWidth: '75%' },
    viewMarginBottom3: { marginBottom: 12 },
    viewMarginBottom4: { marginBottom: 8 },
    viewGap17: { gap: 12 },
    viewMarginBottom5: { marginBottom: 12 },
    viewMarginBottom6: { marginBottom: 8 },
    viewBorderTopWidthBorderTopColorPaddingTop: { borderTopWidth: 1, borderTopColor: '#f3f4f6', paddingTop: 10 },
    viewGap18: { gap: 16 },
    viewMarginBottomGap: { marginBottom: 12, gap: 8 },
    viewGapMarginBottom: { gap: 12, marginBottom: 16 },
    viewGap19: { gap: 12 },
    viewMarginBottomGap2: { marginBottom: 12, gap: 10 },
    viewGapFlexWrapMarginBottom: { gap: 10, flexWrap: 'wrap', marginBottom: 16 },
    viewMarginBottom7: { marginBottom: 10 },
    viewGap20: { gap: 12 },
    viewGap21: { gap: 16 },
    viewGap22: { gap: 12 },
    viewMarginBottomGap3: { marginBottom: 10, gap: 8 },
    viewGap23: { gap: 12 },
    viewMarginBottomGap4: { marginBottom: 14, gap: 10 },
    viewGap24: { gap: 12 },
    viewGapJustifyContent: { gap: 8, justifyContent: 'center' },
    viewGapFlexWrap2: { gap: 12, flexWrap: 'wrap' },
    viewWidthGap: { width: '47%', gap: 6 },
    viewMarginBottom8: { marginBottom: 12 },
    viewGap25: { gap: 12 },
    viewGapPaddingVerticalBorderBottomWidthBorderBottomColor2: { gap: 12, paddingVertical: 12, borderBottomWidth: 1, borderBottomColor: '#f3f4f6' },
    viewGap26: { gap: 16 },
    viewGap27: { gap: 12 }
});

