import * as React from 'react';
import { residentHomeContextStore } from '../../modules/resident/homeContext/state/residentHomeContext.store';
import { getResidentHomeFeatureFlagOverrides } from '../../modules/resident/homeContext/utils/residentHomeContextFeatureFlags';

export const featureFlags = {
  coreMvp: {
    residentAuthentication: true,
    residentMemberships: true,
    multiHome: true,
    familyPortability: true,
    rentalDeclaration: true,
    shortStayManagement: false,
    residentDomesticHelp: true,
    residentEmergency: true,
    residentNotifications: true,
    visitorManagement: true,
    guardApp: true,
    complaints: true,
    notices: true,
    maintenanceBilling: true,
    documentVault: true,
    nocRequests: true,
    ownerTenantManagement: true,
    familyMemberManagement: true,
    tenantOnboarding: true,
    tenantDocumentUpload: true,
    tenantAccessPermissionManagement: true,
    staffManagement: true,
    attendanceBasic: true,
    societyOffice: true,
    treasurerDashboard: true,
    facilityDashboard: true,
  },
  advanced: {
    communityMarketplace: true,
    hardwareIntegrationReadiness: false,
    smartAutomation: false,
    advancedAnalytics: false,
  },
  commercialHidden: {
    subscriptionBillingUI: false,
    pricingPage: false,
    upgradePrompts: false,
  },
  realIntegrations: {
    realPayments: false,
    realNotifications: false,
    realFileUpload: false,
    realBiometricIntegration: false,
  },
};


export const defaultFeatureFlags = {
  ...featureFlags.coreMvp,
  ...featureFlags.advanced,
  ...featureFlags.commercialHidden,
  ...featureFlags.realIntegrations,
  
  
  residentMessenger: true,
  publicResidentDirectory: true,
  controlledGroupChat: true,
  parking: true,
  visitorParking: true,
  visitorExitAssurance: true,
  visitorOverstayAlerts: true,
  visitorExpectedExitTime: true,
  visitorExitEscalation: true,
  wrongParkingReports: true,
  rfidReadiness: true,
  anprReadiness: true,
  facilityBooking: true,
  guestRoomBooking: true,
  facilityDeposits: true,
  facilityQrCheckIn: true,
  facilityAdminApproval: true,
  vendorManagement: true,
  amcManagement: true,
  assetManagement: true,
  inventoryManagement: true,
  purchaseRequests: true,
  vendorScorecards: true,
  complianceExpiryDashboard: true,
  governance: true,
  meetingRecords: true,
  polls: true,
  resolutionTracker: true,
  proxyAuthorization: true,
  ownerOnlyVoting: true,
  committeeElection: true,
  eVoting: false,
  legalNoticeTracker: true,
  governanceAuditLogs: true,
  predictiveMaintenance: true,
  biometricAttendanceIntegration: true,
  hardwareIntegration: true,
  
  
  societySetup: true,
  unitMaster: true,
  profileSettings: true,
  darkMode: true,
  pushNotificationsFrontend: true,
  cameraCaptureFrontend: true,
  documentPickerFrontend: true,
  ownerTenantHistory: true,
  occupancyHistory: true,
  residentDocumentArchive: true,
  moveInMoveOutLogistics: true,
  moveOutNocMandatory: true,
  privacyDirectory: true,
  parcelHandover: true,
  digitalNocRequests: true,
  certificateRequests: true,
  societyRulesAcknowledgement: true,
  parkingVehicles: true,
  vendorAmcAssets: true,
  renovationWorkflow: true,
  agmSgmMeetings: true,
  advancedReports: true,
  attendanceDeviceSyncReadiness: true,
  staffShiftRoster: true,
  attendanceCorrectionWorkflow: true,
  seniorCitizenCare: true,
  emergencyVolunteers: true,
  marketplace: true,
  societyHealthScore: true,
  hardwareIntegrationReadiness: true,
  cctvAccessPlaceholder: true,
  anprRfidIntegrationReadiness: true,
  boomBarrierReadiness: true,
  smartMetersReadiness: true,
  evChargingReadiness: true,
  eVotingPlaceholder: true,
  trialExpiryWarnings: false,
  lockedFeatureBadges: false,
  realNotificationsBackend: false,
  realHardwareControl: false,
  realSmartAutomationEngine: false,

  
  societyOfficeMode: true,
  adminUnitMaster: true,
  adminResidentDirectory: true,
  adminPendingApprovals: true,
  adminNoticeControl: true,
  adminComplaintControl: true,
  adminAuditLogs: true,
  chargeHeadManagement: true,
  billingCycleManagement: true,
  manualPaymentEntry: true,
  flatLedger: true,
  defaulterReport: true,
  bankReconciliation: false,
  financialReports: false,
  exportCenter: false,
  adjustmentEntry: true,
  featureConfigurationUI: false,

  
  domesticHelpManagement: true,
  staffAttendance: true,
  manualAttendanceEntry: true,
  attendanceCorrections: true,
  attendanceReports: true,
  biometricDeviceManagement: false,
  vendorAttendanceVerification: true,
  staffIdCard: false,
  attendanceExport: false,

  
  interFlatIssues: false,
  disputeMediation: false,
  facilityInspectionForDisputes: false,
  ruleLibrary: false,
  ruleAcknowledgement: false,
  adminRuleAcknowledgementReport: false,
  ruleViolationPlaceholder: false,
  penaltyReadinessPlaceholder: false,
  realPenaltyBilling: false,
  realEvidenceUpload: false,
  realNeighbourNotifications: false,

  
  complianceOperations: false,
  wasteCompliance: false,
  housekeepingCompliance: false,
  liftSafetyManagement: false,
  fireSafetyManagement: false,
  complianceCalendar: false,
  complianceReports: false,
  complianceAuditLogs: false,
  wasteViolationPlaceholder: false,
  realWastePenaltyBilling: false,
  realCertificateUpload: false,
  realFireAlarmIntegration: false,
  realLiftHardwareIntegration: false,
  realComplianceExport: false,

  
  marketplaceListings: true,
  residentSkillDirectory: true,
  residentServiceListings: true,
  borrowLendCommunityItems: true,
  lostAndFound: true,
  verifiedVendorListingsPlaceholder: true,
  marketplaceModeration: true,
  communityMarketplaceAuditLogs: true,
  realMarketplacePayments: false,
  realVendorOnboarding: false,
  realListingImageUpload: false,
  realMarketplaceDelivery: false,
  publicContactDetails: false,

  
  superAdminConsole: false,
  platformDashboard: false,
  platformSocietyManagement: false,
  platformSocietyOnboarding: false,
  platformFeatureFlagManagement: false,
  hiddenCommercialControls: false,
  platformSupportConsole: false,
  platformUsageAnalytics: false,
  platformModuleAdoptionAnalytics: false,
  platformSocietyHealthOverview: false,
  platformOperationalAlerts: false,
  platformIntegrationStatusPlaceholder: false,
  platformNotificationStatusPlaceholder: false,
  platformDataExportPlaceholder: false,
  platformImpersonationPlaceholder: false,
  platformReleaseRolloutPlaceholder: false,

  
  deviceRegistry: true,
  gateHardwareReadiness: true,
  boomBarrierPlaceholder: true,
  smartMeterReadiness: true,
  biometricConnectorAlignment: true,
  hardwareSyncLogs: true,
  hardwareEventLogs: true,
  hardwareAuditLogs: true,
  realRfidIntegration: false,
  realAnprIntegration: false,
  realBoomBarrierControl: false,
  realCctvStreaming: false,
  realSmartMeterConnector: false,
  realEvChargingConnector: false,
  realHardwareCommandExecution: false,
} as const;

export type FeatureFlags = typeof defaultFeatureFlags;
export type FeatureFlagKey = keyof FeatureFlags;

export function useFeatureFlags() {
  const refetch = React.useCallback(async () => undefined, []);
  const activeHome = React.useSyncExternalStore(
    residentHomeContextStore.subscribe,
    residentHomeContextStore.getActiveContext,
    residentHomeContextStore.getActiveContext
  );
  const runtimeFeatureFlags: Record<FeatureFlagKey, boolean> = {
    ...defaultFeatureFlags,
    ...getResidentHomeFeatureFlagOverrides(activeHome),
  };

  return {
    flags: runtimeFeatureFlags,
    isEnabled: (flag: FeatureFlagKey) => runtimeFeatureFlags[flag],
    isLoading: false,
    error: null,
    refetch,
  };
}
