import type { ComponentProps } from 'react';
import Ionicons from '@expo/vector-icons/Ionicons';

export type AppIconAlias =
  | "home"
  | "visitor"
  | "complaint"
  | "notice"
  | "bill"
  | "receipt"
  | "document"
  | "noc"
  | "guard"
  | "gate"
  | "staff"
  | "attendance"
  | "unit"
  | "resident"
  | "admin"
  | "treasurer"
  | "facility"
  | "profile"
  | "settings"
  | "logout"
  | "search"
  | "filter"
  | "calendar"
  | "clock"
  | "success"
  | "warning"
  | "error"
  | "empty"
  | "lock"
  | "privacy"
  | "audit"
  | "arrowRight"
  | "chevronRight"
  | "qr"
  | "vehicle"
  | "payment"
  | "wallet"
  | "menu"
  | "more"
  | "users"
  | "building"
  | "shield"
  | "support"
  | "add"
  | "close"
  | "check"
  | "info"
  | "chevronDown"
  | "chevronUp"
  | "refresh"
  | "person"
  | "edit"
  | "delete"
  | "camera"
  | "biometric"
  | "forward";
export type AppIconName = AppIconAlias | ComponentProps<typeof Ionicons>['name'];
export default AppIconName;
