import type { AppIconAlias } from './icon.types';
import type { ComponentProps } from 'react';
import Ionicons from '@expo/vector-icons/Ionicons';

type IoniconsName = ComponentProps<typeof Ionicons>['name'];

export const iconRegistry: Record<AppIconAlias, IoniconsName> = {
  home: 'home-outline',
  visitor: 'people-outline',
  complaint: 'alert-circle-outline',
  notice: 'megaphone-outline',
  bill: 'receipt-outline',
  receipt: 'document-text-outline',
  document: 'folder-open-outline',
  noc: 'document-attach-outline',
  guard: 'shield-half-outline',
  gate: 'enter-outline',
  staff: 'people-circle-outline',
  attendance: 'calendar-clear-outline',
  unit: 'business-outline',
  resident: 'person-outline',
  admin: 'key-outline',
  treasurer: 'cash-outline',
  facility: 'construct-outline',
  profile: 'person-circle-outline',
  settings: 'settings-outline',
  logout: 'log-out-outline',
  search: 'search-outline',
  filter: 'funnel-outline',
  calendar: 'calendar-outline',
  clock: 'time-outline',
  success: 'checkmark-circle-outline',
  warning: 'warning-outline',
  error: 'alert-circle-outline',
  empty: 'archive-outline',
  lock: 'lock-closed-outline',
  privacy: 'eye-off-outline',
  audit: 'list-outline',
  arrowRight: 'arrow-forward-outline',
  chevronRight: 'chevron-forward-outline',
  qr: 'qr-code-outline',
  vehicle: 'car-outline',
  payment: 'card-outline',
  wallet: 'wallet-outline',
  menu: 'menu-outline',
  more: 'ellipsis-horizontal-outline',
  users: 'people-outline',
  building: 'business-outline',
  shield: 'shield-outline',
  support: 'help-buoy-outline',
  add: 'add-outline',
  close: 'close-outline',
  check: 'checkmark-outline',
  info: 'information-circle-outline',
  chevronDown: 'chevron-down-outline',
  chevronUp: 'chevron-up-outline',
  refresh: 'refresh-outline',
  person: 'person-outline',
  edit: 'create-outline',
  delete: 'trash-outline',
  camera: 'camera-outline',
  biometric: 'finger-print-outline',
  forward: 'arrow-forward-outline',
};
export default iconRegistry;
